### ISSUE TITLE
lmer model: wrong order in emtrends after relevel()

### ISSUE THREAD

**Issue by forstem6** [rvlenth/emmeans#92] opened 2019-02-25 14:55 UTC
First of all, thank you for a really helpful package.

I ran a linear mixed model (in lmerTest) with a factor (3 levels) and a covariate. I looked at the slopes of the covariate separately for each level of my factor with `emtrends()`. When reordering the factor (`relevel()`) and rerunning  `emtrends()`, I found that the order of the labels in the output of `emtrends()` was changed (as intended), the slopes (and other stats) however were in the same order as in the first run. Thus, the slopes did not match the factor level anymore.

To make a reproducible example:
```
> m <- lmer(weight ~ Time * Diet + (1|Chick), data = ChickWeight)
> emtrends(m, "Diet", var = "Time")
 Diet Time.trend    SE  df lower.CL upper.CL
 1          6.71 0.258 533     6.20     7.22
 2          8.61 0.342 525     7.94     9.28
 3         11.42 0.342 525    10.75    12.09
 4          9.66 0.349 525     8.98    10.35

Degrees-of-freedom method: satterthwaite 
Confidence level used: 0.95 
> ChickWeight$Diet <- relevel(ChickWeight$Diet, ref = "2")
> emtrends(m, "Diet", var = "Time")
 Diet Time.trend    SE   df lower.CL upper.CL
 2          6.71 0.258  171     6.20     7.22
 1          8.61 0.342 1630     7.94     9.28
 3         11.42 0.342  525    10.75    12.09
 4          9.66 0.349  525     8.98    10.35

Degrees-of-freedom method: satterthwaite 
Confidence level used: 0.95 
```

Interestingly, when I try the same with a linear model `lm()`, rerunning `emtrends()` after changing the reference level gives an error.
```
Error in model.matrix(trms, m, contrasts.arg = object$contrasts)[, nm,  : 
  subscript out of bounds
```

Maybe I overlooked something. Hope it helps.

Best,
Michael

**Comment by rvlenth** [comment] 2019-02-25 16:24
At first, I thought it is a manifestation of a known bug - #83 -- and was going to assure you that an update on CRAN is forthcoming soon. However, I reproduced your results on my patched version. But the reason it happens is because you should have re-fitted the model:
```
> m.new <- lmer(weight ~ Time * Diet + (1|Chick), data = ChickWeight)
> emtrends(m.new, "Diet", var = "Time")
 Diet Time.trend    SE  df lower.CL upper.CL
 2          8.61 0.342 524     7.94     9.28
 1          6.71 0.258 532     6.20     7.22
 3         11.42 0.342 524    10.75    12.09
 4          9.66 0.349 525     8.98    10.35

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 
```
Now the means are correctly associated with the levels. In model `m`, the internal model matrix is still the one built with level 1 as the reference level, so we get the same estimates but (look at the output and notice) the d.f. get messed-up.

The above, however, is with Kenward-Roger d.f. I get a curious result if I want Satterthwaite d.f.:
```
> emtrends(m.new, "Diet", var = "Time", mode="satt")
Error in data[[var]] : subscript out of bounds
> emtrends(m, "Diet", var = "Time", mode="satt")  # this worked before...
Error in data[[var]] : subscript out of bounds
```
I think something has gotten corrupted internally in the Satterthwaite code with this re-leveling?

**Comment by rvlenth** [comment] 2019-02-25 16:33
Footnote: Keep in mind that **emmeans**'s routines recover the data to do their work. That usually involves running a modified version of the model call, which often contains a `data` argument. Thus, if you change the data, you also change the `emmeans()` and `emtrends()` results!

I strongly recommend that when you are constructing examples comparing one method with another, you never re-use the same object names in the two (or more) comparison cases. Use different names for the model objects, and if you modify the data or some variables used, use different names for those too. Besides avoiding the possibility of corrupting existing things, it also makes it much easier for me to dissect what is going on.

**Comment by forstem6** [comment] 2019-02-26 07:08
Thanks for the quick reply and the clarification. I actually noticed before that `emmeans()` recovers the data , but did not connect it to the issue. It makes total sense now.
As I am new a newbie and keen to learn, a quick follow-up on your remark: In my example I (unfortunately) left out the part where I constructed the linear model (`lm() call`). But I definitely created another model with a new name at the `lm()` call.

**Comment by rvlenth** [comment] 2019-02-26 13:58
So please clarify. With your actual example, with the model re-fitted, is this still an issue?

**Comment by forstem6** [comment] 2019-02-26 14:21
Sorry, I think I made it unclearer with my response. I only meant that the `lmer()`model and the `lm()`model have different names.
When I refit the model after changing the reference level and then run `emtrends()` on this new model the means are in the correct order. 
As far as I can see, the issue, as you explained, arises when you rerun `emtrends()` after having changed the data, but not having refitted the model.

I only wanted to raise awareness to this issue, because it happened to me that I ran a model, following it up with `emtrends()`. Then I changed the reference level of a factor (without assigning this change to a new dataset). After moving on in my analysis, I wanted to check the slopes again by just rerunning the line with the `emtrends()` call in my script and this is when I encountered the issue. You might say this is bad practice, because it leads to errors (as this example nicely shows), but I guess others might fall into the same trap. 
I guess this can be closed, but I would like to give you the final call.

**Comment by rvlenth** [comment] 2019-02-27 00:37
OK, thanks. I wish there were a way to detect that data had changed since a model was fitted, as it is a potential trap. But AFAIK there is no time stamp on R objects... Gonna close this & hope for the best. Thanks for alerting me to this again.

**Closed by rvlenth** 2019-02-27 00:37 UTC
Labels: question
