### ISSUE TITLE
emtrends: max.degree > 1 does not work with "overall" spec

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#197] opened 2020-05-19 05:45 UTC
Getting an error when using the "overall" spec in `emtrends` and setting `max.degree` > 1:

``` r
library(emmeans)

model <- lm(Sepal.Length ~ poly(Petal.Length,2), data = iris)

# works
emtrends(model, ~ 1, "Petal.Length", max.degree = 1)
#>  1       Petal.Length.trend     SE  df lower.CL upper.CL
#>  overall              0.448 0.0181 147    0.413    0.484
#> 
#> Confidence level used: 0.95


# does not work
emtrends(model, ~ 1, "Petal.Length", max.degree = 2)
#> Error in emmeans(object = new("emmGrid", model.info = list(call = lm(formula = Sepal.Length ~ : No variable named 1 in the reference grid
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rvlenth** [comment] 2020-05-19 15:42
Thanks for the report. It turns out this error isn't actually in `emtrends()`. It occurs in the very last line when it runs `emmeans()` on the result:
```r
> emtrends(model, ~ 1, "Petal.Length", max.degree = 2)
 Error in emmeans(object = new("emmGrid", model.info = list(call = lm(formula = Sepal.Length ~  : 
  No variable named 1 in the reference grid 

> ### The reference grid is saved before the error occurs:
> .Last.ref_grid
'emmGrid' object with variables:
    Petal.Length = 3.758
    degree = linear, quadratic

> ### We can run `emmeans() on this result:
> emmeans(.Last.ref_grid, ~1|degree)
degree = linear:
 Petal.Length.trend     SE  df lower.CL upper.CL
             0.4474 0.0180 147   0.4119    0.483

degree = quadratic:
 Petal.Length.trend     SE  df lower.CL upper.CL
             0.0815 0.0132 147   0.0554    0.108

Confidence level used: 0.95 

> ### ... but not the way it is called from emtrends()
> emmeans(.Last.ref_grid, ~1, by = "degree")
Error in emmeans(.Last.ref_grid, ~1, by = "degree") : 
  No variable named 1 in the reference grid
```
Gotta go run errands. But I will track that down and report again.

**Comment by rvlenth** [comment] 2020-05-19 16:06
OK, It's fixed:
```r
> emtrends(model, ~ 1, "Petal.Length", max.degree = 2)
degree = linear:
 Petal.Length.trend     SE  df lower.CL upper.CL
             0.4474 0.0180 147   0.4119    0.483

degree = quadratic:
 Petal.Length.trend     SE  df lower.CL upper.CL
             0.0815 0.0132 147   0.0554    0.108

Confidence level used: 0.95 

> ### This would have worked before...
> emtrends(model, ~degree, "Petal.Length", max.degree = 2)
 degree    Petal.Length.trend     SE  df lower.CL upper.CL
 linear                0.4474 0.0180 147   0.4119    0.483
 quadratic             0.0815 0.0132 147   0.0554    0.108

Confidence level used: 0.95 

> ### But this still errors, because we don't create a `degree` variable when it is only 1
> emtrends(model, ~ degree, "Petal.Length", max.degree = 1)
 Error in emmeans(object = new("emmGrid", model.info = list(call = lm(formula = Sepal.Length ~  : 
  No variable named degree in the reference grid 
```

**Comment by rvlenth** [comment] 2020-05-19 16:15
Going ahead and closing this. Thanks again for the report and your usual easy reproducibility of the bug in question.

**Closed by rvlenth** 2020-05-19 16:15 UTC

**Comment by mattansb** [comment] 2020-05-19 18:06
@rvlenth Thanks!
