### ISSUE TITLE
Question: Documentation of Column Names of Outputs

### ISSUE THREAD

**Issue by billdenney** [rvlenth/emmeans#126] opened 2019-07-17 18:11 UTC
Thank you for the emmeans package, I find it very useful for my work!

As I've rerun some older code with newer versions of emmeans, the column names have changed and in some cases, the outputs have subtly changed.  As I review how the changes occurred, I think that they make sense, but I'm curious:  Is there documentation of what column names are generated by the as.data.frame methods and also how they have changed with new versions of emmeans?

**Comment by rvlenth** [comment] 2019-07-18 01:55
Labeling of columns has evolved some, and I am sorry if this has caused problems for you in using old scripts. There is some mention of these changes in the NEWS file, but probably not all. The names for the `as.data.frame` method are those generated by `summary.emmGrid`, so you could look at the code for that and possibly see how they are generated. There is special handling when back-transforming, and this relates to `emm_options(inv.lbl = ...)` with special defaults for log and logit transformations.

If the issue is with the name of the estimator, that can be accessed or changed:
```r
emm = emmeans(...)
main.name = emm@misc$estName
emm = update(emm, estName = "EMM")

summ = summary(emm)
attr(summ, "estName")
```
When creating contrasts, you can also rename the column with the levels:
```r
pairs(emm, name = "trt levels")
```

A related matter is that I fairly recently had it default to display the results in more reasonable precision (previously it was usually too many digits to really justify). You can revert to the old behavior by doing `emm_options(opt.digits = FALSE)`.

I'm going to go ahead and close this issue as I think I've answered the question, but that does not keep you from re-opening it and/or asking more in this thread.

**Closed by rvlenth** 2019-07-18 01:55 UTC
Labels: question

**Comment by billdenney** [comment] 2019-07-18 02:24
Thanks for the detailed response!

I thought that I looked for the changes in NEWS, but I guess I upgraded several versions since the older code.
