### ISSUE TITLE
Warning with formula interface

### ISSUE THREAD

**Issue by knokknok** [rvlenth/emmeans#234] opened 2020-10-18 11:23 UTC
As experienced in the vignette (https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html), emmeans produces a warning with the formula interface:

org.aov <- aov(sales1 ~ day + Error(store), data = oranges,
               contrasts = list(day = "contr.sum"))
org.emml <- emmeans(org.aov, consec ~ day)

Warning message:
In sweep(X, 1, sqrt(weights), "*") :
  STATS is longer than the extent of 'dim(x)[MARGIN]'

**Comment by rvlenth** [comment] 2020-10-18 16:30
Thanks. It turns out that no harm is done. But I'm still surprised that that warning didn't cause issues with the CRAN checking routines. 

The issue is related to the `submodel` option. I'll look at why this happened and see if I can fix it. `aovlist` objects are tricky; I suspect this is related to imbalance.

**Comment by esmccallum** [comment] 2020-10-19 14:23
I am also receiving the exact same warning for a gls (nlme) model I am running emmeans on.

mod1 <- gls(log(Mass_mg)~(OxaTreatment+PredatorTreatment+Date)^2, weights=varIdent(form= ~ 1|Date), method="ML", data=dat.na)

emm2 <- (emmeans(mod1, ~ (OxaTreatment+PredatorTreatment+Date)^2))

Warning message:
In sweep(X, 1, sqrt(weights), "*") :
  STATS is longer than the extent of 'dim(x)[MARGIN]'

However emmeans seems to still be generating sensible output given the data.

**Comment by rvlenth** [comment] 2020-10-19 15:55
Aarghh. Turns out to be a stupid coding error in setting a default. I made a simple change and now we don't get that warning, at least with these examples:

```r
> emmeans(org.aov, consec ~ day)
$emmeans
 day emmean   SE   df lower.CL upper.CL
 1     7.87 2.77 29.2     2.21     13.5
 2     7.10 2.77 29.2     1.43     12.8
 3    13.76 2.77 29.2     8.09     19.4
 4     8.04 2.77 29.2     2.37     13.7
 5    12.92 2.77 29.2     7.26     18.6
 6    11.60 2.77 29.2     5.94     17.3

Warning: EMMs are biased unless design is perfectly balanced 
Confidence level used: 0.95 

$contrasts
 contrast estimate   SE df t.ratio p.value
 2 - 1      -0.772 3.78 25 -0.204  0.9997 
 3 - 2       6.658 3.78 25  1.763  0.3243 
 4 - 3      -5.716 3.78 25 -1.513  0.4683 
 5 - 4       4.882 3.78 25  1.293  0.6127 
 6 - 5      -1.321 3.78 25 -0.350  0.9965 

P value adjustment: mvt method for 5 tests 
```
I'll push it to github and it will be in next CRAN update. In the meantime, it is in a provision for saving info to be used later if `update(object, submodel = ...)` is called. If you don't use `submodel`, it won't affect your results.

**Comment by esmccallum** [comment] 2020-10-20 09:07
Thanks! 👍

**Comment by rvlenth** [comment] 2020-11-01 20:34
Closing, as I think this is fixed.

**Closed by rvlenth** 2020-11-01 20:34 UTC
Labels: bug
