### ISSUE TITLE
Different behavior when as.formula() is used

### ISSUE THREAD

**Issue by fanli-gcb** [rvlenth/emmeans#166] opened 2019-12-13 20:07 UTC
I usually use the `as.formula(sprintf(" ... "))` construct with `lmer` and `emmeans`, but recently noticed that this was throwing a warning message:
```
Note: Use 'contrast(regrid(object), ...)' to obtain contrasts of back-transformed estimates
Warning messages:
1: In if (tran == "linkfun") tran = as.list(environment(trms)) else { :
  the condition has length > 1 and only the first element will be used
2: In if (tran == "I") tran = "identity" :
  the condition has length > 1 and only the first element will be used
```

Reproducible example:
```
set.seed(115)
df <- data.frame(value=rnorm(100), group=factor(c(rep("Group1", 50), rep("Group2", 50))), PID=factor(rep(1:20, each=5)))

mod <- lmer(value ~ group + (1 | PID), data=df); modelstr <- "LMER"
mod.formula <- lmer(as.formula(sprintf("value ~ group + (1 | PID)")), data=df)

e1 <- emmeans(mod, pairwise ~ group)
e2 <- emmeans(mod.formula, pairwise ~ group)
```

The numeric results in `e1` and `e2` are identical, with only an additional note in `e2`:
```
> e1
$emmeans
 group   emmean    SE df lower.CL upper.CL
 Group1 -0.0249 0.145 18   -0.330    0.280
 Group2  0.1878 0.145 18   -0.117    0.493

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 

$contrasts
 contrast        estimate    SE df t.ratio p.value
 Group1 - Group2   -0.213 0.205 18 -1.037  0.3135 

Degrees-of-freedom method: kenward-roger 
```

```
> e2
$emmeans
 group   emmean    SE df lower.CL upper.CL
 Group1 -0.0249 0.145 18   -0.330    0.280
 Group2  0.1878 0.145 18   -0.117    0.493

Degrees-of-freedom method: kenward-roger 
Results are given on the (.| (not the response) scale. 
Confidence level used: 0.95 

$contrasts
 contrast        estimate    SE df t.ratio p.value
 Group1 - Group2   -0.213 0.205 18 -1.037  0.3135 

Note: contrasts are still on the (.| scale
Degrees-of-freedom method: kenward-roger 

```

output from `sessionInfo()`:
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] emmeans_1.4.3.01 lmerTest_3.1-0   lme4_1.1-21      Matrix_1.2-17   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3          pillar_1.4.2        compiler_3.6.1     
 [4] nloptr_1.2.1        plyr_1.8.5          tools_3.6.1        
 [7] boot_1.3-20         lifecycle_0.1.0     tibble_2.1.3       
[10] nlme_3.1-139        gtable_0.3.0        lattice_0.20-38    
[13] pkgconfig_2.0.3     rlang_0.4.2         parallel_3.6.1     
[16] mvtnorm_1.0-11      dplyr_0.8.3         grid_3.6.1         
[19] tidyselect_0.2.5    glue_1.3.1          R6_2.4.1           
[22] minqa_1.2.4         ggplot2_3.2.1       purrr_0.3.3        
[25] magrittr_1.5        scales_1.1.0        MASS_7.3-51.1      
[28] splines_3.6.1       assertthat_0.2.1    pbkrtest_0.4-7     
[31] colorspace_1.4-1    xtable_1.8-4        numDeriv_2016.8-1.1
[34] estimability_1.3    lazyeval_0.2.2      munsell_0.5.0      
[37] crayon_1.3.4 
```

This isn't a big deal since an easy workaround is to simply avoid using `as.formula`, but it would be nice to understand why this happens. Thanks!

**Comment by rvlenth** [comment] 2019-12-13 23:08
It happens because `emmeans()` (actually `ref_grid()`) looks at the model formula to see if there is a response transformation. So your `as.formula` stuff gets in the way and confuses it.

Russ

Sent from my iPhone

On Dec 13, 2019, at 2:07 PM, Fan Li <notifications@github.com<mailto:notifications@github.com>> wrote:


I usually use the as.formula(sprintf(" ... ")) construct with lmer and emmeans, but recently noticed that this was throwing a warning message:

Note: Use 'contrast(regrid(object), ...)' to obtain contrasts of back-transformed estimates
Warning messages:
1: In if (tran == "linkfun") tran = as.list(environment(trms)) else { :
  the condition has length > 1 and only the first element will be used
2: In if (tran == "I") tran = "identity" :
  the condition has length > 1 and only the first element will be used


Reproducible example:

set.seed(115)
df <- data.frame(value=rnorm(100), group=factor(c(rep("Group1", 50), rep("Group2", 50))), PID=factor(rep(1:20, each=5)))

mod <- lmer(value ~ group + (1 | PID), data=df); modelstr <- "LMER"
mod.formula <- lmer(as.formula(sprintf("value ~ group + (1 | PID)")), data=df)

e1 <- emmeans(mod, pairwise ~ group)
e2 <- emmeans(mod.formula, pairwise ~ group)


The numeric results in e1 and e2 are identical, with only an additional note in e2:

> e1
$emmeans
 group   emmean    SE df lower.CL upper.CL
 Group1 -0.0249 0.145 18   -0.330    0.280
 Group2  0.1878 0.145 18   -0.117    0.493

Degrees-of-freedom method: kenward-roger
Confidence level used: 0.95

$contrasts
 contrast        estimate    SE df t.ratio p.value
 Group1 - Group2   -0.213 0.205 18 -1.037  0.3135

Degrees-of-freedom method: kenward-roger


> e2
$emmeans
 group   emmean    SE df lower.CL upper.CL
 Group1 -0.0249 0.145 18   -0.330    0.280
 Group2  0.1878 0.145 18   -0.117    0.493

Degrees-of-freedom method: kenward-roger
Results are given on the (.| (not the response) scale.
Confidence level used: 0.95

$contrasts
 contrast        estimate    SE df t.ratio p.value
 Group1 - Group2   -0.213 0.205 18 -1.037  0.3135

Note: contrasts are still on the (.| scale
Degrees-of-freedom method: kenward-roger



output from sessionInfo():

R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] emmeans_1.4.3.01 lmerTest_3.1-0   lme4_1.1-21      Matrix_1.2-17

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3          pillar_1.4.2        compiler_3.6.1
 [4] nloptr_1.2.1        plyr_1.8.5          tools_3.6.1
 [7] boot_1.3-20         lifecycle_0.1.0     tibble_2.1.3
[10] nlme_3.1-139        gtable_0.3.0        lattice_0.20-38
[13] pkgconfig_2.0.3     rlang_0.4.2         parallel_3.6.1
[16] mvtnorm_1.0-11      dplyr_0.8.3         grid_3.6.1
[19] tidyselect_0.2.5    glue_1.3.1          R6_2.4.1
[22] minqa_1.2.4         ggplot2_3.2.1       purrr_0.3.3
[25] magrittr_1.5        scales_1.1.0        MASS_7.3-51.1
[28] splines_3.6.1       assertthat_0.2.1    pbkrtest_0.4-7
[31] colorspace_1.4-1    xtable_1.8-4        numDeriv_2016.8-1.1
[34] estimability_1.3    lazyeval_0.2.2      munsell_0.5.0
[37] crayon_1.3.4


This isn't a big deal since an easy workaround is to simply avoid using as.formula, but it would be nice to understand why this happens. Thanks!

**Comment by rvlenth** [comment] 2019-12-24 03:26
I actually wasn't able to reproduce the error message with the example you gave; but I was able to do so with a similar scenario based on `example(fiber)`. I think it is now working correctly.

**Comment by rvlenth** [comment] 2020-01-06 19:04
I think this is working correctly in the recent github updates, so I am closing this. Let me know though if your concerns reamin.

**Closed by rvlenth** 2020-01-06 19:04 UTC
