### ISSUE TITLE
Building from github fails on Windows

### ISSUE THREAD

**Issue by Generalized** [rvlenth/emmeans#497] opened 2024-07-04 16:39 UTC
Hi,

I use the command  `remotes::install_github("rvlenth/emmeans", dependencies = TRUE, build_opts = "")`

It always worked, until now. I wanted to update the version that pools the degrees of freedom from imputed data. I noticed you mentioned some error in the code (*2 rather than ^2) and I'm afraid if my current version has this error...

But now it fails completely

```
Enter one or more numbers, or an empty line to skip updates: 
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\.........\Temp\RtmpaGmsoH\remotes3a20159a5b54\rvlenth-emmeans-ce2cddf/DESCRIPTION' ... 
─  preparing 'emmeans': (433ms)
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts (419ms)
─  checking for empty or unneeded directories
─  building 'emmeans_1.10.3.tar.gz'
   
    ERROR
   cannot change to directory ''
Error: Failed to install 'emmeans' from GitHub:
! System command 'Rcmd.exe' failed
```

I use R 4.2.0

-------

OK, it works when the parameter `build_opts` is removed, i.e. this work: `remotes::install_github("rvlenth/emmeans")`

**Comment by rvlenth** [comment] 2024-07-04 16:49
Use install.packages("emmeans"). It's the same version right now.

Russ

On Jul 4, 2024, at 11:40 AM, Generalized ***@***.***> wrote:

﻿

Hi,

I use the command remotes::install_github("rvlenth/emmeans", dependencies = TRUE, build_opts = "")

It always worked, until now. I wanted to update the version that pools the degrees of freedom from imputed data. I noticed you mentioned some error in the code (*2 rather than ^2) and I'm afraid if my current version has this error...

But now it fails completely

Enter one or more numbers, or an empty line to skip updates:
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\.........\Temp\RtmpaGmsoH\remotes3a20159a5b54\rvlenth-emmeans-ce2cddf/DESCRIPTION' ...
─  preparing 'emmeans': (433ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (419ms)
─  checking for empty or unneeded directories
─  building 'emmeans_1.10.3.tar.gz'

    ERROR
   cannot change to directory ''
Error: Failed to install 'emmeans' from GitHub:
! System command 'Rcmd.exe' failed


I use R 4.2.0

**Comment by Generalized** [comment] 2024-07-04 16:58
Thank you.
It also works when the parameter build_opts is removed, i.e. this work: `remotes::install_github("rvlenth/emmeans")`

And thank God I updated it, because I realized that the DFs are different from what I had previously working with imputed data.  Now each row has different DF, which shows that the pooling is actually done through Rubin's rules. Now I have the chance to update all analyses before sending my work.

**Comment by rvlenth** [comment] 2024-07-04 20:26
I'm not sure what the question is anymore. And I still need a reproducible example, preferably small.

On Jul 4, 2024, at 11:59 AM, Generalized ***@***.***> wrote:

﻿

Thank you.
It also works when the parameter build_opts is removed, i.e. this work: remotes::install_github("rvlenth/emmeans")

And thank God I updated it, because I realized that the DFs are different from what I had previously working with imputed data. Now each row has different DF, which shows that the pooling is actually done through Rubin's rules. Now I have the chance to update all analyses before sending my work.

**Comment by Generalized** [comment] 2024-07-05 05:41
On the main page you wrote a way to install it from GitHub: `remotes::install_github("rvlenth/emmeans", dependencies = TRUE, build_opts = "")`

This fails. So either the building scripts should be corrected or this line should be updated.

The line without additional parameters: `remotes::install_github("rvlenth/emmeans")` works well.

What kind of reproducible example would be needed here?

**Comment by rvlenth** [comment] 2024-07-06 01:57
I get the same error. I changed the instructions to omit `build_opts` and add `build_vignettes = TRUE` with a note that this argument may be omitted. It will be in the next push.

**Closed by rvlenth** 2024-07-06 01:57 UTC
Labels: bug
