### ISSUE TITLE
Question: Is there a citation for the 'bias adjustment' used for the outcome scale predictions of a model with random effects

### ISSUE THREAD

**Issue by statsccpr** [rvlenth/emmeans#231] opened 2020-10-12 20:10 UTC
Hi thank you for the package and hard work, it seems flexible and helpful post model fitting.

I've been experimenting with the regrid methods. Looking at the bias adjusted incidence probabilities for the random effect logistic regression example.

https://cran.r-project.org/web/packages/emmeans/vignettes/sophisticated.html#mcmc

Will this 'marginalize/integrate out' the random effects, then return the incidence probabilities? 
Along the lines of
https://drizopoulos.github.io/GLMMadaptive/reference/marginal_coefs.html

"Hedeker et al. (2017) to calculate marginal coefficients from mixed models with nonlinear link functions"

Is it correct to say, using emmeans + regrid + bias adjustment + sd is similar to the marginal_coefs() of GLMMadaptive where the difference is emmeans uses the taylor approximation for the adjustment while glmm adaptive is using montecarlo integration

Is this the adjustment emmeans is using even for the random effects ('CBPP' example)? The vignette below uses the 'pigs' example, (no random effects)
https://cran.r-project.org/web/packages/emmeans/vignettes/transformations.html#bias-adj

I'm guessing this is the implementation talked about here

https://github.com/rvlenth/emmeans/issues/99#issuecomment-512948053
https://github.com/rvlenth/emmeans/blob/master/R/emmGrid-methods.R#L490

Thank you

**Comment by rvlenth** [comment] 2020-10-15 22:08
The answer to the first question is yes or no, depending on whether `GLMMadaptive::marginal_coefs` returns comparable results to those from stan_glmer (the `$stanfit` slot). 

It's important to understand that **emmeans** functions basically analyze the model -- not the data. They take whatever fixed effects are handed to it in the model, and whatever covariance matrix thereof. The bias adjustment is strictly interpreted in terms of trying to estimate E(Y) = E(h(Z)) where Y is the response, Z is the transformed response, and h is the inverse transformation.

The other thing to know is that bias adjustment should be done according to the actual random effects, as opposed to the model deviance. For example, the pigs illustration has a response transformation with random error and we use `sigma(model)` for adjusting bias. If we were to fit, say, a Poisson regression model using `glm` with `family = poisson`, we would *not* do any bias adjustment because the GLM is already framed in terms of the response mean. in a GLMM like that cbpp example, note that the bias adjustment is based on the variance of the random effects in the model, and nothing from the deviance of the GLM part of the model. 

So it is important to know when to use the bias adjustment, and what variances should and should not be used. But the code for actually doing the adjustment is the same second-order approximation. The adjustment is just a second-order Taylor approximation, h(Z) ~= h(mu) + h'(mu)(Z - mu) + 0.5 h''(mu)(Z - mu)^2, so that E[h(Z)] ~= h(mu) + 0 + 0.5 h''(mu)*Var(Z)

I am aware that there are other ways of doing this. Another place I have seen this done is in the **MCMCglmm** package, where they use an adjustment *before* back-transforming whereas I back-transform then adjust with that h'' term. 

I hope this helps clarify what is done.

**Comment by rvlenth** [comment] 2020-10-19 16:20
I am closing this issue; but you can still comment if you have further questions.

**Closed by rvlenth** 2020-10-19 16:20 UTC
Labels: question

**Comment by statsccpr** [comment] 2020-10-29 20:36
Yes thank you. Your response clears things up greatly.

This is more of an aside, but would you have any insight on using the taylor approximation for a glmm, where the covariance of the MVN random effect is something more complex than sigma^2*Identity ? Say, a covariance matrix with non 0 off diagonals (so the random effects are correlated)? So far, I think it's doable and would follow along the lines of your examples.

Using the pigs example, 
```
require(lme4)
cbpp <- transform(cbpp, unit = 1:nrow(cbpp))
cbpp.glmer <- glmer(cbind(incidence, size - incidence) ~ period + 
                          (1 | herd) +  (1 | unit),
                    family = binomial, data = cbpp)

total.SD = sqrt(0.89107^2 + 0.18396^2)
```

If instead, the distribution of the random intercepts for the 'unit' effects was MVN(0,Sigma)
Sigma = matrix(sd1,corr12,corr21,sd2)  where lets say there's only 2 unit levels for ease of example.

My thinking is we would additionally calculate the between group variance of the random unit random effects 'theta_unit' so that this extra term accounts for the correlation, corr12 and corr21.

extra_between_grp_var = Var(theta_unit[1], ... ,theta_unit[g]) 

to plug into

```
total.SD = sqrt(0.89107^2 + 0.18396^2 + extra_between_grp_var)
summary(emm, type = "response", bias.adjust = TRUE, sigma = total.SD)
```

Or is something more complex needed that involves theta's entire Var-Cov matrix, Sigma

**Comment by rvlenth** [comment] 2020-10-29 21:29
Yes, if two random effects are correlated, then for the total variance you need to add twice the covariance. In general, you need (in matrix form) SD_tot = **1' V 1** where **1** is a vector of all 1s and **V** is the covariance matrix.

**Comment by statsccpr** [comment] 2020-12-01 20:47
Hi Russel, following up on this last thought (although I'm in no rush to use it).

After sleeping on it and digging around I think there needs to be a small tweak on the emmeans interface to properly do this  (multivariate) taylor approximation for correlated random effects. 

Without further modification, I think using the current interface `regrid(..., bias.adjust = TRUE, sigma = totSD)`

is only valid for the simple random intercept glmms, where the random intercepts have the exchangeable covariance. MVN(0, constant * Identity_nxn)

I think for any other more exotic covariances, say in (as much as i don't like sas, they have pretty good docs)
https://support.sas.com/resources/papers/proceedings/proceedings/sugi30/198-30.pdf

we would need the multivariate taylor approx for the adjustment

https://stats.stackexchange.com/questions/401749/multivariate-taylor-series-for-moments-of-a-random-variable

The user (or maybe the emmeans package internally) would need to compute
**1/2Tr(f′′(E[λ])Var(λ))** and pass it into the internal calculations in your helper functions below

https://github.com/rvlenth/emmeans/blob/5b02798ad96c951a0fcef1faa58b1c762ed9e718/R/summary.R#L772

I think the current framework is only setup to handle if **1/2Tr(f′′(E[λ])Var(λ))** reduces to the simple scenario where you can just plug in a constant to sigma in `regrid(..., bias.adjust = TRUE, sigma = totSD)`

**Comment by rvlenth** [comment] 2020-12-01 20:59
You are correct in your assessment of the method currently used, but expanding it to support a multivariate Taylor approximation us not what I would call a "small tweak."

Sent from my iPhone

On Dec 1, 2020, at 2:47 PM, statsccpr <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Russel, following up on this last thought (although I'm in no rush to use it).

After sleeping on it and digging around I think there needs to be a small tweak on the emmeans interface to properly do this (multivariate) taylor approximation for correlated random effects.

Without further modification, I think using the current interface regrid(..., bias.adjust = TRUE, sigma = totSD)

is only valid for the simple random intercept glmms, where the random intercepts have the exchangeable covariance. MVN(0, constant * Identity_nxn)

I think for any other more exotic covariances, say in (as much as i don't like sas, they have pretty good docs)
https://support.sas.com/resources/papers/proceedings/proceedings/sugi30/198-30.pdf

we would need the multivariate taylor approx for the adjustment

https://stats.stackexchange.com/questions/401749/multivariate-taylor-series-for-moments-of-a-random-variable

The user (or maybe the emmeans package internally) would need to compute
1/2Tr(f′′(E[λ])Var(λ)) and pass it into the internal calculations in your helper functions below

https://github.com/rvlenth/emmeans/blob/5b02798ad96c951a0fcef1faa58b1c762ed9e718/R/summary.R#L772

I think the current framework is only setup to handle if 1/2Tr(f′′(E[λ])Var(λ)) reduces to the simple scenario where you can just plug in a constant to sigma in regrid(..., bias.adjust = TRUE, sigma = totSD)
