### ISSUE TITLE
non-conformable elements in reference grid

### ISSUE THREAD

**Issue by nlpaces** [rvlenth/emmeans#156] opened 2019-11-03 04:54 UTC
Estimating stan_lm models with log(outcome).

Previous version of emmeans ran without difficulty.

Since updating to 1.4.2, can't estimate any marginal means with
 error message: non-conformable elements in reference grid and further text suggesting rank deficient matrix

**Comment by rvlenth** [comment] 2019-11-03 12:38
Please provide a reproducible example.

Sent from my iPhone

On Nov 2, 2019, at 11:54 PM, nlpaces <notifications@github.com<mailto:notifications@github.com>> wrote:


Estimating stan_lm models with log(outcome).

Previous version of emmeans ran without difficulty.

Since updating to 1.4.2, can't estimate any marginal means with
error message: non-conformable elements in reference grid and further text suggesting rank deficient matrix

**Comment by nlpaces** [comment] 2019-11-03 17:15
What is needed? The model code? The data? The model object?
Thanks for responding quickly.

Sent from my iPhone

On Nov 3, 2019, at 05:38, Russell V. Lenth <notifications@github.com> wrote:

﻿Please provide a reproducible example.

Sent from my iPhone

On Nov 2, 2019, at 11:54 PM, nlpaces <notifications@github.com<mailto:notifications@github.com>> wrote:


Estimating stan_lm models with log(outcome).

Previous version of emmeans ran without difficulty.

Since updating to 1.4.2, can't estimate any marginal means with
error message: non-conformable elements in reference grid and further text suggesting rank deficient matrix

**Comment by rvlenth** [comment] 2019-11-03 18:00
Ideally, and example using an existing data set in an R package, e.g. **datasets**, the R code to fit the model, the R code used with **emmeans**, and the messages you see. 

If not an R package dataset, then maybe you can put it in Dropbox or somewhere and send the link, along with the above.

**Comment by rvlenth** [comment] 2019-11-03 19:11
Based on my revision notes, the change that might affect this came with version 1.41: 

> Added non-estimability infrastructure for Bayesian models, `stanreg` in particular (#114)"

So my guess is that for examples that "worked" previously, either ...
  1. the model was not rank-deficient; or
  2. the model was rank deficient, in which case the previous results you obtained could be incorrect.

**Comment by nlpaces** [comment] 2019-11-04 21:16
I appreciate this guidance.

I followed the links.

I used stan_lm to enforce some regularization of my models.

I double checked. No terms were removed in the model object.

However, about the time of the upgrade to emmeans I had changed a covariate to an ordered factor for three terms in my model.

The highest order term in those factors were close to zero.

I am rerunning my models using covariates rather ordered factors.

I’ll send messages about success or failure in calling emmeans.

Nathan

**Comment by nlpaces** [comment] 2019-11-05 06:18
After reverting to covariates, I can run emmeans without difficulty on my model.

Thanks again for your guidance.

Nathan

From: "Nathan Leon Pace, MD, MStat" <n.l.pace@utah.edu>
Date: Monday, November 4, 2019 at 14:16
To: rvlenth/emmeans <reply@reply.github.com>
Subject: Re: [rvlenth/emmeans] non-conformable elements in reference grid (#156)

I appreciate this guidance.

I followed the links.

I used stan_lm to enforce some regularization of my models.

I double checked. No terms were removed in the model object.

However, about the time of the upgrade to emmeans I had changed a covariate to an ordered factor for three terms in my model.

The highest order term in those factors were close to zero.

I am rerunning my models using covariates rather ordered factors.

I’ll send messages about success or failure in calling emmeans.

Nathan

**Comment by rvlenth** [comment] 2019-11-05 20:08
OK, I'm glad you got it to work. I did double-check a rank-deficient example: the `fit_aov` model in `example(stan_aov)` -- in which `block` is confounded with the 3-way interaction. It worked OK. Oddly, exactly the same model fitted with `stan_lm` does not detect any rank deficiency.
```r
> emmeans(fit_aov, ~block)
Error in as.mcmc.emmGrid(object, names = FALSE, sep.chains = FALSE, NE.include = TRUE,  : 
  Aborted -- No estimates in the grid are estimable

> emmeans(fit_lm, ~block)
 block    emmean lower.HPD upper.HPD
 1      1.52e+12 -1.14e+15  1.17e+15
 2     -1.52e+12 -1.17e+15  1.14e+15
 3     -1.52e+12 -1.17e+15  1.14e+15
 4     -1.52e+12 -1.17e+15  1.14e+15
 5      1.52e+12 -1.14e+15  1.17e+15
 6      1.52e+12 -1.14e+15  1.17e+15

Point estimate displayed: median 
HPD interval probability: 0.95 
```
Then I tried
```r
> fit_lm2 <- stan_lm(yield ~ block + N*P*K, data = npk, prior = R2(0.5), seed = 12345, singular.ok = FALSE)
> emmeans(fit_lm2, ~block)
Error in as.mcmc.emmGrid(object, names = FALSE, sep.chains = FALSE, NE.include = TRUE,  : 
  Aborted -- No estimates in the grid are estimable
```
**SO** The developers of **rstanarm** are confused and have `singular.ok` backwards! Or at least not having the same interpretation is for `lm`
```r
> stats_lm2 <- lm(yield ~ block + N*P*K, data = npk, singular.ok = FALSE)
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  singular fit encountered
```
I suggest you ALWAYS run `stan_lm` with `singular.ok = FALSE` so that it will delete predictors when there is singularity.

**Comment by rvlenth** [comment] 2020-01-28 03:12
(Non)progress report: I looked in on this, and see on this date that that there are 70 open issues on **rstanarm**'s bug-reports page, many since my posting this issue there in November -- https://github.com/stan-dev/rstanarm/issues/402. Moreover, currently almost all CRAN checks on that package report errors, with a few warnings and notes. So the **rstanarm** developers have their hands full, and I'm not anticipating they will get to this anytime soon. In the interim, I suggest you just run `stan_lm` with `singular.ok = FALSE` -- or use `stan_aov` -- which handles singularity correctly -- instead of `stan_lm`. 

I will close this issue now on this site, since the correct resolution of it is in **rstanarm**'s hands.

**Closed by rvlenth** 2020-01-28 03:12 UTC
