### ISSUE TITLE
Ignoring offsets when comparing factor levels

### ISSUE THREAD

**Issue by ndevln** [rvlenth/emmeans#179] opened 2020-03-24 17:20 UTC
Hi,

Firstly, thanks for this package.

I have a small question. I am using a model with an offset and I want to ignore this offset (by setting it 0, see below). When also specifying contrasts the offset option is ignored. Is this the expected behaviour? It does not seem to have any effect on the ratios, which is what I would expect.

Greetings
Alex

Example from [Models with offsets](https://cran.r-project.org/web/packages/emmeans/vignettes/sophisticated.html)
```
ins <- data.frame(
  n = c(500, 1200, 100, 400, 500, 300),
  size = factor(rep(1:3,2), labels = c("S","M","L")),
  age = factor(rep(1:2, each = 3)),
  claims = c(42, 37, 1, 101, 73, 14))
ins.glm <- glm(claims ~ size + age + offset(log(n)), 
               data = ins, family = "poisson")

emmeans(ins.glm, "size", type = "response", offset = 0)
```

```
 size   rate      SE  df asymp.LCL asymp.UCL
 S    0.1385 0.01250 Inf    0.1161    0.1653
 M    0.0693 0.00669 Inf    0.0573    0.0837
 L    0.0237 0.00627 Inf    0.0141    0.0398

Results are averaged over the levels of: age 
Confidence level used: 0.95 
Intervals are back-transformed from the log scale 
```

**Still uses offset:**

```
emmeans(ins.glm, list(pairwise ~ size), type = "response", offset = 0)
```

```
$`emmeans of size`
 size rate   SE  df asymp.LCL asymp.UCL
 S    69.3 6.25 Inf     58.03      82.7
 M    34.6 3.34 Inf     28.67      41.9
 L    11.9 3.14 Inf      7.07      19.9

Results are averaged over the levels of: age 
Confidence level used: 0.95 
Intervals are back-transformed from the log scale 

$`pairwise differences of size`
 contrast ratio    SE  df z.ratio p.value
 S / M     2.00 0.256 Inf 5.402   <.0001 
 S / L     5.84 1.590 Inf 6.478   <.0001 
 M / L     2.92 0.813 Inf 3.848   0.0003 

Results are averaged over the levels of: age 
P value adjustment: tukey method for comparing a family of 3 estimates 
Tests are performed on the log scale 
```

**Comment by rvlenth** [comment] 2020-03-25 02:42
Hmmmm, thanks for your report. I was able to reproduce your result. But it actually isn't due to the presence of a contrast. It is because `specs` is a `list`. If I just give the formula part, it works correctly:
```r
> emmeans(ins.glm, pairwise ~ size, type = "response", offset = 0)
$emmeans
 size   rate      SE  df asymp.LCL asymp.UCL
 S    0.1385 0.01250 Inf    0.1161    0.1653
 M    0.0693 0.00669 Inf    0.0573    0.0837
 L    0.0237 0.00627 Inf    0.0141    0.0398

Results are averaged over the levels of: age 
Confidence level used: 0.95 
Intervals are back-transformed from the log scale 

$contrasts
 contrast ratio    SE  df z.ratio p.value
 S / M     2.00 0.256 Inf 5.402   <.0001 
 S / L     5.84 1.590 Inf 6.478   <.0001 
 M / L     2.92 0.813 Inf 3.848   0.0003 

Results are averaged over the levels of: age 
P value adjustment: tukey method for comparing a family of 3 estimates 
Tests are performed on the log scale 
```
I looked at the code and notice that the offset argument is not passed when there is a list. I changed it so it is, and now it works as expected (you'll find it in the next update to github).

Thanks again for reporting this.

**Comment by rvlenth** [comment] 2020-05-11 16:47
Been a while, and I think this is resolved; so am closing this issue.

**Closed by rvlenth** 2020-05-11 16:47 UTC
Labels: bug
