### ISSUE TITLE
pairs() doesn't work when by = "a variable name with spaces in it"

### ISSUE THREAD

**Issue by cmrnp** [rvlenth/emmeans#305] opened 2021-11-02 07:07 UTC
While arguably bad form, R allows variable names in a model to include spaces and special characters. Mostly emmeans works with this just fine, but not when that variable is the "by" variable for pairwise comparisons. Instead the error message `Error in .find.by.rows(grid, by): 'by' variables are not all in the grid` is produced.

See example below:

``` r
library(emmeans)
#> Warning: package 'emmeans' was built under R version 4.0.5

data(mtcars)
mtcars2 <- data.frame(
  mpg = mtcars$mpg,
  cyl = factor(mtcars$cyl),
  "foo bar" = factor(mtcars$am),
  check.names = FALSE
)
m <- lm(mpg ~ cyl * `foo bar`, data = mtcars2)

# works
emmeans(m, "cyl", by = "foo bar")
#> foo bar = 0:
#>  cyl emmean    SE df lower.CL upper.CL
#>  4     22.9 1.751 26     19.3     26.5
#>  6     19.1 1.516 26     16.0     22.2
#>  8     15.1 0.875 26     13.3     16.8
#> 
#> foo bar = 1:
#>  cyl emmean    SE df lower.CL upper.CL
#>  4     28.1 1.072 26     25.9     30.3
#>  6     20.6 1.751 26     17.0     24.2
#>  8     15.4 2.144 26     11.0     19.8
#> 
#> Confidence level used: 0.95

# works
emmeans(m, "foo bar", by = "cyl")
#> cyl = 4:
#>  foo bar emmean    SE df lower.CL upper.CL
#>  0         22.9 1.751 26     19.3     26.5
#>  1         28.1 1.072 26     25.9     30.3
#> 
#> cyl = 6:
#>  foo bar emmean    SE df lower.CL upper.CL
#>  0         19.1 1.516 26     16.0     22.2
#>  1         20.6 1.751 26     17.0     24.2
#> 
#> cyl = 8:
#>  foo bar emmean    SE df lower.CL upper.CL
#>  0         15.1 0.875 26     13.3     16.8
#>  1         15.4 2.144 26     11.0     19.8
#> 
#> Confidence level used: 0.95

# doesn't work
pairs(emmeans(m, "cyl", by = "foo bar"))
#> Error in .find.by.rows(grid, by): 'by' variables are not all in the grid

# works
pairs(emmeans(m, "foo bar", by = "cyl"))
#> cyl = 4:
#>  contrast estimate   SE df t.ratio p.value
#>  0 - 1       -5.17 2.05 26  -2.521  0.0182
#> 
#> cyl = 6:
#>  contrast estimate   SE df t.ratio p.value
#>  0 - 1       -1.44 2.32 26  -0.623  0.5390
#> 
#> cyl = 8:
#>  contrast estimate   SE df t.ratio p.value
#>  0 - 1       -0.35 2.32 26  -0.151  0.8810
```

<sup>Created on 2021-11-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rvlenth** [comment] 2021-11-02 14:43
Hmmmm. Well, thanks for the report. 

For starters, this error occurs in *summarizing* the result:
```r
> emm12 = emmeans(m, "cyl", by = "foo bar")
> pairs(emm12)
 Error in .find.by.rows(grid, by) : 'by' variables are not all in the grid 

> pr = pairs(emm12)
> pr
 Error in .find.by.rows(grid, by) : 'by' variables are not all in the grid 
```
And the interesting thing is...
```r
> pr@grid
  contrast foo.bar
1    4 - 6       0
2    4 - 8       0
3    6 - 8       0
4    4 - 6       1
5    4 - 8       1
6    6 - 8       1
```
That is, the column name got changed to `foo.bar`. I evidently had a reason to change it this way, but I can't remember why. Knowing this, we can do
```r
> summary(pr, by = "foo.bar")
Note: adjust = "tukey" was changed to "sidak"
because "tukey" is only appropriate for one set of pairwise comparisons
foo.bar = 0:
 contrast estimate   SE df t.ratio p.value
 4 - 6        3.77 2.32 26   1.630  0.3072
 4 - 8        7.85 1.96 26   4.011  0.0014
 6 - 8        4.08 1.75 26   2.328  0.0816

foo.bar = 1:
 contrast estimate   SE df t.ratio p.value
 4 - 6        7.51 2.05 26   3.658  0.0034
 4 - 8       12.68 2.40 26   5.287  <.0001
 6 - 8        5.17 2.77 26   1.867  0.2041

P value adjustment: sidak method for 3 tests 
```
... and this reveals another issue that it doesn't realize that Tukey is legit here. I am able to confirm that that is just caused by the name discrepancy.

Not sure how quickly I can sort this out.

**Comment by cmrnp** [comment] 2021-11-03 01:25
Thanks for gettting back so quickly on this! This isn't an urgent issue from my perspective - a colleague hit this issue and couldn't figure out why it wasn't working and we eventually realised it was the space in the variable name, so figured it was worth reporting.

**Comment by rvlenth** [comment] 2021-11-03 01:52
OK, but it's worth tracking down. I still haven't found where that space gets replaced by a dot. Starting to think it's something in base R somewhere.

**Comment by rvlenth** [comment] 2021-11-03 15:48
Aha! I found out where it happens:
```r
> tmp = list(`foo bar` = 1:3)
> as.data.frame(tmp)
  foo.bar
1       1
2       2
3       3
```
This is something that base R did, not me -- which is a relief because it means I (*probably*) didn't have a specific purpose in removing spaces from names. And I can see a way to fix this:
```r
> as.data.frame(tmp, check.names = FALSE)
  foo bar
1       1
2       2
3       3
```
So if I make that one change three lines from the end of `contrast.emmGrid`, we fix the problem!
```r
> pairs(emm12)
foo bar = 0:
 contrast estimate   SE df t.ratio p.value
 4 - 6        3.77 2.32 26   1.630  0.2513
 4 - 8        7.85 1.96 26   4.011  0.0013
 6 - 8        4.08 1.75 26   2.328  0.0695

foo bar = 1:
 contrast estimate   SE df t.ratio p.value
 4 - 6        7.51 2.05 26   3.658  0.0031
 4 - 8       12.68 2.40 26   5.287  <.0001
 6 - 8        5.17 2.77 26   1.867  0.1686

P value adjustment: tukey method for comparing a family of 3 estimates 
```
Thanks again for reporting this.

**Comment by rvlenth** [comment] 2021-11-09 16:44
I'm going to close this issue, as I think we've got it nailed-down now. Thanks for bringing it to my attention.

**Closed by rvlenth** 2021-11-09 16:44 UTC
Labels: bug
