### ISSUE TITLE
error with 2 within-subjects factors and no between-subjects

### ISSUE THREAD

**Issue by TDJorgensen** [rvlenth/emmeans#6] opened 2017-11-23 19:58 UTC
Thank you for an excellent package. 

When I fit a multivariate intercepts-only model for a factorial within-subjects design, I get an error using the `mult.levs` argument.  Adapted from the `?ref_grid` help page:

```
MOats.lm = lm(yield ~ 1, data = MOats)
ref_grid(MOats.lm, mult.name = "nitro") # no problem with a single WS factor
ref_grid(MOats.lm, mult.levs = list(T=LETTERS[1:2], U=letters[1:2])) # error
```

The same error occurs in the latest `lsmeans::ref.grid`.  It does not occur when there is at least 1 between-subjects factor.

I installed archived versions, and it worked in version 2.26-3, but not 2.27-2

Thanks for your attention,
Terrence

**Comment by rvlenth** [comment] 2017-11-24 00:07
Thanks for reporting this.

Interestingly, I didn't get the first `ref_grid` to run right either; but then after fixing that, I got the error you report in the second `ref_grid`. The problem is in some code that tests to see if there are nested effects; and indeed, that feature wasn't added until **lsmeans** 2.27.

I have now fixed this:

```
> ref_grid(MOats.lm, mult.name = "nitro")
'emmGrid' object with variables:
    1 = 1
    nitro = multivariate response levels: 0, 0.2, 0.4, 0.6

> ref_grid(MOats.lm, mult.levs = list(T=LETTERS[1:2], U=letters[1:2]))
'emmGrid' object with variables:
    1 = 1
    T = multivariate response levels: A, B
    U = multivariate response levels: a, b
```

I'll be pushing the corrected version to github soon, and send an update to CRAN that will include this fix in a couple of weeks.

**Comment by TDJorgensen** [comment] 2017-11-24 09:29
Thanks for the quick response.  I thought this issue seemed familiar :-) 

Thank you also for your vignette on transitioning.  That should save me a lot of time updating my RMarkdown teaching materials.  I prefer the term "expected marginal means" too -- it makes more sense across more contexts.

**Comment by rvlenth** [comment] 2017-11-29 22:28
I think this is resolved, so am closing this issue. Thanks.

**Closed by rvlenth** 2017-11-29 22:28 UTC
