### ISSUE TITLE
inflated dfs in emmeans output

### ISSUE THREAD

**Issue by Mengxia-Fu** [rvlenth/emmeans#46] opened 2018-08-03 02:28 UTC
Hi Russ,

I have run the same model (mod1) with both lsmeans and emmeans for pairwise comparisons. I noticed that the output from emmeans involved some inflated df values which were not found in the lsmeans output. The inflated dfs reduced the number of statistically significant group contrasts. The output from lsmeans and emmeans is listed below. Could you please let me know whether the inflated dfs are resulted from the incorrect models I built or the inaccurate calculations of emmeans? Thanks in advance!  

> mod1<-lmer(GJTscore~GJTpre+Time+Group+Time*Group+(1|Class/Subject),data=GJT, REML = F)
> lsmeans(mod1,list(pairwise~Group|Time),adjust="bonferroni")

$`pairwise differences of contrast, Time | Time`
Time = 2:
 contrast   estimate       SE     df t.ratio p.value
 4 - 1    -3.7713780 1.211024 216.96  -3.114  0.0126
 4 - 2    -3.0443478 1.183329 216.71  -2.573  0.0646
 4 - 3    -2.6995979 1.262705 215.33  -2.138  0.2019
 1 - 2     0.7270302 1.111591 217.16   0.654  1.0000
 1 - 3     1.0717801 1.179184 217.87   0.909  1.0000
 2 - 3     0.3447499 1.153255 217.89   0.299  1.0000

Time = 4:
 contrast   estimate       SE     df t.ratio p.value
 4 - 1    -5.8488587 1.204532 212.95  -4.856  <.0001
 4 - 2    -3.7107185 1.184252 217.30  -3.133  0.0118
 4 - 3    -4.4727699 1.256006 211.36  -3.561  0.0027
 1 - 2     2.1381402 1.113608 218.52   1.920  0.3370
 1 - 3     1.3760888 1.173556 214.28   1.173  1.0000
 2 - 3    -0.7620513 1.154011 218.37  -0.660  1.0000

Time = 6:
 contrast   estimate       SE     df t.ratio p.value
 4 - 1    -5.4159758 1.204532 212.95  -4.496  0.0001
 4 - 2    -3.2493890 1.179468 214.27  -2.755  0.0382
 4 - 3    -3.8862978 1.252647 209.45  -3.102  0.0131
 1 - 2     2.1665868 1.108840 215.30   1.954  0.3120
 1 - 3     1.5296780 1.170054 212.13   1.307  1.0000
 2 - 3    -0.6369087 1.146254 213.39  -0.556  1.0000

Time = 8:
 contrast   estimate       SE     df t.ratio p.value
 4 - 1    -5.2912010 1.204532 212.95  -4.393  0.0001
 4 - 2    -2.4249866 1.177488 213.02  -2.059  0.2440
 4 - 3    -3.9278571 1.273459 221.66  -3.084  0.0138
 1 - 2     2.8662144 1.106607 213.79   2.590  0.0615
 1 - 3     1.3633440 1.192269 226.20   1.143  1.0000
 2 - 3    -1.5028704 1.166641 226.61  -1.288  1.0000

P value adjustment: bonferroni method for 6 tests 

> emmeans(mod1,list(pairwise~Group|Time),adjust="bonferroni")
$`emmeans of Group | Time`

$`pairwise differences of Group | Time`
Time = 2:
 contrast   estimate       SE     df t.ratio p.value
 4 - 1    -3.7713780 1.420087   6.14  -2.656  0.2213
 4 - 2    -3.0443478 1.395626   6.13  -2.181  0.4258
 4 - 3    -2.6995979 1.467241 100.85  -1.840  0.4123
 1 - 2     0.7270302 1.351757   2.79   0.538  1.0000
 1 - 3     1.0717801 1.394396   5.57   0.769  1.0000
 2 - 3     0.3447499 1.371838   5.58   0.251  1.0000

Time = 4:
 contrast   estimate       SE     df t.ratio p.value
 4 - 1    -5.8488587 1.415019   6.01  -4.133  0.0367
 4 - 2    -3.7107185 1.397154   6.14  -2.656  0.2215
 4 - 3    -4.4727699 1.466036  95.44  -3.051  0.0177
 1 - 2     2.1381402 1.353467   2.81   1.580  1.0000
 1 - 3     1.3760888 1.392144   5.44   0.988  1.0000
 2 - 3    -0.7620513 1.375174   5.56  -0.554  1.0000

Time = 6:
 contrast   estimate       SE     df t.ratio p.value
 4 - 1    -5.4159758 1.415019   6.01  -3.827  0.0520
 4 - 2    -3.2493890 1.392929   6.04  -2.333  0.3488
 4 - 3    -3.8862978 1.461934  95.30  -2.658  0.0553
 1 - 2     2.1665868 1.349424   2.77   1.606  1.0000
 1 - 3     1.5296780 1.388054   5.38   1.102  1.0000
 2 - 3    -0.6369087 1.367408   5.43  -0.466  1.0000

Time = 8:
 contrast   estimate       SE     df t.ratio p.value
 4 - 1    -5.2912010 1.415019   6.01  -3.739  0.0577
 4 - 2    -2.4249866 1.391218   6.00  -1.743  0.7917
 4 - 3    -3.9278571 1.482142 100.09  -2.650  0.0561
 1 - 2     2.8662144 1.347532   2.74   2.127  0.7904
 1 - 3     1.3633440 1.408233   5.79   0.968  1.0000
 2 - 3    -1.5028704 1.385909   5.81  -1.084  1.0000

P value adjustment: bonferroni method for 6 tests 

Best regards,

Mengxia

**Comment by rvlenth** [comment] 2018-08-03 17:10
Hmmm, I agree that the d.f. differ drastically. Many of the d.f. are VERY low. But in addition, the standard errors from `emmeans` are also substantially larger, and in many cases that has a bigger impact than the d.f.

Between **lsmeans** and **emmeans**, the default d.f. method changed from Satterthwaite to Kenward-Roger. The K-R method implements a bias correction to the covariance matrix in addition to the d.f. calculation, and I guess that is what is responsible for the changes in the SEs. With such a severe change in these estimates, you must have a very seriously unbalanced or ill-conditioned situation. Your model is garbled, but I think you may be on the fringes of being able to estimate the effects. So my first sugegstion is to try a simpler model (say, remove the Subject:Class grouping) and see if the df in `emmeans` go up substantially. 

You may be able to reproduce the old `lsmeans` results by adding `mode = "satterth"` to the `emmeans()` call. But I trust the K-R results most of the time, and I think the fact that they are flaky indicates that there's an over-fitting issue at hand.

**Comment by rvlenth** [comment] 2018-08-03 17:14
I also wonder why you fit the model with `REML=FALSE`. Is it because it choked with `REML=TRUE`? REML estimation has a lot to do with aligning the fixed effects, so if it doesn't work, that'd suggest there's a real problem with estimating the fixed effects, and that certainly would explain what's happening here.

**Comment by Mengxia-Fu** [comment] 2018-08-04 05:27
Hi Russell,

Thank you very much for your quick reply.

I have tried both ML and REML model fit methods in lsmeans and emmeans. When I use lsmeans for pairwise comparisons, the dfs are very low with the REML model but go up substantially with the ML model. For emmeans output, dfs are always flaky despite the method of model fit.  

I think that you are right that the model is over fitted given that the emmeans output turns to be normal when I drop one random variable (class). I am just a bit confused that why the dfs of lsmeans are not influenced by the issue of over-fitting when the garbled model is fit with ML. Could you please give me some suggestions? Thanks in advance!

Best regards,

Mengxia

**Comment by rvlenth** [comment] 2018-09-22 01:09
I think this issue is resolved, so I am closing it.

**Closed by rvlenth** 2018-09-22 01:09 UTC
Labels: question
