### ISSUE TITLE
Problem with "gee" models since last emmeans update?

### ISSUE THREAD

**Issue by strengejacke** [rvlenth/emmeans#249] opened 2020-12-11 08:52 UTC
Hi Russ,
the following used to work with _emmeans 1.5.2-1_:

``` r
library(gee)
library(emmeans)
data(warpbreaks)
m1 <- suppressMessages(gee(breaks ~ tension, id = wool, data = warpbreaks, silent = TRUE))
#> (Intercept)    tensionM    tensionH 
#>    36.38889   -10.00000   -14.72222

# emmeans 1.5.2-1
emmeans::emmeans(m1, "tension")
#>  tension emmean   SE  df asymp.LCL asymp.UCL
#>  L         36.4 5.77 Inf      25.1      47.7
#>  M         26.4 1.69 Inf      23.1      29.7
#>  H         21.7 2.04 Inf      17.7      25.7
#> 
#> Covariance estimate used: robust.variance 
#> Confidence level used: 0.95
```

however, it now fails with _emmeans 1.5.3_:

``` r
library(gee)
library(emmeans)
data(warpbreaks)
m1 <- suppressMessages(gee(breaks ~ tension, id = wool, data = warpbreaks, silent = TRUE))
#> (Intercept)    tensionM    tensionH 
#>    36.38889   -10.00000   -14.72222

# emmeans 1.5.3
emmeans::emmeans(m1, "tension")
#> Error in tbl[, vars, drop = FALSE] : incorrect number of dimensions
#> Error in (function (object, at, cov.reduce = mean, cov.keep = get_emm_option("cov.keep"), : Perhaps a 'data' or 'params' argument is needed
```

I don't think this was intentional?

**Comment by rvlenth** [comment] 2020-12-11 13:32
Not intentional, indeed.I hope it at least works if you supply data = warpbreaks. I'll look at it. I know what change caused this, but don't understand how it could.

Sent from my iPad

On Dec 11, 2020, at 2:52 AM, Daniel <notifications@github.com> wrote:

﻿

Hi Russ,
the following used to work with emmeans 1.5.2-1:

library(gee)
library(emmeans)
data(warpbreaks)
m1 <- suppressMessages(gee(breaks ~ tension, id = wool, data = warpbreaks, silent = TRUE))
#> (Intercept)    tensionM    tensionH
#>    36.38889   -10.00000   -14.72222

# emmeans 1.5.2-1
emmeans::emmeans(m1, "tension")
#>  tension emmean   SE  df asymp.LCL asymp.UCL
#>  L         36.4 5.77 Inf      25.1      47.7
#>  M         26.4 1.69 Inf      23.1      29.7
#>  H         21.7 2.04 Inf      17.7      25.7
#>
#> Covariance estimate used: robust.variance
#> Confidence level used: 0.95

however, it now fails with emmeans 1.5.3:

library(gee)
library(emmeans)
data(warpbreaks)
m1 <- suppressMessages(gee(breaks ~ tension, id = wool, data = warpbreaks, silent = TRUE))
#> (Intercept)    tensionM    tensionH
#>    36.38889   -10.00000   -14.72222

# emmeans 1.5.3
emmeans::emmeans(m1, "tension")
#> Error in tbl[, vars, drop = FALSE] : incorrect number of dimensions
#> Error in (function (object, at, cov.reduce = mean, cov.keep = get_emm_option("cov.keep"), : Perhaps a 'data' or 'params' argument is needed

I don't think this was intentional?

**Comment by strengejacke** [comment] 2020-12-11 13:36
Yes, that works:

``` r
library(gee)
library(emmeans)
data(warpbreaks)
m1 <- suppressMessages(gee(breaks ~ tension, id = wool, data = warpbreaks, silent = TRUE))
#> (Intercept)    tensionM    tensionH 
#>    36.38889   -10.00000   -14.72222

# emmeans 1.5.3
emmeans::emmeans(m1, "tension", data = warpbreaks)
#>  tension emmean   SE  df asymp.LCL asymp.UCL
#>  L         36.4 5.77 Inf      25.1      47.7
#>  M         26.4 1.69 Inf      23.1      29.7
#>  H         21.7 2.04 Inf      17.7      25.7
#> 
#> Covariance estimate used: robust.variance 
#> Confidence level used: 0.95
```

<sup>Created on 2020-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I realized this issue because your recent update to CRAN caused failing checks in on of my packages: https://cran.r-project.org/web/checks/check_results_ggeffects.html

Are you planning to submit a fixed version to CRAN any time soon? If not / if you currently don't have the time to address this, let me know, then I'll disable the related test and submit an update of my package.

**Comment by rvlenth** [comment] 2020-12-11 13:40
It kind of depends on what exactly goes wrong, and how pervasive the issue is likely to be.(And also on whether I can fix it, of course). I won't be able to get to this until this afternoon (Fri Dec 11).

Sent from my iPad

On Dec 11, 2020, at 7:36 AM, Daniel <notifications@github.com> wrote:

﻿

Yes, that works:

library(gee)
library(emmeans)
data(warpbreaks)
m1 <- suppressMessages(gee(breaks ~ tension, id = wool, data = warpbreaks, silent = TRUE))
#> (Intercept)    tensionM    tensionH
#>    36.38889   -10.00000   -14.72222

# emmeans 1.5.3
emmeans::emmeans(m1, "tension", data = warpbreaks)
#>  tension emmean   SE  df asymp.LCL asymp.UCL
#>  L         36.4 5.77 Inf      25.1      47.7
#>  M         26.4 1.69 Inf      23.1      29.7
#>  H         21.7 2.04 Inf      17.7      25.7
#>
#> Covariance estimate used: robust.variance
#> Confidence level used: 0.95

Created on 2020-12-11 by the reprex package<https://reprex.tidyverse.org> (v0.3.0)

I realized this issue because your recent update to CRAN caused failing checks in on of my packages: https://cran.r-project.org/web/checks/check_results_ggeffects.html

Are you planning to submit a fixed version to CRAN any time soon? If not / if you currently don't have the time to address this, let me know, then I'll disable the related test and submit an update of my package.

**Comment by strengejacke** [comment] 2020-12-11 13:54
It's not that urgent, the CRAN team asked me for a revised version until 6th Jan 21. If you are able to submit before that date, I don't need to take any action, else I would submit an update with disabling the failing test.

**Comment by rvlenth** [comment] 2020-12-11 16:34
Well, at least I know what's wrong. The GEE support uses the `lm` method for recovering the data, and I added to `recover_data.lm` to use the `$model` component when it can, as it contains the model frame. 

However, a `gee` object has a `model` component that is entirely something else:
```r
> m1$model
$link
[1] "Identity"

$varfun
[1] "Gaussian"

$corstr
[1] "Independent"
```

So the fix is to modify `recover_data.gee`. But I need to see if there are other cases like this as well, e.g., `geese`, ...

**Comment by rvlenth** [comment] 2020-12-11 21:29
OK, I have figured out a fix for this.
```r
> emmeans(m1, "tension")
 tension emmean   SE  df asymp.LCL asymp.UCL
 L         36.4 5.77 Inf      25.1      47.7
 M         26.4 1.69 Inf      23.1      29.7
 H         21.7 2.04 Inf      17.7      25.7

Covariance estimate used: robust.variance 
Confidence level used: 0.95
```
However, 

  * this is not an issue that is pervasive for a lot of different model classes
  * there is a simple workaround (specifying `data`)

So... I don't think this warrants an emergency update. Are you still willing to disable the affected tests until after my next update?

**Comment by rvlenth** [comment] 2020-12-11 21:36
PS let's DO leave this open so other users may find it easier to notice it's a known issue and there's a workaround.

**Comment by strengejacke** [comment] 2020-12-11 22:25
> Are you still willing to disable the affected tests until after my next update?

Yes, that's no problem! Thanks for fixing, I'll watch for the next emmeans update.

**Comment by rvlenth** [comment] 2021-02-04 03:22
OK. Version 1.5.4 is now on CRAN, so this issue goes away if people update to that version.

**Comment by strengejacke** [comment] 2021-02-04 06:56
Thanks!

**Comment by rvlenth** [comment] 2021-03-06 22:13
I think I can go ahead and close this issue now.

**Closed by rvlenth** 2021-03-06 22:13 UTC
