### ISSUE TITLE
Using contrasts to conduct F-tests in an augmented factorial treatment structure

### ISSUE THREAD

**Issue by SimonShamusRiley** [rvlenth/emmeans#399] opened 2023-02-03 20:11 UTC
It is common in agronomy and related fields to have experiments with a complete factorial of, say, 2 fertilizer sources and 3 fertilization rates, plus a control, for which source is "none" and rate is "none". nlme::lme() doesn't like models with missing treatment combinations, so what I would like to do is create a single "treatment" variable, fit the model, and then reconstruct the correct F-tests for the main effects and interactions using contrasts. I have tried and failed to figure out a solution using the available add_grouping() or split_fac() functions (I sincerely apologize if I'm just being dense and there is an obvious solution here). Below is an approach which I think should be valid, but I'm not certain and wanted to see if this is reasonable or, alternatively, if there is an established way to do this that I've missed somehow.

Load libraries
```
library(dplyr)
library(nlme)
library(emmeans)
```

Create hypothetical experimental design

```
dat = expand.grid(Block = 1:4,
                  Source = c('Control', 'Urea', 'Manure'), 
                  Rate   = c('None', 'Low', 'Med', 'High')) %>% 
  filter(!((Source == "Control" & Rate != 'None') |
             (Source != 'Control' & Rate == 'None')))

table(dat$Rate, dat$Source) # Augmented factorial treatment structure
```
Create "Trt" column, as well as some fake response values
```
dat = dat %>% 
  mutate(Trt = interaction(Source, Rate, sep = '-'), 
         Y = rnorm(nrow(dat)))
```

lme breaks if I include crossed terms with missing treatment combinations. Error in MEEM, singularity in backsolve, etc:

```
# This does not work...
notfit = lme(Y ~ Source*Rate, data = dat, random = ~1|Block)

# Using the combined "Trt" column works...
fit = lme(Y ~ Trt, data = dat, random = ~1|Block)

# ... but omnibus test is of course not very informative
joint_tests(fit) 
```
How can I perform F test to see if main effects and interaction of rate and source are significant? Following the basic framework used by joint_tests, I construct "eff.emmc"-like contrasts for each term,  and then perform a test on those with joint = TRUE

```
rg = ref_grid(fit)
rg

# There are k=3 sources: control, manure and urea. The weights would thus be 
# (k-1)/k = 2/3,  -1/k = -1/3, and -1/k = -1/3, except that each of these weights needs to be further 
# divided by the number of levels of rate in that source, I think. 
source_me_contr = list('Control'  = c( 2/3, -1/9, -1/9, -1/9, -1/9, -1/9, -1/9),
                                      'Urea'     = c(-1/3,  2/9, -1/9,  2/9, -1/9,  2/9, -1/9),
                                      'Manure'   = c(-1/3, -1/9,  2/9, -1/9,  2/9, -1/9,  2/9))

test(contrast(emmeans(rg, ~ Trt), source_me_contr), joint = T)
```
Is this valid? Meaningful? Can the interaction contrasts be enumerated by simply taking the products of all combinations of the main effects contrasts? Thanks for your time and patience, and I really do apologize if I've missed something obvious or if this isn't the appropriate forum for such a question.

**Comment by rvlenth** [comment] 2023-02-04 16:14
I prefer to handle cases like this via imposing an appropriate factor structure. Below I make your example reproducible by setting a seed, and also added some real effects just so we're not estimating zero effects everywhere. To get the needed factor structure, I added a factor that accounts for whether the plot is treated or not.
```
> set.seed(2023.0204)
> dat$Y = rnorm(28) + rep(c(10, 12, 11, 15, 19, 20, 22), each = 4) + rep(c(1, 2, 5, -8), 7)
> dat = transform(dat, Treated = factor(Rate != "None"))
```
Now let's try fitting a model
```
> nested = lme(Y ~ Treated + Source*Rate, data = dat, random = ~1|Block)
Error in MEEM(object, conLin, control$niterEM) : 
  Singularity in backsolve at level 0, block 1
```
An irritating feature of `lme` is that it can't handle rank deficiency. So instead I'll turn to `lmer` in the **lme4** package
```
> nested = lme4::lmer(Y ~ Treated + Source*Rate + (1|Block), data = dat)
fixed-effect model matrix is rank deficient so dropping 6 columns / coefficients
```
Let's get the means
```
> (EMM = emmeans(nested, ~Source*Rate|Treated))
NOTE: A nesting structure was detected in the fitted model:
    Source %in% Treated, Rate %in% Treated
Treated = FALSE:
 Source  Rate emmean   SE   df lower.CL upper.CL
 Control None   9.22 2.73 3.09    0.659     17.8

Treated = TRUE:
 Source  Rate emmean   SE   df lower.CL upper.CL
 Urea    Low   12.14 2.73 3.09    3.577     20.7
 Manure  Low   10.76 2.73 3.09    2.203     19.3
 Urea    Med   15.33 2.73 3.09    6.771     23.9
 Manure  Med   19.63 2.73 3.09   11.070     28.2
 Urea    High  20.19 2.73 3.09   11.630     28.7
 Manure  High  21.05 2.73 3.09   12.495     29.6

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 
```
To get the joint tests I thought I could just do it:
```
> joint_tests(EMM)
 model term     df1 df2 F.ratio p.value note
 Treated          1  18 351.659  <.0001     
 Source:Treated   1  18  18.432  0.0004    e
 Rate:Treated     2  18 334.701  <.0001    e
 (confounded)     2  18  31.447  <.0001     

e: df1 reduced due to non-estimability 
> joint_tests(EMM, by = "Treated")
Treated = TRUE:
 model term   df1 df2 F.ratio p.value
 (confounded)   5  18      NA      NA
```
This doesn't separate things out correctly, but we can do it manually:
```
> test(contrast(emmeans(EMM, ~Source|Treated), "consec"), joint = TRUE)
 Treated df1 df2 F.ratio p.value note
 FALSE     0  NA      NA      NA  d e
 TRUE      1  18  18.432  0.0004     

d: df1 reduced due to linear dependence 
e: df1 reduced due to non-estimability 

> test(contrast(emmeans(EMM, ~Rate|Treated), "consec"), joint = TRUE)
 Treated df1 df2 F.ratio p.value note
 FALSE     0  NA      NA      NA  d e
 TRUE      2  18 334.701  <.0001     

d: df1 reduced due to linear dependence 
e: df1 reduced due to non-estimability 

> test(contrast(EMM, interaction = "consec"), joint = TRUE)
 Treated df1 df2 F.ratio p.value note
 FALSE     0  NA      NA      NA  d e
 TRUE      2  18  31.446  <.0001     

d: df1 reduced due to linear dependence 
e: df1 reduced due to non-estimability 
```
I'm pretty sure these are the "right answers" in terms of testing these effects *within* the non-control conditions. And, interestingly, they do correspond to the original `joint_tests()` output.

Let's try what you do. I'm going to use `lmer` instead of `lme` so we don't have degrees-of-freedom discrepancies.
```
> rg = ref_grid(trtmod)
> source_me_contr = list('Control'  = c( 2/3, -1/9, -1/9, -1/9, -1/9, -1/9, -1/9),
+                        'Urea'     = c(-1/3,  2/9, -1/9,  2/9, -1/9,  2/9, -1/9),
+                        'Manure'   = c(-1/3, -1/9,  2/9, -1/9,  2/9, -1/9,  2/9))
> test(contrast(rg, source_me_contr), joint = TRUE)
 df1 df2 F.ratio p.value note
   2  18 185.046  <.0001  d  

d: df1 reduced due to linear dependence 
```
(You get only 2 d.f., because of linear dependence: your 2nd and 3rd contrasts sum to the negative of the 1st one.) This does not match any of my results, but of course it shouldn't, because your contrasts *include* my `Treated` effect, whereas mine create *F* tests for the 2 x 3 part of the experiment that excludes the control. Both are valid in their own way, depending on your goals. BTW, my test of source is obtainable via
```
> my_source_contr = list('Urea vs. Manure' = c(0, 1, -1, 1, -1, 1, -1))
> test(contrast(rg, my_source_contr), joint = TRUE)
 df1 df2 F.ratio p.value
   1  18  18.432  0.0004
```

It's fine to do joint tests of specified sets of contrasts as you do, so long as those are the contrasts that interest you. BTW, it does *not* matter whether you divide by 9, or 3, or whatever.

**Comment by SimonShamusRiley** [comment] 2023-02-06 21:47
Thank you so much, that is extremely helpful.

**Comment by rvlenth** [comment] 2023-02-11 18:05
I think this is resolved, so am closing.

**Closed by rvlenth** 2023-02-11 18:05 UTC
Labels: question
