### ISSUE TITLE
Conflict when using vcov. and adjust options together

### ISSUE THREAD

**Issue by jwilliman** [rvlenth/emmeans#283] opened 2021-07-08 05:33 UTC
Awesome package. 

I noticed what appears to be a bug when passing a function to the `vcov.` command and simultaneously changing the default `adjust` option. This doesn't occur when the model vcov is passed instead of the function.

Thanks :)

``` r

library(emmeans)

fiber.lm <- lm(strength ~ machine*diameter, data = fiber)

emmeans(
  fiber.lm, pairwise ~ machine, vcov. = sandwich::vcovHAC(fiber.lm),
  adjust = 'none')
#> NOTE: Results may be misleading due to involvement in interactions
#> $emmeans
#>  machine emmean    SE df lower.CL upper.CL
#>  A         40.2 0.359  9     39.4     41.0
#>  B         41.6 0.642  9     40.1     43.1
#>  C         38.5 0.996  9     36.3     40.8
#> 
#> Confidence level used: 0.95 
#> 
#> $contrasts
#>  contrast estimate    SE df t.ratio p.value
#>  A - B       -1.38 0.728  9 -1.892  0.0910 
#>  A - C        1.69 1.058  9  1.595  0.1452 
#>  B - C        3.07 1.189  9  2.577  0.0298

emmeans(fiber.lm, pairwise ~ machine, vcov. = sandwich::vcovHAC)
#> NOTE: Results may be misleading due to involvement in interactions
#> $emmeans
#>  machine emmean    SE df lower.CL upper.CL
#>  A         40.2 0.359  9     39.4     41.0
#>  B         41.6 0.642  9     40.1     43.1
#>  C         38.5 0.996  9     36.3     40.8
#> 
#> Confidence level used: 0.95 
#> 
#> $contrasts
#>  contrast estimate    SE df t.ratio p.value
#>  A - B       -1.38 0.728  9 -1.892  0.1963 
#>  A - C        1.69 1.058  9  1.595  0.2965 
#>  B - C        3.07 1.189  9  2.577  0.0699 
#> 
#> P value adjustment: tukey method for comparing a family of 3 estimates

emmeans(
  fiber.lm, pairwise ~ machine, vcov. = sandwich::vcovHAC,
  adjust = 'none')
#> Error in if (adjust) utu <- n.orig/(n.orig - k) * utu: argument is not interpretable as logical
```

<sup>Created on 2021-07-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rvlenth** [comment] 2021-07-08 15:21
Thanks for the report. This error has to do somehow with the two-sided formula, which has been a thorn in my side for a long time because it is ambiguous which arguments should apply to the `emmeans` part (the RHS) and which to the `contrast` part (the LHS). If I had never provided the 2-sided formula, it would avoid the problem:
```r
> EMM <- emmeans(fiber.lm, ~ machine, vcov. = sandwich::vcovHAC)
NOTE: Results may be misleading due to involvement in interactions

> pairs(EMM, adjust = "none")
 contrast estimate    SE df t.ratio p.value
 A - B       -1.38 0.728  9  -1.892  0.0910
 A - C        1.69 1.058  9   1.595  0.1452
 B - C        3.07 1.189  9   2.577  0.0298
```

I will attempt to fix it. I just yesterday sent an update to CRAN, so unfortunately, it will be a while before the fixed version reaches CRAN.

**Comment by rvlenth** [comment] 2021-07-08 15:35
Hmmmm, I now see what the issue is. From the help page for `sandwich::vcovHAC`:
```
Usage
vcovHAC(x, ...)

## Default S3 method:
vcovHAC(x, order.by = NULL, prewhite = FALSE, weights = weightsAndrews,
  adjust = TRUE, diagnostics = FALSE, sandwich = TRUE, ar.method = "ols",
  data = list(), ...)
```
Note that this function has an `adjust` argument, and in your example, we have passed it a character string, which is inappropriate. We need to respect the arguments of external functions, because it could be we wanted:
```r
> EMM <- emmeans(fiber.lm, ~ machine, vcov. = sandwich::vcovHAC, adjust = FALSE)
NOTE: Results may be misleading due to involvement in interactions

> pairs(EMM, adjust = "none")
 contrast estimate    SE df t.ratio p.value
 A - B       -1.38 0.564  9  -2.443  0.0372
 A - C        1.69 0.819  9   2.059  0.0696
 B - C        3.07 0.921  9   3.327  0.0088
```
So (*whew!*) this isn't a bug after all, but rather an argument conflict with a function in another package. And it is only coincidentally related to the two-sided formula, in that the way to work around it requires us to *not* use a two-sided formula (or to call the function explicitly as you did in the beginning).

**Comment by rvlenth** [comment] 2021-07-08 15:41
PS - note there is also a `weights` argument to `vcovHAC()` which is also an optional argument for `emmeans()`. For that one, we would definitely need to do an explicit call to `vcovHAC(fiber.lm, weights = ...)` whether it is a one- or two-sided formula.

Thanks again for the report; it's an interesting issue, and I am considering adding a cautionary note in the help files.

**Comment by jwilliman** [comment] 2021-07-09 04:52
Brilliant. Thanks very much for looking into this Russell. I'll remember not to use the word 'bug' so hastily in future!

**Comment by rvlenth** [comment] 2021-07-16 20:12
I think this is resolved, or at least answered. So will close this issue. But it is still possible to comment if any concerns arise.

**Closed by rvlenth** 2021-07-16 20:12 UTC
Labels: question
