### ISSUE TITLE
Ideas for extending emmeans to work with output from mice (multiple imputation)

### ISSUE THREAD

**Issue by ablack3** [rvlenth/emmeans#80] opened 2019-01-22 20:42 UTC
I'm looking for thoughts on how to extend emmeans to work with models fit using multiple imputation with the mice package. When using mice I end up with three objects:

- mids - contains the original data as well as imputed datasets
- mira - contains the call and the fitted model object for each one of the imputations
- mipo - contains the pooled regression coefficients and standard errors

From https://cran.r-project.org/web/packages/emmeans/vignettes/xtending.html I see that I need to implement two methods: `recover_data` and `emm_basis`. For those a little more experienced with this than I am my question is "Does this seem relatively straightforward or does extending emmeans to work with mids/mira/mipo objects seem like a difficult or impossible task?" The first think I noticed was that the data, call, and fitted coefficients are in separate objects so that seems to make things difficult.

Maybe the appropriate approach is to compute the emmeans on each imputed dataset and then pool the results instead of computing the emmeans using the pooled coefficient estimates.

**Comment by rvlenth** [comment] 2019-01-22 23:14
My intuition is that it all depends on whether you can recover some kind of variance-covariance matrix for the pooled regression coefficients. That appears to be related to the method for getting the SEs of them, which you say is possible from the `mipo` object. I think trying to combine the `emmGrid` objects from the separate models would be somewhat harder, because you'd still have to figure out how to pool the covariances and account for the variations among imputations. I have not read much on MI methods (have always meant to learn more...) so don't have a lot of familiarity on how that's done.

One way to try to "breadboard" a solution would be the `qdrg()` function (quick and dirty reference grid). You don't need to write those methods to use that, you just need to assemble the needed pieces. If you can get that to work, then it'd provide a pretty good idea of how to write an `emm_basis` method. As for the fact that there are three objects, a brute-force method would be to assemble all of them in a list or an environment, and give it a `class` attribute. I suspect the `recover_data` part would be pretty easy.

**Comment by ablack3** [comment] 2019-01-23 17:22
Thanks for the response @rvlenth. I can get the variance estimates of the regression coefficients from the `mipo` object (This is just the square of the standard errors assuming I'm interpreting things correctly). However I don't think I can get any estimate of covariance between regression coefficient estimates. Do most other model objects in R give you the covariance of the regression coefficient estimates? 

I guess one big question is whether I should pool the analysis results from the imputations first and then calculate emmeans using the pooled coefficients on the original dataset or calculate the emmeans on each imputed dataset and then pool the results. I'm currently taking the latter approach and it does not seem too difficult but is a somewhat manual process. If we take the former approach and extend emmeans to work with the output of mice then it does seem like there will need to be a new model object containing the mids, mira, and mipo objects so that everything is in one list like you suggest.

**Comment by rvlenth** [comment] 2019-01-24 01:54
Offhand, I'd have thought that the first approach would be better. *However*, almost simultaneously, I received a question about adding support for model averaging (package **MuMIn**). Interesting, because the common element is that one has a set of several models for the same data, and the results need to be combined in some way. I wonder if the methods for combining them are similar. And the method used by `MuMIn` is more akin to your second approach of obtaining estimates, then combining them.

Anyway, now my mind is spinning around an idea of having a class (say, `emmGrid_list`) that's like `emmGrid`, but has lists of several coefficients and `vcov` matrices (and a common `grid` of predictor combinations and associated `linfct` slots). To summarize, we would separately summarize with each model, then combine the results using a function like `MuMIn::par.avg()`, which is what is at the heart of `MuMIn::predict.averaging()`. It seems like this could be a promising approach *if* the methods for combining several models' predictions are similar. But it would require my old, feeble mind to learn some new things... I may need to find a co-developer to pull this off. Maybe it even ought to be a separate package?

**Comment by ablack3** [comment] 2019-01-25 06:07
I wonder if it would be possible to go a simple route and just implement custom support for **mice** and **MuMln** outputs without generalizing too much. I could work on the **mice** output although be forewarned I am still an immature developer and would probably need some guidance. (emmeans is an awesome package by the way!) Here is what I have so far. This is a quick first pass at a emmeans method for multiple imputed repeated analysis (mira) object. I realize this is won't work as is but it is perhaps a start.

Our research question: Do droids have lower or higher BMIs than humans after accounting for age and gender?

`
library(dplyr)
set.seed(1)
df <- starwars %>% 
  filter(species %in% c("Human", "Droid")) %>% 
  mutate(bmi = mass/(height/100)^2) %>% 
  select(bmi, age = birth_year, gender, species) %>% 
  wakefield::r_na(prob = .2)

library(mice)
mids <- mice(df, seed = 1)
mira <- with(mids, lm(bmi ~ age + gender + species))

emmeans.mira <- function(object, specs, ...){
  
  spec_names <- purrr::map(specs, as.name)

  # purrr::map(object$analyses, ~as.data.frame(emmeans::emmeans(., specs, ...))) %>% # if I try passing the dots here I get an error. Not sure why.
  purrr::map(object$analyses, ~as.data.frame(emmeans::emmeans(., specs))) %>%
    purrr::reduce(bind_rows) %>%
    mutate(variance = SE^2) %>%
    group_by(!!!spec_names) %>%
    summarise(mean_emmean = mean(emmean), 
              mean_variance = mean(variance), 
              n = n(), 
              between_variance = 1/(n-1)*sum((emmean - mean(emmean))^2), 
              df = unique(df)) %>%
    mutate(SE = sqrt(mean_variance + (1 + 1/n)*between_variance)) %>% 
    select(1, emmean = mean_emmean, SE, df) 
}


emmeans.mira(mira, specs = c("species"))

`

**Comment by rvlenth** [comment] 2019-01-25 15:22
It looks like you have an idea for something that will work for you. However, notice that `emmeans()` is not implemented via methods for a generic `emmeans` function, but rather through `recover_data` and `emm_basis` methods for various models; `ref_grid()` calls these methods to construct the reference grid.

In addition, "simple route" is in the eyes of the beholder. As the **emmeans** developer, I want to find unifying frameworks that work with certain classes of models, so that I don't need to write different versions of the same complicated code every time I encounter a model like that. If the idea of summarizing several `emmGrid` objects via within- and between-model variances carries over appropriately to several scenarios, then I want to put my efforts into implementing that framework and using it with each of those model types, rather than vice versa. Meanwhile, it looks like you have something started that may serve your specific needs in the near term for MI situations.

**Comment by rvlenth** [comment] 2019-02-06 18:24
I just pushed an update that supports `mira` objects. [Oops, I forgot to reference this issue in the commit message)

 It averages together the regression coefficients and the covariance matrices, and adds the between-imputation covariance per Rubin's rules. With your example...
```
> ref_grid(mira)
NOTE: A nesting structure was detected in the fitted model:
    gender %in% species
'emmGrid' object with variables:
    age = 47.078
    gender = female, male, none
    species = Droid, Human
Nesting structure:  gender %in% species

> emmeans(mira, "species")
NOTE: A nesting structure was detected in the fitted model:
    gender %in% species
 species emmean  SE df lower.CL upper.CL
 Droid     34.4 4.5 20     25.0     43.8
 Human     25.8 1.9 20     21.9     29.8

Results are averaged over the levels of: gender 
Confidence level used: 0.95 

> ### Show more digits for comparison...
> print(summary(.Last.value), digits = 5)
 species emmean     SE df lower.CL upper.CL
 Droid   34.357 4.5033 20   24.963   43.751
 Human   25.816 1.8989 20   21.855   29.777

Results are averaged over the levels of: gender 
Confidence level used: 0.95 
```
These results differ slightly from yours because with your method, a different average age is used in each imputation to get the EMMs, whereas I compute an average dataset and use its common average age in the grid:
```
> sapply(mira$analyses, function(m) ref_grid(m)@grid$age[1])
### ... messages omitted ...
[1] 41.90833 46.26667 47.05833 47.03750 53.12083
> mean(.Last.value)
[1] 47.07833
```
I think using common covariate reference values is the right way to go.

**Comment by rvlenth** [comment] 2019-03-14 21:57
The current CRAN version (1.3.3) now incorporates **mice** support. I hope that this support addresses your needs -- or that you will let me know if it doesn't. But I think this issue is largely resolved, so am closing it.

**Closed by rvlenth** 2019-03-14 21:57 UTC
Labels: enhancement, question
