### ISSUE TITLE
Error when using aov object from ezANOVA in v1.3.4

### ISSUE THREAD

**Issue by aylinsgl** [rvlenth/emmeans#111] opened 2019-06-05 12:26 UTC
Hey,
we have recently discovered that using an aov object retrieved from an ezANOVA output like this:

```
ez <- ezANOVA(
  data = agg.acc
  , dv = correct
  , wid = sub
  , within =.(type,related)
  , return_aov = TRUE)

emm <- emmeans(ez$aov, ~ related * type)
```
gives the error 

`Error in formula(aov_formula) : object 'aov_formula' not found`

when using v1.3.4 of emmeans, however not when using v1.3.0. There it works just fine. 

Does anyone know why this happens? 
Thank you in advance! :)

**Comment by rvlenth** [comment] 2019-06-05 18:30
I have never used the **ez** package or `ezANOVA`, and I don't have the dataset you show, so there is no way I can reproduce this. If you send a dataset that reproduces this error, along with the complete code for fitting the model, I can look at it.

I'll also mention that the string `aov_formula` does not appear anywhere in the **emmeans** package code. So it seems like this could be something unrelated to **emmeans**. Did you make any other package-installation changes when you updated **emmeans**?

All that said, there are two changes in recent versions:

  * Changed `aovlist` support so it re-fits the model when non-sum-to-zero
    contrasts were used
  * Added support for multivariate response in `aovlist` models (#73)

The second one seems unlikely to have affected you, unless you have a multivariate response. But the first definitely *does* seem like it could apply. If so, I think you can work around it like this:

```r
options(contrasts = c("contr.sum", "contr.poly"))
ez <- ezANOVA(
  data = agg.acc
  , dv = correct
  , wid = sub
  , within =.(type,related)
  , return_aov = TRUE)
```
Re-fitting the model manually like this will prevent `emmeans` from having to re-fit it later. And actually, when you're using `aov` or anything that uses `aov`, you should always change those options first because the default contrasts bias the fixed effects badly.

**Comment by rvlenth** [comment] 2019-07-18 19:06
Seeing no further comment, I will close this. I add a further comment that using `aov()` with error strata is a relatively antiquated approach, and one is better off using `lme4::lmer()` for simple error structures, or `lm()` with a multivariate response or `nlme::lme()` for more sophisticated error structures.

**Closed by rvlenth** 2019-07-18 19:06 UTC
