### ISSUE TITLE
emmeans() for {ordbetareg} models only reports output on the log odds scale

### ISSUE THREAD

**Issue by mz555** [rvlenth/emmeans#477] opened 2024-04-11 08:23 UTC
I fit a model using the {ordbetareg} package.

```{r}
ordbeta.m1 <- ordbetareg(
  bf(Count ~ condition * Profession + (1 | part_id)), 
  data = MAGL.data.long,
  true_bounds = c(0, 3))
```

When I try to compute pairwise contrasts for the interaction term of interest, `emmeans()` will only provide responses on the log odds scale, regardless of what the `type = ` argument is. This was confirmed by the {ggeffects} package dev who suggested I make this ticket.

```{r}
emm.RQ1 <- emmeans(ordbeta.m1, ~condition | Profession, type = "response")) |>
  contrast("trt.vs.ctrl", ref = 1)
```
Output:
```{r}
Profession = writ:
 condition  emmean lower.HPD upper.HPD
 1         -0.3116   -0.3683   -0.2564
 2         -0.3609   -0.4209   -0.3041
 3         -0.0280   -0.0880    0.0298
 4         -0.2011   -0.2547   -0.1491
 5         -0.1917   -0.2413   -0.1359

Point estimate displayed: median 
HPD interval probability: 0.95 
```
And changed to something else, `type = "scale"`:
```{r}
Profession = writ:
 condition  emmean lower.HPD upper.HPD
 1         -0.3116   -0.3683   -0.2564
 2         -0.3609   -0.4209   -0.3041
 3         -0.0280   -0.0880    0.0298
 4         -0.2011   -0.2547   -0.1491
 5         -0.1917   -0.2413   -0.1359

Point estimate displayed: median 
HPD interval probability: 0.95 
```

## Describe the bug
I would like for the output to either be on the DV scale (counts here) or the probability scale (0-1), but this only is possible in the marginaleffects package for now.

**Comment by rvlenth** [comment] 2024-04-11 12:11
Traveling. It will be a while but offhand, I think the problem is just that these objects are not supported in emmeans. The developer of ordbetareg could write the needed methods. there is a vignette on that.

On Apr 11, 2024, at 10:24 AM, DR MZ ***@***.***> wrote:

﻿

I fit a model using the {ordbetareg} package.

ordbeta.m1 <- ordbetareg(
  bf(Count ~ condition * Profession + (1 | part_id)),
  data = MAGL.data.long,
  true_bounds = c(0, 3))


When I try to compute pairwise contrasts for the interaction term of interest, emmeans() will only provide responses on the log odds scale, regardless of what the type = argument is. This was confirmed by the {ggeffects} package dev who suggested I make this ticket.

emm.RQ1 <- emmeans(ordbeta.m1, ~condition | Profession, type = "response")) |>
  contrast("trt.vs.ctrl", ref = 1)


Output:

Profession = writ:
 condition  emmean lower.HPD upper.HPD
 1         -0.3116   -0.3683   -0.2564
 2         -0.3609   -0.4209   -0.3041
 3         -0.0280   -0.0880    0.0298
 4         -0.2011   -0.2547   -0.1491
 5         -0.1917   -0.2413   -0.1359

Point estimate displayed: median
HPD interval probability: 0.95


And changed to something else, type = "scale":

Profession = writ:
 condition  emmean lower.HPD upper.HPD
 1         -0.3116   -0.3683   -0.2564
 2         -0.3609   -0.4209   -0.3041
 3         -0.0280   -0.0880    0.0298
 4         -0.2011   -0.2547   -0.1491
 5         -0.1917   -0.2413   -0.1359

Point estimate displayed: median
HPD interval probability: 0.95


Describe the bug

I would like for the output to either be on the DV scale (counts here) or the probability scale (0-1), but this only is possible in the marginaleffects package for now.

**Comment by mz555** [comment] 2024-04-11 13:15
Thank you for the quick response. I have also contacted the {ordbetareg} dev. For context, their package is just a wrapper and some special families for the {brms} package, which i believe is natively supported by {emmeans} and does work well with beta family models.

**Comment by strengejacke** [comment] 2024-04-12 07:07
Just to add: the same issue can be seen for `glmmTMB(family=ordbeta())`. So it might be emmeans not detecting the response / link inverse correctly? Just a guess

**Comment by rvlenth** [comment] 2024-04-23 21:03
Please provide a reproducible example. I don't have the MAGL.data.long data

**Comment by rvlenth** [comment] 2024-06-05 13:55
This issue has been languishing here, but I honestly don't know what to do with it, so I am closing it. **emmeans** does not support the **ordbetareg** package, and if that package's code is just a wrapper for **brms** code, that's still not an **emmeans** issue because **brms** provides its own **emmeans** support. There are several options for that brms code. I suggest you look at `? emm_basis.brmsfit`.

**Closed by rvlenth** 2024-06-05 13:55 UTC
Labels: bug
