### ISSUE TITLE
Warning and Error when plotting contrast

### ISSUE THREAD

**Issue by rpmady** [rvlenth/emmeans#108] opened 2019-05-17 15:59 UTC
I ran a model with an interaction between location and treatment.
```
mod <- glmmTMB(sum.50 ~ location*trtmt + julian2 + min_aft_sunrise2 + mintemp2 + (1|site:day + (1|week), data = bcch_sub, ziformula=~1, family=nbinom1) 
```
I'm interested in the difference between differences. Is there a difference between near and far across treatments. 
So I calculated Estimated Marginal Means and then the differences between them.
```
mod3.emm <- emmeans(mod3, ~ location|trtmt, adjust = "none")
locdiffs <- contrast(mod3.emm, "revpairwise", adjust="none")
c <- contrast(locdiffs, "revpairwise", by = NULL, adjust = "mvt")
c
````
```
 contrast                                          estimate    SE  df t.ratio p.value
 near - far,constant - near - far,pulsed_nofood       1.003 0.534 123 1.878   0.1475 
 near - far,pulsed_food - near - far,pulsed_nofood    1.698 0.625 123 2.718   0.0201 
 near - far,pulsed_food - near - far,constant         0.695 0.510 123 1.363   0.3605 
```
When I try to plot c using plot(c), I get this output: ```There were 43 warnings (use warnings() to see them)```
When I use warnings(), I see many repeats, but these are the unique ones: 
```
1: In delta + sds * qt(1 - (1 - p)/2, df = df) :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.

2: In delta/sds :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.
24: In checkmvArgs(lower = lower, upper = upper, mean = delta,  ... :
  both ‘corr’ and ‘sigma’ specified: ignoring ‘sigma’
````
I'm not sure what to make of it. I also get similar warnings when I try to use the function 
```confint()``` on c.

**Comment by rvlenth** [comment] 2019-05-17 16:35
This may be due to the fact that you named the result `c`, which is also the name of the function for concatenating things into an array. Try
```r
diffdiffs <- contrast(locdiffs, "revpairwise", by = NULL, adjust = "mvt")
plot(diffdiffs
```
and see if you get the same errors

**Comment by rpmady** [comment] 2019-05-17 16:40
Unfortunately I do get the same errors.

**Comment by rvlenth** [comment] 2019-05-17 17:05
I don't get errors like this with a parallel example, using R 3.5.2. Is this with R 3.6.0???

**Comment by rpmady** [comment] 2019-05-17 17:14
That's strange. I can try to make a reproducible example? 
I am using R 3.5.2 as well.

**Comment by rvlenth** [comment] 2019-05-17 17:37
Hmmm. Well, what I can say as this does not occur in the **emmeans** package. I did a search of the code, and the variable name `sds` is not used anywhere.

I did do a web search though, and it appears that this code is in the **mvtnorm** package, perhaps in the function `mvtnorm:::getInt`. And that package is related to the `"mvt"` adjustment you specified. Perhaps if you specify `adjust = "tukey"` or `adjust = "none"`, you won't get the warnings. I wonder if this is happening because of a small number of degrees of freedom or something.

**Comment by rvlenth** [comment] 2019-05-17 19:19
A reproducible example would help.

I am assuming that you don't get warnings when not using `adjust = "mvt"`.

**Comment by rvlenth** [comment] 2019-05-18 16:08
Here's an idea that might make it possible to debug this: Assuming that `c` is the object you created in the original communication, do:
```r
c.list <- as.list(c)
dump("c.list", stdout())
```
This will give you about a screen's worth of stuff. Copy and paste the results here (make sure you get it all -- a bit extra before and after won't hurt), then I can recover the object and see if I experience the same warnings.

**Comment by rpmady** [comment] 2019-05-20 14:47
You're right, I don't get warnings when I don't use the adjust = "mvt
 in the plot() function itself now. So that may be part of my problem. I'm able to plot both "locdiffs" and "c." 
But I can't use comparisons = TRUE for either plot -- ie I get warnings. 

Here is the the result of the code you just sent (it's a lot!): 
```
c.list <-
list(bhat = c(`(Intercept)` = -0.765568509261142, locationnear = 1.62353676041158, 
trtmtpulsed_food = -1.2722003687095, trtmtpulsed_nofood = -0.549982723731013, 
julian2 = 0.0139577785663497, min_aft_sunrise2 = 0.00506423675709075, 
mintemp2 = -0.0565192055237848, `locationnear:trtmtpulsed_food` = 0.789980215026524, 
`locationnear:trtmtpulsed_nofood` = -1.33741736947486), V = structure(c(0.102529984569147, 
-0.0847909338246014, -0.0878736386305804, -0.084009986682354, 
-0.000656386683232686, -0.00201988658323706, 0.000199220714623119, 
0.080316572932304, 0.0839750799009895, -0.0847909338246015, 0.0979570808429229, 
0.0778149454594449, 0.0766664226911762, 0.0021780327743463, 0.000188202653750035, 
0.00283522235196, -0.0954489099374189, -0.0981541166905095, -0.0878736386305805, 
0.0778149454594449, 0.610698706461952, 0.0850308395561106, -0.00173373394156271, 
-0.000682859103290641, 0.000799047759066078, -0.585746637396642, 
-0.0784076837417557, -0.084009986682354, 0.0766664226911763, 
0.0850308395561104, 0.36080867946353, 0.000878479638077005, -0.00122357783715252, 
-0.00130108197294307, -0.0767174389843266, -0.336820113439432, 
-0.000656386683232685, 0.0021780327743463, -0.00173373394156271, 
0.000878479638077005, 0.0134998392489701, 0.00286548589612027, 
0.0049050556685476, -0.00212544135028766, -0.00426624055199171, 
-0.00201988658323706, 0.000188202653750035, -0.000682859103290641, 
-0.00122357783715252, 0.00286548589612027, 0.00975407170631993, 
-0.00180848877349096, 0.000508581072091309, 0.00045349939334931, 
0.000199220714623119, 0.00283522235196, 0.000799047759066073, 
-0.00130108197294306, 0.0049050556685476, -0.00180848877349096, 
0.0125666247165729, -0.00293513161793991, -0.00428362202609617, 
0.0803165729323041, -0.0954489099374191, -0.585746637396642, 
-0.0767174389843267, -0.00212544135028767, 0.000508581072091308, 
-0.00293513161793991, 0.647294535211958, 0.0958374770143748, 
0.0839750799009895, -0.0981541166905095, -0.0784076837417555, 
-0.336820113439432, -0.00426624055199171, 0.000453499393349309, 
-0.00428362202609616, 0.0958374770143746, 0.570209468878183), .Dim = c(9L, 
9L), .Dimnames = list(c("(Intercept)", "locationnear", "trtmtpulsed_food", 
"trtmtpulsed_nofood", "julian2", "min_aft_sunrise2", "mintemp2", 
"locationnear:trtmtpulsed_food", "locationnear:trtmtpulsed_nofood"
), c("(Intercept)", "locationnear", "trtmtpulsed_food", "trtmtpulsed_nofood", 
"julian2", "min_aft_sunrise2", "mintemp2", "locationnear:trtmtpulsed_food", 
"locationnear:trtmtpulsed_nofood"))), levels = list(contrast = structure(1:3, .Label = c("near - far,pulsed_food - near - far,constant", 
"near - far,pulsed_nofood - near - far,constant", "near - far,pulsed_nofood - near - far,pulsed_food"
), class = "factor")), linfct = structure(c(0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -1, 0, 1, 
1), .Dim = c(3L, 9L), .Dimnames = list(NULL, c("(Intercept)", 
"locationnear", "trtmtpulsed_food", "trtmtpulsed_nofood", "julian2", 
"min_aft_sunrise2", "mintemp2", "locationnear:trtmtpulsed_food", 
"locationnear:trtmtpulsed_nofood"))), dffun = function (k, dfargs) 
                                                                                                                                                                                                                                                                     dfargs$df, 
    dfargs = list(df = 124L), post.beta = structure(NA, .Dim = c(1L, 
    1L)), tran = "log", inv.lbl = "ratio", estName = "estimate", 
    estType = "pairs", infer = c(FALSE, TRUE), level = 0.95, 
    adjust = "mvt", famSize = 3L, avgd.over = character(0), methDesc = "pairwise differences", 
    is.new.rg = FALSE, orig.grid = structure(list(contrast = structure(c(1L, 
    1L, 1L), .Label = "near - far", class = "factor"), trtmt = structure(1:3, class = "factor", .Label = c("constant", 
    "pulsed_food", "pulsed_nofood"))), row.names = c(NA, -3L), class = "data.frame"), 
    con.coef = structure(c(-1, -1, 0, 1, 0, -1, 0, 1, 1), .Dim = c(3L, 
    3L), .Dimnames = list(c("near - far,pulsed_food - near - far,constant", 
    "near - far,pulsed_nofood - near - far,constant", "near - far,pulsed_nofood - near - far,pulsed_food"
    ), c("near - far,constant", "near - far,pulsed_food", "near - far,pulsed_nofood"
    ))), orig.tran = "log", log.contrast = TRUE, orig.inv.lbl = "ratio")
```

**Comment by rvlenth** [comment] 2019-05-20 18:39
Hmmm, well, I don't get any errors or warnings:
```r
> con = as.emmGrid(c.list)
> confint(con)
 contrast                                          estimate    SE  df lower.CL upper.CL
 near - far,pulsed_food - near - far,constant          0.79 0.805 124    -1.11    2.687
 near - far,pulsed_nofood - near - far,constant       -1.34 0.755 124    -3.12    0.443
 near - far,pulsed_nofood - near - far,pulsed_food    -2.13 1.013 124    -4.52    0.261

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
Conf-level adjustment: mvt method for 3 estimates 
```
Nor do I have problems with plots:
```r
plot(con, intervals = TRUE)
```
![image](https://user-images.githubusercontent.com/26777519/58042189-a1202b80-7aff-11e9-9790-5a605b4c0b21.png)
```r
plot(con, comparisons= TRUE)
```
![image](https://user-images.githubusercontent.com/26777519/58042243-c3b24480-7aff-11e9-9aa2-4422f6534dec.png)

**NOTE** This last plot is meaningless though! You have *already* computed the comparisons you need: those are plotted in the first plot. The arrows in the 2nd plot are comparisons of those comparisons, and that's not what you want. For example, copmparing the red arrows in the 1st and second lines is for comparing `near - far,pulsed_food - near - far,constant` with `near - far,pulsed_nofood - near - far,constant` which reduces algebraically to  `near - far,pulsed_food` minus `near - far,pulsed_nofood`, and this is depicted in the *third* bar in the *first* plot.

I noticed that these estimates and SEs are different from those in your original post. I actually restarted R and copy-pasted `c.list` again, and didn't get the same results, or even the same labels. That mystified me until I realized I pasted it from your e-mail the first time, and from the github window the second time, and you had subsequently edited it. However, both versions worked fine for me, and neither version has the same estimates and SEs as the original posting. So I am not sure what is going on,a nd it seems like I'm working with a moving target. I'm not sure what I can conclude, other than I think it's a problem with a particular model you have, not with **emmeans** in general.

**Comment by rpmady** [comment] 2019-05-20 19:29
I apologize for the estimates and the SE changing -- the random effects I include the model have recently changed. I have edited my comment with the ```c.list```. I also copy and repasted it back to make sure I was still getting an error and I am. 

I do agree, the second plot is meaningless. I wanted to do 
```
plot(c)
plot(locdiffs, comparisons=TRUE)
```

**Comment by rvlenth** [comment] 2019-05-21 02:47
From the revised dump...
```r
> con = as.emmGrid(c.list)
> confint(con)
 contrast                                          estimate    SE  df lower.CL upper.CL
 near - far,constant - near - far,pulsed_nofood       1.003 0.534 123   -0.260     2.27
 near - far,pulsed_food - near - far,pulsed_nofood    1.698 0.625 123    0.220     3.18
 near - far,pulsed_food - near - far,constant         0.695 0.510 123   -0.511     1.90

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
Conf-level adjustment: mvt method for 3 estimates
```
I do match the reported estimates and SEs. But no warnings were issued. Beats me.

**Comment by rvlenth** [comment] 2019-05-21 02:51
*Maybe* if you restart R and then do `install.packages("mvtnorm")` before restoring anything else, it will fix itself. I am pretty sure the warnings come from **mvtnorm**, as outlined above.

**Comment by rpmady** [comment] 2019-05-21 12:25
I restarted R, did install.packages("mvtnorm") and also made sure that R was version 3.5.3 (version that the emmeans package was built for). I successfully ran functions ```plot(locdiffs)``` and ```plot(c)```. I am still unable to ```plot(locdiffs, comparisons=TRUE)```.
```
> plot(locdiffs, comparisons = TRUE)
Warning messages:
1: In min(d[involved[[i]]]) :
  no non-missing arguments to min; returning Inf
2: In min(d[involved[[i]]]) :
  no non-missing arguments to min; returning Inf
3: In min(d[involved[[i]]]) :
  no non-missing arguments to min; returning Inf
4: Removed 3 rows containing missing values (geom_segment). 
```

**Comment by rpmady** [comment] 2019-05-29 17:18
Also, when I take out the adjust="mvt", the problem still occurs - I can't plot the red comparison arrows, but I can plot the confidence intervals.

**Comment by rvlenth** [comment] 2019-07-18 19:14
I see no recent traffic on this, so am closing the issue.

**Closed by rvlenth** 2019-07-18 19:14 UTC
