### ISSUE TITLE
emtrends does not allow retransforming scaled variables

### ISSUE THREAD

**Issue by singmann** [rvlenth/emmeans#54] opened 2018-10-25 22:13 UTC
Hi Russ,

I noticed the following problems disallowing `scale()` in the `var` part of `emtrends`.

```r
library("emmeans")
data("Prestige", package = "carData")
mp_3 <- lm(income ~ scale(education)*scale(prestige), Prestige)

emtrends(mp_3, specs = "education", var = "prestige", 
         at = list(education = c(8.01, 10.74, 13.47)))
#  education prestige.trend       SE df lower.CL upper.CL
#       8.01       141.6524 40.24965 98  61.7783 221.5266
#      10.74       186.9203 32.50945 98 122.4064 251.4343
#      13.47       232.1882 34.95312 98 162.8249 301.5515
# 
# Confidence level used: 0.95 

emtrends(mp_3, specs = "education", var = "scale(prestige)", 
         at = list(education = c(8.01, 10.74, 13.47)))
# Error in if (any(diffl == 0)) warning("Some differentials are zero") : 
#   missing value where TRUE/FALSE needed
```

Best,
Henrik

**Comment by rvlenth** [comment] 2018-10-26 01:05
Henrik,

The problem is that `scale()` requires all of the original values of `prestige`, which are not available in the scope of `emtrends()`. Here are 3 ways to get it to work.

One way is to pre-scale the values:

> Prestige <- transform(Prestige, sc.pres = scale(prestige))
> mp_4 <- lm(income ~ scale(education)*sc.pres, Prestige)
> emtrends(mp_4, specs = "education", var = "sc.pres",
+          at = list(education = c(8.01, 10.74, 13.47)))
education sc.pres.trend       SE df lower.CL upper.CL
      8.01      2437.057 692.4746 98 1062.864 3811.250
     10.74      3215.868 559.3084 98 2105.939 4325.797
     13.47      3994.679 601.3504 98 2801.318 5188.039

Another is to explicitly provide the mean and sd. This requires that you also disable its returning a matrix:

> emtrends(mp_3, specs = "education", var = "as.numeric(scale(prestige, 46.8333, 17.20449))",
+          at = list(education = c(8.01, 10.74, 13.47)))
education as.numeric(scale(prestige, 46.8333, 17.20449)).trend       SE df lower.CL upper.CL
      8.01                                             2437.058 692.4748 98 1062.864 3811.251
     10.74                                             3215.869 559.3086 98 2105.939 4325.798
     13.47                                             3994.680 601.3506 98 2801.319 5188.040

Third, same as above but with a custom function to make the output less messy:

> Scale = function(x)
+     as.numeric(scale(x, 48.8333, 17.20449))
> emtrends(mp_3, specs = "education", var = "Scale(prestige)",
+          at = list(education = c(8.01, 10.74, 13.47)))
education Scale(prestige).trend       SE df lower.CL upper.CL
      8.01              2437.058 692.4748 98 1062.864 3811.251
     10.74              3215.869 559.3086 98 2105.939 4325.798
     13.47              3994.680 601.3506 98 2801.319 5188.040

Cheers,

Russ

**Comment by rvlenth** [comment] 2018-10-26 15:20
Henrik, 
The problem is that `scale()` requires all of the original values of `prestige`, which are not available in the scope of `emtrends()`. Here are 3 ways to get it to work. 

One way is to pre-scale the values: 
```
Prestige <- transform(Prestige, sc.pres = scale(prestige)) 
mp_4 <- lm(income ~ scale(education)*sc.pres, Prestige) 
emtrends(mp_4, specs = "education", var = "sc.pres", at = list(education = c(8.01, 10.74, 13.47))) 
## education sc.pres.trend       SE df lower.CL upper.CL
##      8.01      2437.057 692.4746 98 1062.864 3811.250
##     10.74      3215.868 559.3084 98 2105.939 4325.797
##     13.47      3994.679 601.3504 98 2801.318 5188.039
```
 Another is to explicitly provide the mean and sd. This requires that you also disable its returning a matrix: 
```
emtrends(mp_3, specs = "education", var = "as.numeric(scale(prestige, 46.8333, 17.20449))", 
         at = list(education = c(8.01, 10.74, 13.47)))
## education as.numeric(scale(prestige, 46.8333, 17.20449)).trend       SE df lower.CL upper.CL
##      8.01                                             2437.058 692.4748 98 1062.864 3811.251
##     10.74                                             3215.869 559.3086 98 2105.939 4325.798
##     13.47                                             3994.680 601.3506 98 2801.319 5188.040
```
Third, same as above but with a custom function to make the output less messy: 
```
Scale = function(x) as.numeric(scale(x, 48.8333, 17.20449))
emtrends(mp_3, specs = "education", var = "Scale(prestige)", 
         at = list(education = c(8.01, 10.74, 13.47)))
## education Scale(prestige).trend       SE df lower.CL upper.CL
##      8.01              2437.058 692.4748 98 1062.864 3811.251
##     10.74              3215.869 559.3086 98 2105.939 4325.798
##     13.47              3994.680 601.3506 98 2801.319 5188.040
```

**Comment by singmann** [comment] 2018-10-26 22:19
I have come up with a more principled suggestion by writing a new function, `rescale` that uses `dynGet` to get the necessary information from the environments in the call stack. 

I also wrote another function, `mean_sd`, that uses a similar approach and can be used to specify the points on the `specs` variable in SD units. In the example above, the points are chosen such that they represent mean of `education` + -1, 0, and +1 times SD of `education`. And `mean_sd` returns those per default. Here are the functions:

```
rescale <- function(x) {
  fcn <- sub("rescale\\((.+)\\)", "\\1", dynGet("fcn"))
  data <- recover_data(dynGet("model"))
  var <- with(data, eval(parse(text = fcn)))
  var_scale <- scale(var)
  return(as.numeric(scale(
    x = x, 
    center = attr(var_scale, "scaled:center"), 
    scale = attr(var_scale, "scaled:scale")
  )))
}

mean_sd <- function(x, at = c(-1, 0, 1)) {
  fcn <- deparse(substitute(x))
  data <- recover_data(dynGet("model"))
  var <- with(data, eval(parse(text = fcn)))
  var_scale <- scale(var)
  return(attr(var_scale, "scaled:center") + at*attr(var_scale, "scaled:scale"))
}
```

With this, the example above becomes:
```
library("emmeans")
data(Prestige, package = "carData")
mp_3 <- lm(income ~ scale(education)*scale(prestige), Prestige)
emtrends(mp_3, specs = "education", var = "rescale(prestige)", 
         at = list(education = mean_sd(education)))
#  education rescale(prestige).trend       SE df lower.CL upper.CL
#   8.009595                2436.942 692.5040 98 1062.690 3811.193
#  10.738039                3215.309 559.3463 98 2105.304 4325.313
#  13.466483                3993.676 601.1829 98 2800.648 5186.703
# 
# Confidence level used: 0.95 
```
We get the scaled slope of `prestige` for the three values of education based on mean + SD.

The good thing about the functions is that they also work with further transformations as the following example shows:

```
data(Highway1, package = "carData")
summary(h2 <- lm(log2(rate) ~ scale(log2(len))*scale(log2(sigs1)), 
                 data = Highway1))
emtrends(h2, specs = "len", var = "rescale(log2(sigs1))", 
         at = list(len = mean_sd(log(len))))
#       len rescale(log2(sigs1)).trend        SE df  lower.CL upper.CL
#  1.785701                  0.8958535 0.2845766 35 0.3181323 1.473575
#  2.388839                  0.7963091 0.2443039 35 0.3003459 1.292272
#  2.991977                  0.7192975 0.2139129 35 0.2850311 1.153564
# 
# Trends are based on the log2 (transformed) scale 
# Confidence level used: 0.95 
```

I am not sure if it makes sense to include these functions like this or keep them external, but I am open for any suggestions. In any case, I think they solve my problem for now.

**Comment by rvlenth** [comment] 2018-12-03 21:47
Henrik,

I'm going to close this issue as I think it is resolved. I am not inclined to add more support code for `scale()` at this time, as I think having a function of a different name isn't going to do much to avoid confusion in situations like this.

**Closed by rvlenth** 2018-12-03 21:47 UTC
Labels: help wanted
