### ISSUE TITLE
column order affects emmeans outcome

### ISSUE THREAD

**Issue by xabiben** [rvlenth/emmeans#86] opened 2019-02-13 11:16 UTC
I want to present a little issue that I found. I am trying to use emmeans as a posthoc comparision after a MANOVA with 2 IV and 3 DV. The nature of the DV´s seem to be compostional , so I transform them with an isometric transformed log-ratio (ilr function in the compostions packages).  Data has this structure:

```{r}
data <- data.frame(IV1 = factor(c(1,1,1,1,2,2,2,2)),
 IV2 = factor(c(1,2,1,2,1,2,1,2)), DV1 = rnorm(8), DV2 = rnorm(8), DV3 = rnorm(8))

```
As I said, DV´s are strongly co-dependent (not in the example, though), so the require and ilr transformation.  The model that roughtly looks like this:
```{r}
model <- manova(cbind(ilr(clo(DV1, DV2, DV3))) ~IV1*IV2, data = data)
```
The model shows interaction, so that I would like to see differences between IV´s in a way like this:
```{r}
model.emm <- emmeans(model, ~IV1|IV2)
```
The problem comes when I performed the same thing inverting the DV order:
```{r}
model <- manova(cbind(ilr(clo(DV2, DV1, DV3))) ~IV1*IV2, data = data)
model.emm <- emmeans(model, ~IV1|IV2)
```
The outcome of ilr transformation changes (that is something I could expect), but not the information contained in it, as the MANOVA gives the same outcome, no mater the order of the factors. However, even though the model looks the same, the emmeans outcome completely chenges.

How is this possible? Which would be the correct order in the original data table to use?
EDIT: I have edited the question as the simplification of the problem I presented first was solved with updating the emmeans package to the last version (v 1.3.2.) As my actual issue is still unsoved, I add some more concrete details.

**Comment by rvlenth** [comment] 2019-02-13 15:45
Thanks for your report. I can't reproduce the example because I encounter an error fitting the model:
```
> model <- manova(cbind(ilr(clo(DV1, DV2, DV3))) ~IV1*IV2, data = data)
Error in gsi.plain(oneOrDataset(X))[, parts, drop = FALSE] : 
  only 0's may be mixed with negative subscripts
```
Here is another possibly parallel example:
```
> MOats1 = MOats
> MOats1$pyield = MOats$yield[, c(4,2,1,3)]   # permuted the order of columns

> mod1 = aov(yield ~ Variety + Error(Block), data = MOats1)
> mod2 = aov(pyield ~ Variety + Error(Block), data = MOats1)

> emmeans(mod1, "rep.meas")
Note: re-fitting model with sum-to-zero contrasts
 rep.meas emmean   SE df lower.CL upper.CL
 0          79.4 6.55  5     62.6     96.2
 0.2        98.9 7.02  5     80.9    116.9
 0.4       114.2 6.51  5     97.5    130.9
 0.6       123.4 7.86  5    103.2    143.6

Results are averaged over the levels of: Variety 
Confidence level used: 0.95 

> emmeans(mod2, "rep.meas")
Note: re-fitting model with sum-to-zero contrasts
 rep.meas emmean   SE df lower.CL upper.CL
 0.6       123.4 7.86  5    103.2    143.6
 0.2        98.9 7.02  5     80.9    116.9
 0          79.4 6.55  5     62.6     96.2
 0.4       114.2 6.51  5     97.5    130.9

Results are averaged over the levels of: Variety 
Confidence level used: 0.95
```
In this test case, I get the same results, permuted. *However*, this is after fixing a bug that is reported in issue #83. Perhaps if you install **emnmeans** from github, that will fix the problem? Please let me know.

**Comment by rvlenth** [comment] 2019-02-13 15:56
Looking at this again, I get a stronger idea that the transformation you are using varies depending on the order of the responses. In that case, you should *expect* the post hoc estimates to differ as well. While the two results may span the same space, that does not mean they are the same variables. 

For example, if you have two variables `length` and `width` describing a collection of rectangles, you might define `perimeter = 2*(length + width)` and `shape = length - width`. Then `(length, width)` and `(perimeter, shape)` contain exactly the same information, but summary varlues of `(length, width)` would not be the same as summary values of `(perimeter, shape)`.

**Comment by rvlenth** [comment] 2019-02-13 16:23
After looking at the documentation for `ilr()` and related examples I tested, I am completely convinced that the transformation depends on the order of entry and that the means will be completely different for different orderings. Adapting the example:
```
> cdata <- Hydrochem[,6:9]
> i1 = ilr(cdata)
> i2 = ilr(cdata[, 4:1])

> apply(i1, 2, mean)
[1] 16.089155  7.505488  6.303591

> apply(i2, 2, mean)
[1]  -0.8135644   1.3138777 -18.7760578

> summary(lm(i2 ~ i1))
# ... results not shown, but they show that each column of i2 is a linear function of columns of i1,
# with a perfect fit but with nonzero coefficients.
```

**Comment by xabiben** [comment] 2019-02-14 19:23
Sorry for the problems with the code. I did it to illustrate the example, but I did not make it with the purpose of being run. Your examples worked perfectly in my computer.
It is true that the ilr transformation is key here. I get your point, and yes, if you reorder the columns in the data set, the current values of the transformed matrices differ. However, I think that the statistical tests should  give similar results in any case. In fact the MANOVA analysis does. I will try to make an example of this and go further in the compositional analysis to clarify a bit concepts.

Lets play around with the Hydrochem dataset:
'''{r}
library(emmeans)
library(compositions)
data(Hydrochem)

X <- Hydrochem[,1:2]
Y <- clo(Hydrochem[,4:5])
'''
Y closed the Y component (with the clo function) to make it fully compositional. This will make the explanation easier. This means that now the columns correspond to percentages of the presence of the different minerals. This is how my actual dataset look like.
The main problem of this analysis is that your dependent variables covariate, as the correspond to "parts of a whole". That is if some component is increased, necessary it has to be at the expense of decreasing another one. Therefore the variance covariance matrix looks pretty fancy:
'''{r}
cov(Y)
rowSums(cov(Y))
'''
What I want to show with the rowsums operation is that the results are very close (if not exactly) 0. This is because the variance of a component can be explained by the rest of the components. It makes perfectly sense if you think that if you loose one column you can know what the values were by doing 1-(all the other columns).

This conditions a strong dependency between the DV's and if you would jump directly into inferential statistics, spurious correlations would appear. Here is where the isometric log-ratio comes to rescue. 
We can imagine graphically what ilr does by plotting all the dots in a

**Comment by rvlenth** [comment] 2019-02-15 19:06
I had to fit the same models using the actual variable names, as the column numbers don't work with `emmeans()`:
```
Mod1 = manova(i1 ~ Code * Site, data = X)
Mod12 = manova(i2 ~ Code * Site, data = X)

> summary(Mod1)   ### (same as summary(Mod2))
           Df   Pillai approx F num Df den Df    Pr(>F)
Code        1 0.017520   4.2797      2    480  0.014380
Site        1 0.022577   5.5437      2    480  0.004167
Code:Site   1 0.048651  12.2734      2    480 6.332e-06
Residuals 481
```

A couple of observations. First, as I indicated before, the manova tests are *omnibus* tests, while `emmeans()` estimates specific linear functions of the effects, each having 1 degree of freedom.

Second, the manova tests you obtain with your example have to do with comparing the slopes of the `Code` and `Site` trends at each `rep.meas`, not the marginal `rep.meas` means. (I'll add parenthetically that your model uses `Code` and `Site` as continuous covariates, which doesn't make any practical sense; but the example still serves as a numerical example.)

So here are some `emtrends()` results for the two models, with reference to the `Code` trends:
```
> (emtc1 = emtrends(Mod1, "rep.meas", var = "Code"))
 rep.meas Code.trend       SE  df  lower.CL  upper.CL
        1  -0.000609 0.000201 481 -0.001004 -0.000213
        2  -0.000466 0.000153 481 -0.000768 -0.000165

Confidence level used: 0.95 

> (emtc2 = emtrends(Mod2, "rep.meas", var = "Code"))
 rep.meas Code.trend       SE  df  lower.CL upper.CL
        1   9.97e-05 0.000103 481 -0.000103 0.000303
        2   7.60e-04 0.000231 481  0.000307 0.001214

Confidence level used: 0.95 
```
Note that the two models estimate different slopes for `Code`, because of the difference in how the transformation is done. However, in each case, the two trends embody the overall two-dimensional `Code` effect. If we perform a joint (omnibus) test of these trends, we get the same overall significance of the two trends:
```
> test(emtc1, joint = TRUE)
 df1 df2 F.ratio p.value
   2 481   5.618 0.0039 

> test(emtc2, joint = TRUE)
 df1 df2 F.ratio p.value
   2 481   5.618 0.0039
```
The *F* ratios for the two models are *identical* for the two models, albeit the common value differs somewhat from the manova results for `Code` (the d.f. differ too) -- that's because these are Wald tests, not the same as the Pillai tests in the manova. 

You can verify that the analogous joint tests for `Site` trends are also identical for the two models. I'm a little unclear on what to do for `Code:Site`. But the point is that *omnibus* tests of *trends* do give identical results for the two models.

**Comment by xabiben** [comment] 2019-02-20 16:33
Let me extend a bit more what I did. I hope I chose the appropiate model, also in the emmeans package, as you seem to be using different functions than I.
I changed the X variable to fit more my conditions, to make it closer to my actual dataset. Data will be completely made up, but it will show the point.
```{r }
X$Site <- factor(c(rep(1,242), rep(2,243)))
X$Location <- factor(c(rep(c(1,2),242),1))

mod1 <- manova(i1~Site*Location, data = X)
mod2 <- manova(i2~Site*Location, data = X)
summary(mod1)
summary(mod2)
```
In this particular case there is only main effect for the Site factor. In my dataset, interaction pops up as significant. So I chose to use an emmeans comparision, that looks like a Dunnet´s posthoc test:
```{r }
model.emm <- emmeans(mod1, ~Site|Location)
model2.emm <- emmeans(mod2, ~Site|Location)

test(contrast(model.emm, "dunnett"), side = "=", adjust = "dunnett")
test(contrast(model2.emm, "dunnett"), side = "=", adjust = "dunnett")
```
Here the p-values seem to be different depending on the ilr transformation you start from. Please, let me know if there is a better choice in the emmeans package to do this task.

Thanks a lot for all your work and patience.

**Comment by rvlenth** [comment] 2019-02-20 16:43
**emmeans** cannot do anything about this. It summarizes the model it is given. You have two different models with two different response variables, so you get two different sets of results.

**Comment by xabiben** [comment] 2019-02-20 16:59
All right, I was wondering if there could be something there that I was missing.

I will try to focus in the ilr transformation. Perhaps there is one of the combinations that give the best solution. Maybe the one that maximazes the total variance or something like that. Anyways, this is behind the scope of this forum. 

Again, thank you for all the attention and congratulations for the great work in the package.

Xabi

**Comment by rvlenth** [comment] 2019-03-14 21:53
As far as I can tell, this issue is resolved, so I am closing it.

**Closed by rvlenth** 2019-03-14 21:53 UTC
Labels: question

**Comment by rvlenth** [comment] 2024-07-23 20:39
Hello, I'm looking at past **emmeans** issues that mention the **compositions** package. I have just developed an `mvregrid()` function that performs multivariate transformations, and it might be relevant to this. If interested, take a look at the GitHub site or https://rvlenth.github.io/emmeans/reference/mvregrid.html. The example code doesn't show yet because it isn't yet on CRAN, but you can look in the `inst/extexamples` directory on GitHub
