### ISSUE TITLE
reference grid updated with transformation information doesn't work

### ISSUE THREAD

**Issue by maarten-jung** [rvlenth/emmeans#112] opened 2019-06-05 19:58 UTC
Following [these](https://cran.r-project.org/web/packages/emmeans/vignettes/transformations.html#after) instruction in the `emmeans` transformation vignette I couldn't get the `emmeans()` function to give me results on the response scale. 
```
library("lme4")
library("emmeans")

m1 <- lmer(1/Reaction ~ Days + (Days | Subject), sleepstudy)
rg <- update(ref_grid(m1), tran = "inverse")

# results should be given on the response scale 
# but they are still on the inverse scale
emmeans(rg, ~ Days, type = "response")
# Days  emmean       SE df lower.CL upper.CL
#  4.5 0.00347 0.000111 17  0.00323   0.0037
# 
# Degrees-of-freedom method: kenward-roger 
# Results are given on the inverse (not the response) scale. 
# Confidence level used: 0.95 
```
Is there a quick solution?

**Comment by rvlenth** [comment] 2019-06-06 18:48
Hmmm. I confirmed this. Here's a workaround...
```r
> summary(emmeans(rg, "Days"), type = "r")
 Days response   SE df lower.CL upper.CL
  4.5      288 9.23 17      270      309

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 
Intervals are back-transformed from the inverse scale
```
Or another way:
```r
> emmeans(rg, "Days", options = list(predict.type = "response"))
 Days response   SE df lower.CL upper.CL
  4.5      288 9.23 17      270      309

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 
Intervals are back-transformed from the inverse scale
```
Or yet another way:
```r
> rg <- update(ref_grid(m1), tran = "inverse", predict.type = "response")
> emmeans(rg, "Days")
 Days response   SE df lower.CL upper.CL
  4.5      288 9.23 17      270      309

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 
Intervals are back-transformed from the inverse scale
```

I am not sure why the `type` spec isn't passing through. I'll look at it.

**Comment by rvlenth** [comment] 2019-06-06 19:05
The clue is in this with a log transformation: If I give the model to `emmeans()`
```r
> m2 <- lmer(log(Reaction) ~ Days + (Days | Subject), sleepstudy)
> emmeans(m2, "Days", type = "r")
 Days response   SE df lower.CL upper.CL
  4.5      293 9.11 17      275      313

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 
Intervals are back-transformed from the log scale 
```
But if I give a ref. grid to emmeans:
```r
> emmeans(ref_grid(m2), "Days", type = "r")
 Days emmean     SE df lower.CL upper.CL
  4.5   5.68 0.0311 17     5.62     5.75

Degrees-of-freedom method: kenward-roger 
Results are given on the log (not the response) scale. 
Confidence level used: 0.95
```
What happens is that `type` is passed in the `...` argument of `emmeans()`, and those dots are passed to `ref_grid()` if it is called, which it is in the 1st case, but not in the 2nd. I added a line of code that copies any `type` entry into `options`, and that does the trick:
```r
> emmeans(rg, "Days", type = "r")
 Days response   SE df lower.CL upper.CL
  4.5      288 9.23 17      270      309

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 
Intervals are back-transformed from the inverse scale
```
This will be fixed in the next push to github.

**Closed by rvlenth** 2019-06-06 19:05 UTC

**Comment by maarten-jung** [comment] 2019-06-06 20:17
@rvlenth thanks for looking into that issue.
If found a related bug which might not be addressed by the fix you describe above. 

The `pairs()` and `contrast()` functions do not return results on the response scale when applied to an object generated by `emmeans()` given that `emmeans()` was applied to the updated reference grid.

```
> rg1 <- update(ref_grid(m1, at = list(Days = c(1, 3))), 
+               tran = "inverse", predict.type = "response")
> emm1 <- emmeans(rg1, ~ Days)
> pairs(emm1)
 contrast     estimate            SE df t.ratio p.value
 1 - 3    0.0002219872 0.00003100194 17    7.16  <.0001

> pairs(emm1, type = "reponse")
 contrast     estimate            SE df t.ratio p.value
 1 - 3    0.0002219872 0.00003100194 17    7.16  <.0001

> contrast(emm1, method = "pairwise")
 contrast     estimate            SE df t.ratio p.value
 1 - 3    0.0002219872 0.00003100194 17    7.16  <.0001

> contrast(emm1, method = "pairwise", type = "reponse")
 contrast     estimate            SE df t.ratio p.value
 1 - 3    0.0002219872 0.00003100194 17    7.16  <.0001
```

**Comment by rvlenth** [comment] 2019-06-06 23:29
I don't view that as a bug. It's mopre like precedence of operations. The argument `type = "response"`, as documented, specifies how to summarize results that have *already been computed*. All the estimates in `rg1` are on the inverse scale. When you run `contrast`, those results are computed on the inverse scale. At that point, the existing `"tran"` setting is nulled-out because those contrasts are no longer the reciprocals of anything. 

If you want to run the contrasts after back-transforming, that is done by re-gridding:
```r
> emm2 <- emmeans(regrid(rg1), ~ Days)
> emm2
 Days emmean   SE df lower.CL upper.CL
    1    259 7.08 17      244      274
    3    275 7.97 17      258      292

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 

> pairs(emm2)
 contrast estimate   SE df t.ratio p.value
 1 - 3       -15.9 2.38 17 -6.650  <.0001 
```

See the documentation for `regrid()` and `vignette("transformations")`

**Comment by maarten-jung** [comment] 2019-06-07 00:15
I understand why it makes sense to calculate the contrasts on the transformed scale and agree with your opinion/implementation.  I was just wondering why setting `type` to "response" works for `m2`  - but I guess this is because it can be argued that the difference/ratio of the marginal means on the log scale is also a meaningful ratio on the response scale. Is that correct?

```
> emm2 <- emmeans(m2, ~ Days, at = list(Days = c(1, 3)))
> pairs(emm2, type = "response")
 contrast    ratio          SE df t.ratio p.value
 1 / 3    0.934881 0.008888553 17  -7.082  <.0001

Tests are performed on the log scale
```

**Comment by rvlenth** [comment] 2019-06-07 00:43
That's correct. Contrasts of logs (usually) translate to logs of ratios, so they're treated specially.

Russ

**Comment by maarten-jung** [comment] 2019-06-10 19:04
OK. Thank you for clarifying.

**Comment by rvlenth** [comment] 2019-06-10 19:38
I think the update of emmeans is now on CRAN, with the fix included.

Sent from my iPhone

On Jun 10, 2019, at 2:04 PM, maarten-jung <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. Thank you for clarifying.
