### ISSUE TITLE
Problem in binning and renaming covariates after cov.reduce (possible bug)

### ISSUE THREAD

**Issue by kauttoj** [rvlenth/emmeans#237] opened 2020-10-24 09:26 UTC
I have a model with factorial and continuous predictors (aka covariates). In addition to running EMTRENDS, I would like to compare low and high levels of covariates against each other. I can do this with custom cov.reduce function. However, I want to rename my new bins with LEVELS function to make results easier to interpret. I noticed two problems:
(1) Renaming does not always work and depends on order of variables in model
(2) Renaming may lead to incorrect results

Here is a small example to reproduce this behavior:

```
require(emmeans)

set.seed(1)

fiber$dummy = factor(sample(1:3,nrow(fiber), replace=T)) # random dummy factor
model1 = lm(strength ~ machine*diameter + dummy,data=fiber) 
model2 = lm(strength ~ diameter*machine + dummy,data=fiber) # same as above

# function to get low and high values
discretizer = function(x) {
  high = quantile(x,0.80)
  low = quantile(x,0.20)
  res = c(low,high)
  return(res)
}

G = ref_grid(model1,cov.reduce = discretizer,nesting=list())
ems = emmeans(G,pairwise ~ diameter | dummy)
print("--- model 1 contrasts NO RENAMING ----")
print(ems$contrasts)

G = ref_grid(model2,cov.reduce = discretizer,nesting=list())
ems = emmeans(G,pairwise ~ diameter | dummy)
print("--- model 2 contrasts NO RENAMING ----")
print(ems$contrasts)

# SO FAR OK, results are identical as they should

G = ref_grid(model1,cov.reduce = discretizer,nesting=list())
levels(G)$diameter = c('diameter_LOW','diameter_HIGH') # rename levels to get prettier table
ems = emmeans(G,pairwise ~ diameter | dummy)
print("--- model 1 contrasts AFTER RENAMING ----")
print(ems$contrasts)  # STILL ORIGINAL LABELS AND WRONG RESULTS

G = ref_grid(model2,cov.reduce = discretizer,nesting=list())
levels(G)$diameter = c('diameter_LOW','diameter_HIGH')
ems = emmeans(G,pairwise ~ diameter | dummy)
print("--- model 2 contrasts AFTER RENAMING ----")
print(ems$contrasts) # results OK
```

Question: What is going on here? Am I using LEVELS function wrong or is there a bug in emmeans? 
I'm running the latest version emmeans_1.5.2.

**Comment by rvlenth** [comment] 2020-10-24 18:38
To tell the truth, I didn't provide a `levels` or `levels<-` method for `emmGrid` objects, and even know that the defaults would even work without error. But the problem is that my objects have a `grid` slot in addition to the `levels` slot. For the reference grid, these are pretty much redundant, but then they diverge once we run `emmeans()`. Your call to `levels<-` did not change the labels in the `grid`, and the labels in the summary are based on the `grid` slot. You can look at `G@grid` to see what `ems@grid` to see what you have.

My suggestion is to not try to mess with the levels in the `emmGrid` object, as this can cause errors. Instead, re-label the summary (which inherits from `data.frame`):
```r
summ = summary(ems)
levels(summ$diameter) = c('diameter_LOW', 'diameter_HIGH')
summ
```

**Comment by rvlenth** [comment] 2020-10-24 18:47
Oops -- I should have noticed that `ems` is an `emm_list` and that `diameter` is numeric. So you need something a bit differet:
```r
summ = summary(ems[[1]])
summ$diameter = factor(summ$diameter, labels = c('diameter_LOW','diameter_HIGH'))
```
then we get
```r
> summ
dummy = 1:
 diameter      emmean    SE df lower.CL upper.CL
 diameter_LOW    38.7 1.232  7     35.8     41.6
 diameter_HIGH   44.9 1.103  7     42.3     47.5

dummy = 2:
 diameter      emmean    SE df lower.CL upper.CL
 diameter_LOW    37.1 0.777  7     35.3     39.0
 diameter_HIGH   43.3 0.799  7     41.5     45.2

dummy = 3:
 diameter      emmean    SE df lower.CL upper.CL
 diameter_LOW    36.4 1.251  7     33.4     39.4
 diameter_HIGH   42.6 1.490  7     39.1     46.1

Results are averaged over the levels of: machine 
Confidence level used: 0.95 
```

**Comment by kauttoj** [comment] 2020-10-24 19:27
Ok. Renaming the output was actually my second approach, but I (wrongly) assumed that "levels" function was made particularly for this purpose. Thanks for the clarification and correct approach.

**Comment by rvlenth** [comment] 2020-10-24 19:41
Actually, I *will* consider implementing a `levels<-` method, or something similar. A related matter is that sometimes users fit a model with, say, a standardized predictor, but they want summaries and plots on the unstandardized scale.

In fact, this is in a sense a bug, since the default `levels<-` function *seems* to work, but in fact may screw things up. So I am re-opening this and labeling it a bug. At the very least, I should return an error message if somebody tries to re-level the object in this way.

**Comment by rvlenth** [comment] 2020-11-01 20:32
I have addressed this, I think:

  * I have provided a `labels<-` method to override the default. It just produces an error message
   and directs to the new `transform` method
  * The new `transform` method provides a reasonable interface for replacing, rescaling, and renaming levels
  * `update(..., levels = ...)` has been modified to just sending its arguments to `transform`.

So here is an excerpt from your example
```r
> G = ref_grid(model1,cov.reduce = discretizer,nesting=list())
> levels(G)$diameter = c('diameter_LOW','diameter_HIGH') # rename levels to get prettier table
 Error in `levels<-.emmGrid`(`*tmp*`, value = list(machine = c("A", "B",  : 
  To modify levels, see help("transform.emmGrid") 
```
Continuing with `transform()`:
```r
> G = transform(G, diameter = c('diameter_LOW','diameter_HIGH'))
> ems = emmeans(G,pairwise ~ diameter | dummy)
> print(ems$contrasts)  # Now results are right
dummy = 1:
 contrast                     estimate   SE df t.ratio p.value
 diameter_LOW - diameter_HIGH    -6.71 1.02  7 -6.594  0.0003 

dummy = 2:
 contrast                     estimate   SE df t.ratio p.value
 diameter_LOW - diameter_HIGH    -6.71 1.02  7 -6.594  0.0003 

dummy = 3:
 contrast                     estimate   SE df t.ratio p.value
 diameter_LOW - diameter_HIGH    -6.71 1.02  7 -6.594  0.0003 

Results are averaged over the levels of: machine
```

**Comment by rvlenth** [comment] 2020-11-01 20:34
Closing this, but you may still comment if you think an issue remains.

**Closed by rvlenth** 2020-11-01 20:34 UTC
Labels: bug

**Comment by rvlenth** [comment] 2020-11-04 20:21
Update -- I have reversed myself on this. My existing code for `update(object, levels = ...)` already served this purpose
reasonably well, so now, `levels<-.emmGrid` just calls that update method and it works fine with your example.

The `transform()` method described above has been removed. It was slightly more flexible, but not enough to justify the existence of similar, but not identical, functionality. I have no choice about keeping `update(levels)` because I'm sure somebody, somewhere uses it. In addition, we already have keywords `trans` and `transform` in other functions, and a `transform` method that doesn't serve similar purposes is confusing and problematic. 

So now we have (for a somewhat more interesting example where `dummy` interacts with `diameter`:
```r
set.seed(1)
fiber$dummy = factor(sample(1:3,nrow(fiber), replace=T)) # random dummy factor
model1 = lm(strength ~ diameter * dummy,data=fiber) 
G = ref_grid(model1,cov.reduce = discretizer,nesting=list())
levels(G)$diameter = c('diameter_LOW','diameter_HIGH') # rename levels to get prettier table
ems = emmeans(G,pairwise ~ diameter | dummy)
summary(ems$contrasts, by = NULL)
```
... and the results are:
```
 contrast                     dummy estimate   SE df t.ratio p.value
 diameter_LOW - diameter_HIGH 1        -8.55 1.17  9 -7.337  <.0001 
 diameter_LOW - diameter_HIGH 2        -6.17 1.04  9 -5.953  0.0002 
 diameter_LOW - diameter_HIGH 3        -9.42 1.72  9 -5.475  0.0004 
```
[In future bug reports, to me or others, may I ask that you not re-use variable names? Having different versions of `G` and `ems` floating around creates confusion. Thanks.]
