### ISSUE TITLE
Additional arguments not passed to methods when used in "interaction"

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#22] opened 2018-03-18 13:17 UTC
I've been trying to create my own method, but have found that arguments cannot be passed when the method is used in an interaction. Here is some sample mock code to demonstrate the issue:

```
# some fake data
df <- data.frame(Y = rnorm(100),
                 F1 = factor(rep(letters[1:4],each = 25)),
                 F2 = factor(rep(letters[5:8],25)))

fit <- aov(Y ~ F1*F2, data = df)

rg <- emmeans(fit, ~F1*F2)

# my method - won't run unless '.second' is set to FALSE
my_method.emmc <- function(x, .second = TRUE){
  vex <- rep(0,length(x))
  if(.second)
    stop("")
  
  vex[1:2] <- c(-1,1)
  
  as.data.frame(vex)
}

# this works
contrast(rg, "my_method",.second = FALSE)

# this does not
contrast(rg, interaction = c("my_method","pairwise"),.second = FALSE)
```

I think this can be fixed by changing ` contrast.emmGrid`, when an interaction in called to include `...`. So from this:
```
object = contrast.emmGrid(object, interaction[i], by = vars[-i], name = nm)
```
to this:
```
object = contrast.emmGrid(object, interaction[i], by = vars[-i], name = nm,...)
```

**Comment by rvlenth** [comment] 2018-03-23 02:02
Thanks for your report.

I believe I had that `...` in the call when I first programmed this, and having put it back in, I remembered why I took it out. With a different example (more convenient for me):
```
> warp.lm <- lm(breaks ~ wool*tension, data = warpbreaks)
> warp.emm <- emmeans(warp.lm, ~ tension | wool)

> contrast(warp.emm, interaction = "consec", by = NULL, reverse = TRUE)
Argument ‘reverse’ was ignored. Valid choices are:
adjust, alpha, avgd.over, by.vars, delta, df, initMesg, estName, estType, famSize, infer, inv.lbl, level, methDesc, nesting, null, predict.type, pri.vars, side, tran, tran.mult, tran2, type, is.new.rg, model.info, roles, grid, levels, matlevs, linfct, bhat, nbasis, V, dffun, dfargs, misc, post.beta
 tension_consec wool_consec  estimate       SE df t.ratio p.value
 L - M          A - B        21.11111 7.293523 48   2.895  0.0057
 M - H          A - B       -10.55556 7.293523 48  -1.447  0.1543

> contrast(warp.emm, interaction = "consec", by = NULL, reverse = FALSE)
Argument ‘reverse’ was ignored. Valid choices are:
adjust, alpha, avgd.over, by.vars, delta, df, initMesg, estName, estType, famSize, infer, inv.lbl, level, methDesc, nesting, null, predict.type, pri.vars, side, tran, tran.mult, tran2, type, is.new.rg, model.info, roles, grid, levels, matlevs, linfct, bhat, nbasis, V, dffun, dfargs, misc, post.beta
 tension_consec wool_consec  estimate       SE df t.ratio p.value
 M - L          B - A        21.11111 7.293523 48   2.895  0.0057
 H - M          B - A       -10.55556 7.293523 48  -1.447  0.1543
```
As you see, the levels for both factors are indeed reversed, indicating that the `reverse` was passed to `consec.emmc`, but we get an annoying warning message from the `update` call. The problem is that `...` is used for two purposes here.

I decided though that it is more important to support optional arguments for contrast functions than it is to warn people about invalid `update` parameters (which are just ignored anyway). So I set my secret `silent = TRUE` argument later on in the code and that suppresses the warnings. 
```
> contrast(warp.emm, interaction = "consec", by = NULL, reverse = TRUE)
 tension_consec wool_consec  estimate       SE df t.ratio p.value
 L - M          A - B        21.11111 7.293523 48   2.895  0.0057
 M - H          A - B       -10.55556 7.293523 48  -1.447  0.1543
```
This fix will be in the next push to github, and in the next update to CRAN (which I plan to submit in a week or two).

**Comment by rvlenth** [comment] 2018-04-02 18:53
Closing as I think it is addressed in CRAN version 1.1.3. But let me know if there are more concerns.

**Closed by rvlenth** 2018-04-02 18:53 UTC
Labels: bug

**Comment by mattansb** [comment] 2018-04-03 09:21
A minor hiccup - while this does now work (for my first example):
```
contrast(rg, interaction = c("my_method","pairwise"),.second = FALSE)
```
It seems that using methods with additional arguments does not work together with the following methods:  
- `poly`
- `trt.vs.ctrl` (and thus also `trt.vs.ctrl1`, `trt.vs.ctrlk`, and  `dunnett`)
- `tukey`

So these do not work:
```
contrast(rg, interaction = c("my_method","poly"),.second = FALSE)
contrast(rg, interaction = c("my_method","trt.vs.ctrl"),.second = FALSE)
contrast(rg, interaction = c("my_method","tukey"),.second = FALSE)
```

This can be solved easily by adding a `...` input argument to these functions.

Thanks again!

**Comment by rvlenth** [comment] 2018-04-06 15:59
Thanks, you're right and I will do the repairs.

**Comment by mattansb** [comment] 2018-04-06 18:59
Awesome! Thanks Russell!
