### ISSUE TITLE
[FC] support of logistf

### ISSUE THREAD

**Issue by andreasleha** [rvlenth/emmeans#395] opened 2023-01-11 13:10 UTC
I'd like to propose firth corrected models as fit with logistf::logistf() to be added to the (already very extensive) list of supported models.

**Comment by rvlenth** [comment] 2023-01-11 18:23
On the surface of it, it looks like it's pretty easy to use emmeans with these objects via the `qdrg()` function.
Using the first example provided in the help for `logistf()`,
```
require(emmeans)
require(logistf)

> (rg = qdrg(object=fit, data=sex2, link="logit"))
'emmGrid' object with variables:
    age = 0, 1
    oc = 0, 1
    vic = 0, 1
    vicl = 0, 1
    vis = 0, 1
    dia = 0, 1
Transformation: “logit” 

> emmeans(rg, ~age|oc, type = "resp")
oc = 0:
 age response    SE  df asymp.LCL asymp.UCL
   0    0.795 0.129 Inf     0.451     0.948
   1    0.561 0.204 Inf     0.202     0.866

oc = 1:
 age response    SE  df asymp.LCL asymp.UCL
   0    0.783 0.133 Inf     0.437     0.944
   1    0.544 0.204 Inf     0.192     0.857

Results are averaged over the levels of: vic, vicl, vis, dia 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale
```
I am not sure if "logit" is the correct link, however, as I haven't even skimmed the documentation.

It is best to try to get package developers to include **emmeans** support in their packages, as they know the finer details of their models. I will try to encourage the developer to do this and will try to help.

**Comment by andreasleha** [comment] 2023-01-12 08:20
Great!  Thanks a lot for the swift reaction and the offer to work with the logistf author on this!

**Comment by ikosmidis** [comment] 2023-01-31 14:06
I landed at this issue through a very unusual path. While it is worthwhile extending **logistf** to support **emmeans**, I may have a suggestion using one of my packages.

You can use the `brglm_fit` method from the [brglm2](https://cran.r-project.org/package=brglm2) R package, which provides the Firth bias reduction method by default for logistic regression. See `?brglm_fit` for examples. 

I have not studied the internals of **emmeans**, but the objects from the `brglm_fit` method inherit directly from `glm` and `lm` so the methods should work out of the box. @rvlenth, if I missed anything, happy to consider suggestions, and I will add this in the next **brglm2** update that I am preparing for submission one of these days.

**Comment by rvlenth** [comment] 2023-01-31 18:54
I don't think you need to do anything! Because, as you say, your model objects inherit from `glm`, so it just works:
```
> library(brglm2)
> data("lizards")
> lizardsBR_mean <- glm(cbind(grahami, opalinus) ~ height + diameter +
+                           light + time, family = binomial(logit), data = lizards,
+                       method = "brglmFit")
> 

> emmeans(lizardsBR_mean, ~ height * diameter | light, type = "response")
light = sunny:
 height diameter  prob     SE  df asymp.LCL asymp.UCL
 <5ft   <=2in    0.850 0.0397 Inf     0.755     0.913
 >=5ft  <=2in    0.945 0.0188 Inf     0.894     0.972
 <5ft   >2in     0.727 0.0619 Inf     0.591     0.831
 >=5ft  >2in     0.890 0.0367 Inf     0.795     0.944

light = shady:
 height diameter  prob     SE  df asymp.LCL asymp.UCL
 <5ft   <=2in    0.715 0.0349 Inf     0.642     0.778
 >=5ft  <=2in    0.883 0.0251 Inf     0.825     0.924
 <5ft   >2in     0.541 0.0429 Inf     0.457     0.623
 >=5ft  >2in     0.781 0.0449 Inf     0.681     0.856

Results are averaged over the levels of: time 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
```
It uses the estimates from the model and results of `vcov(model)`. You can specify a different vcov matrix or function via the `vcov.` argument. 

The reason you might want to add **emmeans** support to your package is if you want to add, say, a `mode` argument to select certain options or features of your models. The ["xtending" vignette](https://cran.r-project.org/web/packages/emmeans/vignettes/xtending.html) tries to explain how to do this. You need to provide S3 methods `recover_data.brglmFit` and `emm_basis.brglmFit`, and register them. The former is for recovering the dataset, and is usually pretty trivial. The latter is akin to `predict.brglmFit(model, newdata = ...)`

**Comment by rvlenth** [comment] 2023-02-11 18:04
Gonna close this issue, ans we are resolved or at leaST AT A HIATUS

**Closed by rvlenth** 2023-02-11 18:04 UTC
Labels: question

**Comment by rvlenth** [comment] 2023-03-15 22:29
Support has been added to the **logistf** package, and it seems to be working well. See more at https://github.com/georgheinze/logistf/issues/51

**Comment by andreasleha** [comment] 2023-03-16 07:21
Great!  Thanks a lot for your efforts!
