### ISSUE TITLE
emmeans issues with weights argument in lme

### ISSUE THREAD

**Issue by wbarr08** [rvlenth/emmeans#75] opened 2019-01-10 15:13 UTC
The emmeans function don´t works in lme objects with weights argument.  When the argument for allow diferent variance is active, the function emmeans show the next error:
Error in model.frame.default(data = frigo, weights = c(`1` = 1, `1` = 1,  : 
  variable lengths differ (found for '(weights)')
Error in ref_grid(object, ...) : 
  Perhaps a 'data' or 'params' argument is needed

**Comment by rvlenth** [comment] 2019-01-12 19:11
I am unable to reproduce this error. I tried:
```
> library(nlme)
> library(emmeans)

> ### Without weights:
> fm = lme(distance ~ age + Sex, data = Orthodont, random = ~ 1|Subject)
> ref_grid(fm)
'emmGrid' object with variables:
    age = 11
    Sex = Male, Female
> emmeans(fm, "Sex")
 Sex    emmean    SE df lower.CL upper.CL
 Male     25.0 0.486 25     24.0     26.0
 Female   22.6 0.586 25     21.4     23.9

> ### With weights:
> fmw = lme(distance ~ age + Sex, data = Orthodont, random = ~ 1|Subject, weights = ~ age)
> ref_grid(fmw)
'emmGrid' object with variables:
    age = 11
    Sex = Male, Female
> emmeans(fmw, "Sex")
 Sex    emmean    SE df lower.CL upper.CL
 Male     24.9 0.485 25     23.9     25.9
 Female   22.7 0.584 25     21.5     23.9

Degrees-of-freedom method: containment 
Confidence level used: 0.95
```
Do you have a reproducible example, preferably using a dataset that comes with R or the **nlme** package? Give the actual model-fitting call, and any error/warning messages. I suspect that it may have to do with weights that come out zero or some error condition that occurred.

It may also help to look at the actual numerical weights it used:
```
varWeights(fm$modelStruct)
```
where you replace `fm` with the name you gave to your fitted model

**Comment by wbarr08** [comment] 2019-01-13 13:46
Dear Professor. I could figure out how fix the problem. The problem happen when I try to handle a lme object that come from analysis with the "na.action=na.omit" option. 
I removed the missing data from data frame in matrix way and could do the analysis without na.action option. In this case, the emmeans it worked correctly.

To will reproduce the problem, need a response variable with missing data, the na.action function in lme and the varIdent(form=~1|x) form in weights option.

Thanks you so much for you interest and response to my question.

Regards,

Wilson

**Comment by rvlenth** [comment] 2019-01-14 17:18
I'm willing to work on resolving the bug, but I'd rather not also have to work to create an example. May I request that you create a complete example where the problem occurs? For instance, some R code that would modify an existing R dataset, and show the model-fitting call and `emmeans()` call that errors out. Thanks.

**Comment by wbarr08** [comment] 2019-01-15 11:37
Dear Professor. Here an example from a library MASS dataset. 

```
 #Data from MASS. This dataset haven't  missing values
 library(MASS)
 data(Oats)
 #Introducing some missing value
 Oats[17,4]<-NA
 #Make a ficticial variance heterogeneity in dataset
 Oats[c(1:8), 4]<-c(150, 160, 100, 50, 166, 55, 179, 51 )
 #run model with a na.action option for avoid a missing value
 m1<- lme(yield ~ Variety * factor(nitro), random =~ 1|Block, data =Oats, 
na.action = na.omit)
 #Check the variance heterogeneity in Block factor
 plot(m1)
 plot(residuals(m1, type="pearson")~ Oats[-17,]$Variety)
 plot(residuals(m1, type="pearson")~ Oats[-17,]$Block)
 #improve variance heterogeneity with the specification of varIdent in 
 #weights option.
 m2<- lme(yield ~ Variety*factor(nitro), random=~1|Block, data =Oats,
         weights = varComb(varIdent(form =~  1|Variety),
                            varIdent(form =~ 1|Block)),  na.action = na.omit)
 #Check variance heterogeneity solutions 
 plot(m2)
 plot(residuals(m2, type="pearson")~ Oats[-17,]$Variety)
 plot(residuals(m2, type="pearson")~ Oats[-17,]$Block)
 #Run emmeans for model with na.action in model
 emmeans(m2, "Variety")
Error in model.frame.default(data = Oats, weights = c(1, 1, 1, 1, 0.829667906044738,  : 
  variable lengths differ (found for '(weights)')
Error in ref_grid(object, ...) : 
  Perhaps a 'data' or 'params' argument is needed
 #Solve the problem. Take out the na.action option and remove the missing
 #value from dataset in the matrix way
 m2.1<- lme(yield ~ Variety*factor(nitro), random=~1|Block, data =Oats[-17,],
          weights = varComb(varIdent(form = ~1|Variety),
                            varIdent(form= ~1|Block)))
 #run a emmeans in model without na.action
 emmeans(m2.1, "Variety")
NOTE: Results may be misleading due to involvement in interactions
 Variety        emmean       SE df lower.CL upper.CL
 Golden Rain 100.46245 4.667269  5 88.46485 112.4600
 Marvellous  106.60568 3.801747  5 96.83298 116.3784
 Victory      89.48636 3.997904  5 79.20942  99.7633
Results are averaged over the levels of: nitro 
Degrees-of-freedom method: containment 
Confidence level used: 0.95 

```

**Comment by rvlenth** [comment] 2019-02-16 15:10
I think this is resolved, so I am closing the issue

**Closed by rvlenth** 2019-02-16 15:10 UTC
