### ISSUE TITLE
Different results for predicted probability from emmeans over time

### ISSUE THREAD

**Issue by elizabethwe** [rvlenth/emmeans#226] opened 2020-09-20 22:45 UTC
Hello,

I noticed that the values in a predicted probability change considerably from an older to newer package version. All other values (OR, z, p) are the same. Can you tell me if this was intentional, and if so what the difference is in the function?

Version 1.4
<img width="829" alt="Screen Shot 2020-09-20 at 12 39 57 PM" src="https://user-images.githubusercontent.com/43682276/93723921-76ecdc80-fb3e-11ea-8c1b-4f14db747c3e.png">

Version 1.5.1
<img width="793" alt="Screen Shot 2020-09-20 at 12 44 53 PM" src="https://user-images.githubusercontent.com/43682276/93724001-1e6a0f00-fb3f-11ea-960d-4c3feca689a4.png">

**Comment by rvlenth** [comment] 2020-09-21 00:32
From what I can tell, it's because they are different fitted models -- `model2` v.s. `model2a` .  If they are in fact identical models, then yes there is an issue but there is noway I would be able to identify what the problem is without a reproducible answer. This is especially true because the `kable` processing hides whatever summary.emmGrid annotations that would have otherwise been shown.

Sent from my iPad

On Sep 20, 2020, at 5:45 PM, elizabethwe <notifications@github.com> wrote:

﻿

Hello,

I noticed that the values in a predicted probability change considerably from an older to newer package version. All other values (OR, z, p) are the same. Can you tell me if this was intentional, and if so what the difference is in the function?

Version 1.4
[Screen Shot 2020-09-20 at 12 39 57 PM]<https://user-images.githubusercontent.com/43682276/93723921-76ecdc80-fb3e-11ea-8c1b-4f14db747c3e.png>

Version 1.5.1
[Screen Shot 2020-09-20 at 12 44 53 PM]<https://user-images.githubusercontent.com/43682276/93724001-1e6a0f00-fb3f-11ea-960d-4c3feca689a4.png>

**Comment by elizabethwe** [comment] 2020-09-21 00:47
Ah yeah that could look like the reason but its not - would take longer to
explain why than its worth. Can I send you a short .rmd and a short csv
with data to reproduce the problem?

**Comment by rvlenth** [comment] 2020-09-21 01:06
yes

Sent from my iPad

On Sep 20, 2020, at 7:48 PM, elizabethwe <notifications@github.com> wrote:

﻿

Ah yeah that could look like the reason but its not - would take longer to
explain why than its worth. Can I send you a short .rmd and a short csv
with data to reproduce the problem?

**Comment by rvlenth** [comment] 2020-09-21 01:08
simplest thing might be to put it in Dropbox ir similar, and obtain a link for it. Or you can find my email at dept of statistics, U of Iowa.

Sent from my iPad

On Sep 20, 2020, at 7:48 PM, elizabethwe <notifications@github.com> wrote:

﻿

Ah yeah that could look like the reason but its not - would take longer to
explain why than its worth. Can I send you a short .rmd and a short csv
with data to reproduce the problem?

**Comment by elizabethwe** [comment] 2020-09-21 01:30
Here you go -

As you'll see (and I commented) the problem emerges when the model includes
covariates - so for model 1 there is no issue, but with models 2 and 3
there are different results. I knit 2 html files so you can see...

Please delete the data when you're done
Thank you!

Elizabeth

**Comment by rvlenth** [comment] 2020-09-21 02:27
Haven't tested this yet. HOWEVER, mentioning the covariate jogs a memory. Perchance does the covariate have only two different values? Note this excerpt fromthe NEWS file for version 1.4.2:


  *   New cov.keep argument in ref_grid() for specifying covariates to be treated just like factors (#148). A side effect is that the system default for indicator variables as covariates is to treat them like 2-level factors. This could change the results obtained from some analyses using earlier versions. To replicate old analyses, set emm_options(cov.keep = character(0)).

My suspicion is that's the issue. I bet if you try what it says at the end there and rerun the analyses with version 1.5.1, you'll get the same results as 1.4

Russ

Sent from my iPad

On Sep 20, 2020, at 8:30 PM, elizabethwe <notifications@github.com> wrote:

﻿

Here you go -

As you'll see (and I commented) the problem emerges when the model includes
covariates - so for model 1 there is no issue, but with models 2 and 3
there are different results. I knit 2 html files so you can see...

Please delete the data when you're done
Thank you!

Elizabeth

**Comment by rvlenth** [comment] 2020-09-21 17:39
It is as I suspected... Looking at your `model3`, we have:
```r
> rg1 = ref_grid(model3)
'emmGrid' object with variables:
    cond_f = control, intv, letter
    months_after_jjc = 7.0916
    s0.personality_c3 = 4.475
    gender_nonmale = 0, 1
    age_intv = 15.936
    s0.demo_edu_mom = 2.325
Transformation: “logit” 
```
Note that for most of the covariates, we use their average value; but for `gender_nomale`, we use both its levels due to a change in version 1.4.2. So then:
```r
> emmeans(rg1, "cond_f", type = "response")
 cond_f    prob     SE  df asymp.LCL asymp.UCL
 control 0.5451 0.2080 Inf   0.18799     0.861
 intv    0.3750 0.2523 Inf   0.06781     0.832
 letter  0.0384 0.0458 Inf   0.00351     0.312

Results are averaged over the levels of: gender_nonmale 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
```
Note the annotation "Results are averaged over the levels of: gender_nonmale" -- this is the clue, indicating that we averaged the predictions for `gender_nonmale = 0` and `gender_nonmale = 1`, by default with equal weights.

The old behavior pre-1.4.2 was to reduce *all* covariates to their means. This is still possible via the `cov.keep` argument:
```r
> rg2 = ref_grid(model3, cov.keep = character(0))
'emmGrid' object with variables:
    cond_f = control, intv, letter
    months_after_jjc = 7.0916
    s0.personality_c3 = 4.475
    gender_nonmale = 0.1
    age_intv = 15.936
    s0.demo_edu_mom = 2.325
Transformation: “logit” 

> emmeans(rg2, "cond_f", type = "response")
 cond_f   prob    SE  df asymp.LCL asymp.UCL
 control 0.822 0.114 Inf    0.5010     0.955
 intv    0.698 0.169 Inf    0.3242     0.917
 letter  0.133 0.101 Inf    0.0268     0.462

Confidence level used: 0.95 
Intervals are back-transformed from the logit scale
```
These are the results you had with the old version. Note that `gender_nonmale` is held at its mean of 0.1, and there is no annotation about averaging over its levels.

By the way, another way to get these results is to weight proportionally rather than equally. With the first reference grid:
```r
> emmeans(rg1, "cond_f", type = "response", weights = "prop")
 cond_f   prob    SE  df asymp.LCL asymp.UCL
 control 0.822 0.114 Inf    0.5010     0.955
 intv    0.698 0.169 Inf    0.3242     0.917
 letter  0.133 0.101 Inf    0.0268     0.462

Results are averaged over the levels of: gender_nonmale 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale
```

The reason for this change is that I was getting a lot of questions from people who fit a model with indicators and then wondering why they don't get separate estimates. So I realized that most of the time when people have a covariate with just 2 values, they usually want it treated like a factor. Until a couple of updates ago, I had a startup message about that change, but removed it after it'd been going about a year.

**Comment by rvlenth** [comment] 2020-09-21 18:43
Per your request, I have deleted the data from my PC. I'll leave it to you to close this if the issue is resolved for you, at which time I will also delete the attachments from the email you sent.

**Comment by elizabethwe** [comment] 2020-09-22 03:06
Hi Russell,

Thank you so much, this is really helpful. While I have you - I was
wondering if there is a link to the equation that is used to generate these
probabilities?
In my effort to troubleshoot, I made one, but I found that it only worked
when there were no covariates in the model. When there were, the
probability estimate always becomes 1. I'm assuming covariates need to be
accounted for with the logit coefficient *b*?

Best,
Elizabeth

**Comment by rvlenth** [comment] 2020-09-22 14:27
I'm not sure I understand the question. It's all based on the model predictions. If you do, say,
```r
rg1@grid   # reference grid for model3
pred = predict(model3, newdata = rg1@grid)
exp(pred) / (1 + exp(pred))
```
`pred` are predictions on the logit scale for the reference grid, and we back-transform those.

**Closed** 2020-09-28 23:41 UTC
Labels: question
