### ISSUE TITLE
Credible intervals of contrasts from brm not consistent when reverse set to TRUE

### ISSUE THREAD

**Issue by qdread** [rvlenth/emmeans#315] opened 2021-11-24 21:00 UTC
First off, Russ I really appreciate your excellent package!

I'm not sure if this is an issue with the emmeans package, or brms, or just my poor understanding of contrasts.

The `contrast` function argument `reverse` can be set to `TRUE` to flip around the default ordering of the pairwise contrasts. My understanding is that this is just a cosmetic difference. However, when I fit a model with `brms::brm()` and calculate the contrasts (in this case odds ratios back-transformed from the log OR scale) both with default and reverse ordering, the HPD intervals do not coincide. The median estimate for the reverse order is equal to 1/the default estimate. But the HPD intervals are not consistent -- I noticed this in one case where both sides of the 95% HPD for a contrast were less than 1, but the corresponding reversed contrast did not have both sides of the 95% HPD greater than 1. I was curious, like I said above, where the issue is coming from, or if it is just my lack of understanding.

Below is my reproducible example where I fit a model and do the contrasts in default and reversed order.

```
library(brms)
library(emmeans)

dat <- 
  structure(list(Year = c(2019, 2019, 2019, 2019, 2019, 2019, 2019, 
                          2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 
                          2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2020, 2020, 
                          2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 
                          2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 
                          2020, 2020, 2020), 
                 Rep = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 
                                   1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 
                                   3L, 3L, 3L, 3L, 3L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 
                                   2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L
                 ), .Label = c("1", "2", "3"), class = "factor"), 
                 Line = structure(c(8L, 
                                    9L, 4L, 3L, 7L, 1L, 5L, 6L, 2L, 5L, 8L, 7L, 6L, 9L, 2L, 4L, 3L, 
                                    1L, 7L, 4L, 2L, 8L, 6L, 3L, 5L, 1L, 9L, 2L, 3L, 6L, 5L, 7L, 1L, 
                                    4L, 9L, 8L, 3L, 9L, 7L, 8L, 4L, 5L, 6L, 2L, 1L, 7L, 4L, 6L, 1L, 
                                    3L, 5L, 9L, 2L, 8L), .Label = c("1", "2", "3", "4", "5", "6", 
                                                                    "7", "8", "9"), class = "factor"), 
                 Lodging = c(0.12, 0.02, 0.05, 
                             0, 0.1, 0.08, 0, 0.25, 0.12, 0, 0.2, 0.3, 0.45, 0.02, 0.02, 0.05, 
                             0.03, 0.15, 0.05, 0.06, 0.05, 0.1, 0.3, 0, 0, 0.15, 0.05, 0.95, 
                             0.952380952380952, 1, 0.24, 1, 0.28, 1, 0.76, 0.92, 0, 1, 0.76, 
                             0.6, 0.68, 0.8, 0.92, 0.92, 0.96, 0.76, 0.28, 0.88, 1, 0.68, 
                             0.32, 0.84, 0.72, 0.76)), row.names = c(NA, -54L), class = "data.frame")

options(mc.cores = 4)

fit <- brm(Lodging ~ Year + Line + (1|Rep/Year), data = dat, family = zero_one_inflated_beta, 
           chains = 4, iter = 5000, warmup = 4000, seed = 606,
           prior = prior('student_t(3, 0, 100)', class = 'Intercept'),
           backend = 'cmdstanr')

line_means <- emmeans(fit, ~ Line, type = 'response')

line_contr <- contrast(line_means, 'tukey')
line_contr_rev <- contrast(line_means, 'tukey', reverse = TRUE)

# Show the specific contrast that seems inconsistent.
line_contr_df <- as.data.frame(line_contr)
line_contr_rev_df <- as.data.frame(line_contr_rev)

line_contr_df[line_contr_df$contrast == '4 / 8', ]
line_contr_rev_df[line_contr_rev_df$contrast == '8 / 4', ]
```

Output of the final two lines:

```
> line_contr_df[line_contr_df$contrast == '4 / 8', ]
   contrast odds.ratio  lower.HPD upper.HPD
25    4 / 8  0.3262281 0.06052075 0.8727396
> line_contr_rev_df[line_contr_rev_df$contrast == '8 / 4', ]
   contrast odds.ratio lower.HPD upper.HPD
25    8 / 4    3.06534 0.6808781  8.497483
```

**Comment by rvlenth** [comment] 2021-11-24 22:41
Interesting question -- which, luckily, I am able to answer. The HPD intervals are computed using the `coda::HPDinterval()` function. Rather than your example, I'll concentrate on a single sample which you can reproduce:

```
> set.seed(123)
> y = exp(rnorm(1000, mean = 1, sd = 2))

> ### for y ...
> HPDinterval(mcmc(y), .95)
           lower    upper
var1 0.009857237 78.95447
attr(,"Probability")
[1] 0.95

> 1 / .Last.value
        lower      upper
var1 101.4483 0.01266553
attr(,"Probability")
[1] 0.95

> ### for 1/y ...
> HPDinterval(mcmc(1/y), .95)
            lower    upper
var1 0.0005630851 9.706139
attr(,"Probability")
[1] 0.95
```
Note that the same phenomenon you observed happens here: you see that the reciprocals of the first interval are very different from the second interval.

The reason is that HPD intervals are *not* based on quantiles, but rather on finding the shortest interval that has the specified probability. Here is what we get if we just cut off .025 from each tail:
```
> quantile(y, c(.025, .975))
        2.5%        97.5% 
  0.05596054 160.09722082 

> 1 / .Last.value
        2.5%        97.5% 
17.869735956  0.006246205 

> quantile(1/y, c(.025, .975))
      2.5%      97.5% 
 0.0062463 17.8697396 
```
Here we see that the intervals indeed are inverses of one another. But these intervals are a lot wider than the HPD intervals. And also note that we can get pretty close to the first HPD interval via a very asymmertical 95% quantile interval:
```
> quantile(y, c(.001, .951))
       0.1%       95.1% 
 0.01327194 78.97895423 
```

**Comment by qdread** [comment] 2021-11-26 13:25
Thank you, this is very helpful to understand the problem from a mathematical standpoint. I can see why 1 over the limits of the HPD interval for y is not the same as the limits of the HPD interval of 1/y. But I am having trouble wrapping my head around the consequences for inference. In my example above, it's arbitrary whether we look at the odds ratio of line 8/line 4 or line 4/line 8. If I understand it correctly, the interpretation of the 95% credible interval as defined by the HPD interval is that we can be 95% sure that the parameter value lies in that interval. But how do we interpret it if 1 is in the interval in one case but not the other?

**Comment by rvlenth** [comment] 2021-11-26 19:16
Interesting question, and it might attract some good discussion if you want to post it on [CrossValidated](https://stats.stackexchange.com/) or some such. But a few things I could mention:

  * It is not unusual for skewed distributions create difficulties in statistical inference.
  * There is often not one "right answer" in statistics
  * If you look at what `emmeans` often does in frequentist analyses with `type = "response"`, you'll typically see an annotation such as "tests are performed on the <link> scale."

And that latter point is a useful suggestion, I think. If you take logs of those ratios, you get differences of the logs; and even if the distribution is skewed after taking logs, we still have that the logs of the reciprocals are the negatives of the logs of the ratios. Thus, by analyzing logs of ratios, you actually *guarantee* that you won't run into this problem, because HPD limits when the differences are taken in one direction will be the negatives of the HPD limits if you do them the other way.

So for inference purposes, my suggestion is to use `type = "link"`. I would have demo'd this with your example, but I can't install the **cmdstanr** package for some reason.

**Comment by rvlenth** [comment] 2021-11-26 19:26
Ah -- I just took out the `backend` argument:
```
> EMM <- emmeans(fit, ~ Line, type = 'response', at = list(Line = c("4", "8")))
> EMM
 Line response lower.HPD upper.HPD
 4       0.218    0.0518     0.424
 8       0.459    0.2119     0.714

Point estimate displayed: median 
Results are back-transformed from the logit scale 
HPD interval probability: 0.95 
> pairs(EMM)
 contrast odds.ratio lower.HPD upper.HPD
 4 / 8          0.32    0.0685     0.801

Point estimate displayed: median 
Results are back-transformed from the log odds ratio scale 
HPD interval probability: 0.95 
> pairs(EMM, rev = TRUE)
 contrast odds.ratio lower.HPD upper.HPD
 8 / 4          3.12     0.657      8.08

Point estimate displayed: median 
Results are back-transformed from the log odds ratio scale 
HPD interval probability: 0.95 
```
Similar to what you had.

Now try on the link scale:
```
> pairs(EMM, type = "link")
 contrast estimate lower.HPD upper.HPD
 4 - 8       -1.14     -2.24   -0.0554

Point estimate displayed: median 
Results are given on the log odds ratio (not the response) scale. 
HPD interval probability: 0.95 
> pairs(EMM, rev = TRUE, type = "link")
 contrast estimate lower.HPD upper.HPD
 8 - 4        1.14    0.0554      2.24

Point estimate displayed: median 
Results are given on the log odds ratio (not the response) scale. 
HPD interval probability: 0.95 
```
As promised, these are consistent; and the intervals don't contain zero.

**Comment by rvlenth** [comment] 2021-11-27 16:04
I think this is resolved, I'll close this. That does not keep you from commenting if you have more to ask/say.

**Closed by rvlenth** 2021-11-27 16:04 UTC
Labels: question
