### ISSUE TITLE
Memory problems with large data and complex GLM models

### ISSUE THREAD

**Issue by MillaSalonen** [rvlenth/emmeans#282] opened 2021-07-07 06:34 UTC
Dear Russell, thank you for the great package! I've been using it a lot, but now I've faced a problem with my latest analyses. I have a relatively large data (n=11400) and a lot of variables. When I try to use emmeans, I either get the error "Error: vector memory exhausted (limit reached?)" or it just takes a long time (several hours) to run.

I've tested emmeans 1.6.1 as well as 1.4.3 and 1.4.1, which have previously worked great. I've also tried to call ref_grid but have gotten the same error.

Here is an example dataset resembling my data. Unfortunately I failed to replicate the error with this simulated dataset, but getting the emmGrid object took overnight, so it partially replicates my issues.

```
set.seed(1)
n <- 11500
cat <- paste("a",1:50,sep="")

df <- data.frame(
  y = rgamma(n, shape=4),
  a = sample(letters[1:2], n, replace = TRUE),
  b = sample(letters[1:2], n, replace = TRUE),
  c = sample(letters[1:2], n, replace = TRUE),
  d = sample(letters[1:2], n, replace = TRUE),
  e = sample(letters[1:2], n, replace = TRUE),
  f = sample(letters[1:2], n, replace = TRUE),
  g = sample(letters[1:2], n, replace = TRUE),
  h = sample(letters[1:2], n, replace = TRUE),
  i = sample(letters[1:5], n, replace = TRUE),
  j = sample(letters[1:4], n, replace = TRUE),
  k = sample(letters[1:3], n, replace = TRUE),
  l = sample(letters[1:5], n, replace = TRUE),
  m = sample(letters[1:4], n, replace = TRUE),
  n = sample(letters[1:3], n, replace = TRUE),
  o = rgamma(n, shape=1),
  p = sample(cat, n, replace = TRUE)
)

model <- glm(y~a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+a*b, data=df, family=Gamma(link="log"))
emm.p <- emmeans(model,"p",type="response")
```

Thank you in advance!

**Comment by rvlenth** [comment] 2021-07-07 15:15
Hello,

Rather than try to run your example, I will look ahead to what it requires.

First, the reference grid consists of all combinations of the factors in the model. There are 16 factors (including the one numerical covariate 'o') The number of such combinations is
    2*8 * 3^2 * 4^2 * 5^2 * 1 * 50 = 2,880,000
The number of regression coefficients is
    1 + 8*1 + 2*(2 + 3 + 4) + 1 + 49 = 77
So the 'linfct' slot in the reference grid is a 2,880,000 x 77 matrix, and the 'grid' slot is a data.frame with 2,880,000 rows and 16 columns. I believe each element of these structures requires 8 bytes of storage, so together these two slots require 2880000*(77+16)*8 = 2,142,720,000 bytes, or over 2 GB. Then there are other slots such as 'V', a 77x77 matrix, and your workspace also contains the dataset, model object, and probably several other things.

So, the issue isn't really so much the number of observations as the number of predictors. I suspect the huge time requirements you get when it doesn't error-out are consumed by your computer's paging portions of memory on and off the hard disk, and R's garbage-collect operations.

So my suggestion is to fit a model with fewer factors. Even removing one two-level factor cuts the memory requirements in half. But I suggest more paring-down than that. I see people trying to account for everything but the kitchen sink by throwing them into the model, and that might make some technical sense, but it also lessens the likelihood that anyone would ever be able to replicate your results. I note that your model is mostly additive; I don't know what these factors really are but I'd be surprised if there aren't some important interactions among them. Decide which predictors are really substantively important. You might well be better off with a model that has fewer factors and more interactions.

Russ

From: MillaSalonen ***@***.***>
Sent: Wednesday, July 7, 2021 1:35 AM
To: rvlenth/emmeans ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [rvlenth/emmeans] Memory problems with large data and complex GLM models (#282)


Dear Russell, thank you for the great package! I've been using it a lot, but now I've faced a problem with my latest analyses. I have a relatively large data (n=11400) and a lot of variables. When I try to use emmeans, I either get the error "Error: vector memory exhausted (limit reached?)" or it just takes a long time (several hours) to run.

I've tested emmeans 1.6.1 as well as 1.4.3 and 1.4.1, which have previously worked great. I've also tried to call ref_grid but have gotten the same error.

Here is an example dataset resembling my data. Unfortunately I failed to replicate the error with this simulated dataset, but getting the emmGrid object took overnight, so it partially replicates my issues.

set.seed(1)

n <- 11500

cat <- paste("a",1:50,sep="")



df <- data.frame(

  y = rgamma(n, shape=4),

  a = sample(letters[1:2], n, replace = TRUE),

  b = sample(letters[1:2], n, replace = TRUE),

  c = sample(letters[1:2], n, replace = TRUE),

  d = sample(letters[1:2], n, replace = TRUE),

  e = sample(letters[1:2], n, replace = TRUE),

  f = sample(letters[1:2], n, replace = TRUE),

  g = sample(letters[1:2], n, replace = TRUE),

  h = sample(letters[1:2], n, replace = TRUE),

  i = sample(letters[1:5], n, replace = TRUE),

  j = sample(letters[1:4], n, replace = TRUE),

  k = sample(letters[1:3], n, replace = TRUE),

  l = sample(letters[1:5], n, replace = TRUE),

  m = sample(letters[1:4], n, replace = TRUE),

  n = sample(letters[1:3], n, replace = TRUE),

  o = rgamma(n, shape=1),

  p = sample(cat, n, replace = TRUE)

)



model <- glm(y~a+b+c+d+e+f+g+h+i+j+k+l+m+n+o+p+a*b, data=df, family=Gamma(link="log"))

emm.p <- emmeans(model,"p",type="response")

Thank you in advance!

**Comment by MillaSalonen** [comment] 2021-07-08 13:41
Thank you for the quick response!

Good that the package is working as intended, although it's bad news for me. Unfortunately I have very complex response variables (behavior traits) and this was the combination of variables I got after utilizing stringent model selection. But I'll think about what variables I could remove and try again.

Thanks again!

**Comment by rvlenth** [comment] 2021-07-08 16:09
I think you mean your behavior traits are *independent* variables; I hope you can find a workaround. Here is an idea:
```r
base.mod <- glm(y~<several nuisance variables>, data=df, family=Gamma(link="log"))
df$base.pred <- predict(base.mod)
model2 <- glm(y ~ <interesting predictors> + offset(base.pred), data=df, family=Gamma(link="log"))
model2$df.residual <- <original model's df.residual>
```
This isn't exactly the same  model, but it's close, and we have included appropriate adjustments for nuisance variable. The last statement is a hack to account for the fact that model2 doesn't include the d.f. in the base model.

**Comment by rvlenth** [comment] 2021-07-16 20:16
I think this is resolved, or at least answered. So will close this issue. But it is still possible to comment if any concerns arise. 

I'd still be curious if my final suggestion was helpful. BTW, if `predict(mode)l` and `predict(model2)` differ substantially, that would indicate that `<interesting predictors>` interact with predictors in `base.mod`.

**Closed by rvlenth** 2021-07-16 20:16 UTC

**Comment by MillaSalonen** [comment] 2021-07-23 07:46
Dear Russell, sorry for the late response!

We are studying how environmental and demographic variables associate with behaviors and so behavior traits are indeed response variables (I have several separate analyses). Because these traits are highly complex, many variables influence them with a small effect, but I wasn't expecting this many variables.

You're idea of fitting a base model first was a great idea. Unfortunately these analyses are also pretty exploratory, so we don't have nuisance variables we could fit first. I will reduce the number of variables and refit the models.

Again, thanks a lot for your help!

**Comment by rvlenth** [comment] 2021-09-16 18:53
Just a follow-up on this issue. I received another report in #292 that you may want to look at for details. I have figured out a way to deal with large numbers of nuisance factors via a 'nuisance' argument (or 'non.nuis') by which the specified factors are pre-averaged as the reference grid is constructed. 

With your example, we can now use: 
```r
> emm.p <- emmeans(model,"p",type="response", non.nuis = "p")
> emm.p
 p   response    SE  df asymp.LCL asymp.UCL
 a1      4.18 0.147 Inf      3.90      4.48
 a10     3.94 0.127 Inf      3.70      4.20
 a11     3.96 0.136 Inf      3.70      4.24
 a12     3.78 0.127 Inf      3.54      4.03
 a13     4.10 0.136 Inf      3.84      4.37
 a14     3.77 0.125 Inf      3.54      4.03
 a15     4.09 0.131 Inf      3.85      4.36
 a16     4.02 0.123 Inf      3.78      4.27
 a17     4.10 0.131 Inf      3.86      4.37
 a18     4.19 0.137 Inf      3.93      4.47
 a19     3.84 0.127 Inf      3.60      4.09
 a2      3.87 0.127 Inf      3.63      4.13
 a20     3.84 0.124 Inf      3.61      4.10
 a21     3.94 0.125 Inf      3.70      4.19
 a22     3.94 0.128 Inf      3.70      4.20
 a23     4.10 0.135 Inf      3.84      4.37
 a24     4.09 0.134 Inf      3.84      4.36
 a25     3.83 0.129 Inf      3.58      4.09
 a26     4.22 0.143 Inf      3.94      4.51
 a27     3.96 0.129 Inf      3.72      4.22
 a28     4.11 0.138 Inf      3.85      4.39
 a29     3.95 0.131 Inf      3.70      4.22
 a3      3.98 0.135 Inf      3.72      4.25
 a30     4.15 0.139 Inf      3.89      4.43
 a31     4.00 0.132 Inf      3.75      4.27
 a32     3.89 0.131 Inf      3.64      4.16
 a33     4.15 0.136 Inf      3.89      4.43
 a34     3.87 0.126 Inf      3.63      4.13
 a35     4.09 0.143 Inf      3.82      4.38
 a36     4.20 0.140 Inf      3.94      4.48
 a37     3.97 0.134 Inf      3.71      4.24
 a38     4.15 0.136 Inf      3.89      4.43
 a39     4.00 0.125 Inf      3.76      4.25
 a4      4.11 0.137 Inf      3.85      4.38
 a40     4.03 0.134 Inf      3.77      4.30
 a41     3.93 0.128 Inf      3.69      4.19
 a42     3.92 0.128 Inf      3.68      4.18
 a43     3.88 0.126 Inf      3.64      4.13
 a44     3.99 0.131 Inf      3.75      4.26
 a45     3.96 0.127 Inf      3.71      4.21
 a46     4.02 0.133 Inf      3.77      4.29
 a47     3.78 0.130 Inf      3.53      4.04
 a48     4.00 0.131 Inf      3.75      4.26
 a49     3.94 0.129 Inf      3.69      4.20
 a5      3.97 0.126 Inf      3.74      4.23
 a50     4.07 0.132 Inf      3.82      4.34
 a6      4.06 0.133 Inf      3.80      4.33
 a7      4.19 0.136 Inf      3.94      4.47
 a8      3.79 0.126 Inf      3.55      4.05
 a9      4.21 0.137 Inf      3.95      4.48

Results are averaged over the levels of: 13 nuisance factors, a, b 
Confidence level used: 0.95 
Intervals are back-transformed from the log scale
```
In addition, I've added a trap for this kind of situation. With your original call, we get:
```r
 emmeans(model,"p",type="response")
 Error in .check.grid(ref.levels, rg.limit) : 
  The size of your requested reference grid would be 46080000, which exceeds
the limit of 1e+05. your options are:
  1. Specify some (or more) nuisance factors using the 'nuisance' argument
     (see ?ref_grid). These must be factors that do not interact with others.
  2. Add the argument 'rg.limit = <new limit>' to the call. Be careful,
     because this could cause excessive memory use and performance issues.
     Or, change the default via 'emm_options(rg.limit = <new limit>)'. 
```
