### ISSUE TITLE
Comparison arrows not showing in plot.emmGrid()

### ISSUE THREAD

**Issue by peterinnes** [rvlenth/emmeans#321] opened 2021-12-15 18:22 UTC
I'm having issues with the plot.emmGrid() function. The comparison arrows seem to not plot properly when only `specs` but not `by` is specified in the `emmeans` function. 

To begin, this seems to work as expected:
```
library(emmeans)

pigs.lm = lm(log(conc) ~ source + factor(percent), data = pigs)

emm1 = emmeans::emmeans(pigs.lm, specs = "source", by = "percent")
emmeans:::plot.emmGrid(emm1, comparisons = T)
```
![pig_emm1](https://user-images.githubusercontent.com/49176750/146240734-95e5314e-21b4-4d26-8e05-ebdce3e2c454.png)

But if I only consider the estimated marginal means of `source` averaged over `conc` (i.e. leaving out `by="percent"`), comparison arrows all but disappear:
```
emm2 = emmeans(pigs.lm, specs = "source")
emmeans:::plot.emmGrid(emm2, comparisons = T)
```
![pig_emm2](https://user-images.githubusercontent.com/49176750/146240739-d9bc1f5c-4f62-48c1-b45d-8e2c811e55f9.png)

I think `soy` and `skim` should have overlapping comparison arrows based on `contrasts`:
```
contrasts <- emmeans::emmeans(object=pigs.lm, pairwise ~ "source")
```
```
$contrasts
 contrast    estimate     SE df t.ratio p.value
 fish - soy    -0.273 0.0529 23  -5.153  0.0001
 fish - skim   -0.402 0.0542 23  -7.428  <.0001
 soy - skim    -0.130 0.0530 23  -2.442  0.0570

```

I'd appreciate any insight you might have on this as I believe it was working previously. I'm running R v4.1.1 and have emmeans 1.7.1 installed. Thank you!

**Comment by rvlenth** [comment] 2021-12-15 18:36
Hmmm. I confirm this. Indeed, the plot should look exactly like one of the panels of the previous plot, since the model is additive. The comparison limits come out right at the means:
```
> plot(emm2, comparisons = TRUE, plotit = FALSE)
  source the.emmean         SE df lower.CL upper.CL pri.fac   lcmpl    rcmpl
1   fish   3.394492 0.03668122 23 3.318612 3.470373    fish      NA 3.394492
2    soy   3.667260 0.03744798 23 3.589793 3.744727     soy 3.66726 3.667260
3   skim   3.796770 0.03938283 23 3.715300 3.878240    skim 3.79677       NA
```
Very mysterious...

**Comment by rvlenth** [comment] 2021-12-15 19:01
OK, I figured it out. It's due to an internal routine `.validate.names()` I added to ensure that all names are valid. If the `by.vars` attribute is NULL, then it replaces it with `character(0)` which isn't quite the same thing:
```
> summ = confint(pairs(emm2))

> summ
 contrast    estimate     SE df lower.CL upper.CL
 fish - soy    -0.273 0.0529 23   -0.405 -0.14020
 fish - skim   -0.402 0.0542 23   -0.538 -0.26664
 soy - skim    -0.130 0.0530 23   -0.262  0.00333

Results are averaged over the levels of: percent 
Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
Conf-level adjustment: tukey method for comparing a family of 3 estimates 

> attr(summ, "by.vars")
NULL

> attr(summ, "by.vars") = make.names(NULL)
> summ
Results are averaged over the levels of: percent 
Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
Conf-level adjustment: tukey method for comparing a family of 3 estimates 
```
I have fixed this and now it works.
```
> plot(emm2, comp = TRUE, plotit = FALSE)
  source the.emmean         SE df lower.CL upper.CL pri.fac    lcmpl    rcmpl
1   fish   3.394492 0.03668122 23 3.318612 3.470373    fish       NA 3.462197
2    soy   3.667260 0.03744798 23 3.589793 3.744727     soy 3.602362 3.732212
3   skim   3.796770 0.03938283 23 3.715300 3.878240    skim 3.728877       NA
```
Thanks for reporting this.

**Comment by rvlenth** [comment] 2021-12-15 19:23
The sad thing is that this bug is probably not so severe that I want to beg CRAN to allow an emergency update; but yet the problem is visible in vignettes such as https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html#graphical and https://cran.r-project.org/web/packages/emmeans/vignettes/xplanations.html#arrows

**Comment by peterinnes** [comment] 2021-12-15 19:30
Thanks so much for the quick fix!! You're life saver. I reinstalled with the dev version  `remotes::install_github("rvlenth/emmeans")` and its working now.

**Comment by rvlenth** [comment] 2021-12-15 19:57
For the benefit of users who don't install the fixed version, there is no problem as long as there is a `by` variable. If there is none, here is a workaround that works with Version 1.7.1-1:
```
emm3 = add_grouping(emm2, "dummy", "source", rep(1, 3))
plot(emm3, comp = TRUE, by = "dummy") + ggplot2::facet_grid(NULL)
```
The idea is that we have to have a non-NULL `by` variable, so we create a grouping variable that has only one level, then use it as a `by` variable. And in plotting, disable displaying it in panel style.

**Comment by rvlenth** [comment] 2022-01-18 22:39
This is resolved and the fix for the error is incorporated in the newest CRAN version; so closing.

**Closed by rvlenth** 2022-01-18 22:39 UTC
