### ISSUE TITLE
Error in emmeans: no variable named X in the reference grid

### ISSUE THREAD

**Issue by papavientos** [rvlenth/emmeans#251] opened 2020-12-30 10:23 UTC
Hi, this is my first post here in GitHub! 

I would like to know which is the problem with my code as I get this warning when I try to carry a path analysis using piecewiseSEM. I am self taught student and I am performing a path analysis as a recommendation from a colleague. I think it would be better to give you some background to know how it is my data and the question I am trying to addressed with the path analysis.

I study a population of birds in which some of them are not able to get a territory in their first breeding season whereas some other do it. So we can differentiate two reproductive status: floaters (those which don't get a place to breed) and breeders. Our question in this work was if there were any phenotypical traits that may be associated with this reproductive status, so we conducted a logistic regression model for reproductive status dependent on several phenotypical traits (body condition, ornamentation and behaviour). We conducted this logistic regression for **adult and nestling measurements**. And we found that body condition was positively associated with breeder status: as body condition increases, so does likelihood of becoming a breeder in the population.

So, one workmate recommended me to perform a path analysis for those individuals of which we have both nestling and adult measurements, to know how this relationship between nestling and adult condition would be when accounting for the relationship between nestling condition and adult condition, as they are correlated to some extent. 

However, when I build my psem objetc with the paths, formed by a binomial first model and followed by linear models resuming the relationship between other variables, I got the following error: 

`q1=psem(
  reproductive.status = glm(status ~ adult_condition + nestling_condition + ornamentation + aggressiveness + screaming, family = "binomial", data = data),`

  `adult.condition = lm(adult_condition ~ nestling_condition, data = data),`

 `feather.length = lm(ornamentation ~ adult_condition, data = data),`

  `nestling.condition = lm(nestling_condition ~ birth_date + brood_size, data = data),`

  `total_pecking%~~%screaming)`

`summary(q1)`

`  |======================================================                                               |  54%`
`Error in emmeans::emmeans(model, specs = v, data = data) : 
 No variable named status in the reference grid`

I don't know what this error means, but I checked that my binomial variable (status) was coded as a factor and I can't solve this problem. So, I could really use help. I also put this issue in the piecewiseSEM page, and I thought maybe I could use some help in this site too if anyone knows how to fix this problem.

Thank you! 

Iraida.

**Comment by rvlenth** [comment] 2020-12-30 15:06
I really have no clue, as I have never used the piecewiseSEM package. It appears that the summary method for your model relies somehow on emmeans, and that's why it's shown in the error message. I note that status is the DEPENDENT variable in the glm() part of your call, and emmeans() works only with the predictors, not the response. That makes me speculate that somehow you have misspecified something in the psem() call -- because somehow it must interpret that status is a predictor.

Sent from my iPad

On Dec 30, 2020, at 4:24 AM, papavientos <notifications@github.com> wrote:

﻿

Hi, this is my first post here in GitHub!

I would like to know which is the problem with my code as I get this warning when I try to carry a path analysis using piecewiseSEM. I am self taught student and I am performing a path analysis as a recommendation from a colleague. I think it would be better to give you some background to know how it is my data and the question I am trying to addressed with the path analysis.

I study a population of birds in which some of them are not able to get a territory in their first breeding season whereas some other do it. So we can differentiate two reproductive status: floaters (those which don't get a place to breed) and breeders. Our question in this work was if there were any phenotypical traits that may be associated with this reproductive status, so we conducted a logistic regression model for reproductive status dependent on several phenotypical traits (body condition, ornamentation and behaviour). We conducted this logistic regression for adult and nestling measurements. And we found that body condition was positively associated with breeder status: as body condition increases, so does likelihood of becoming a breeder in the population.

So, one workmate recommended me to perform a path analysis for those individuals of which we have both nestling and adult measurements, to know how this relationship between nestling and adult condition would be when accounting for the relationship between nestling condition and adult condition, as they are correlated to some extent.

However, when I build my psem objetc with the paths, formed by a binomial first model and followed by linear models resuming the relationship between other variables, I got the following error:

q1=psem( reproductive.status = glm(status ~ adult_condition + nestling_condition + ornamentation + aggressiveness + screaming, family = "binomial", data = data),

adult.condition = lm(adult_condition ~ nestling_condition, data = data),

feather.length = lm(ornamentation ~ adult_condition, data = data),

nestling.condition = lm(nestling_condition ~ birth_date + brood_size, data = data),

total_pecking%~~%screaming)

summary(q1)

|====================================================== | 54%
Error in emmeans::emmeans(model, specs = v, data = data) : No variable named status in the reference grid

I don't know what this error means, but I checked that my binomial variable (status) was coded as a factor and I can't solve this problem. So, I could really use help. I also put this issue in the piecewiseSEM page, and I thought maybe I could use some help in this site too if anyone knows how to fix this problem.

Thank you!

Iraida.

**Comment by rvlenth** [comment] 2020-12-30 17:59
Looking at the documentation for psem(), I wondrr if you need to add 'data = data' to the model-fitting call. Worth a try, anyway.

Sent from my iPad

On Dec 30, 2020, at 4:24 AM, papavientos <notifications@github.com> wrote:

﻿

Hi, this is my first post here in GitHub!

I would like to know which is the problem with my code as I get this warning when I try to carry a path analysis using piecewiseSEM. I am self taught student and I am performing a path analysis as a recommendation from a colleague. I think it would be better to give you some background to know how it is my data and the question I am trying to addressed with the path analysis.

I study a population of birds in which some of them are not able to get a territory in their first breeding season whereas some other do it. So we can differentiate two reproductive status: floaters (those which don't get a place to breed) and breeders. Our question in this work was if there were any phenotypical traits that may be associated with this reproductive status, so we conducted a logistic regression model for reproductive status dependent on several phenotypical traits (body condition, ornamentation and behaviour). We conducted this logistic regression for adult and nestling measurements. And we found that body condition was positively associated with breeder status: as body condition increases, so does likelihood of becoming a breeder in the population.

So, one workmate recommended me to perform a path analysis for those individuals of which we have both nestling and adult measurements, to know how this relationship between nestling and adult condition would be when accounting for the relationship between nestling condition and adult condition, as they are correlated to some extent.

However, when I build my psem objetc with the paths, formed by a binomial first model and followed by linear models resuming the relationship between other variables, I got the following error:

q1=psem( reproductive.status = glm(status ~ adult_condition + nestling_condition + ornamentation + aggressiveness + screaming, family = "binomial", data = data),

adult.condition = lm(adult_condition ~ nestling_condition, data = data),

feather.length = lm(ornamentation ~ adult_condition, data = data),

nestling.condition = lm(nestling_condition ~ birth_date + brood_size, data = data),

total_pecking%~~%screaming)

summary(q1)

|====================================================== | 54%
Error in emmeans::emmeans(model, specs = v, data = data) : No variable named status in the reference grid

I don't know what this error means, but I checked that my binomial variable (status) was coded as a factor and I can't solve this problem. So, I could really use help. I also put this issue in the piecewiseSEM page, and I thought maybe I could use some help in this site too if anyone knows how to fix this problem.

Thank you!

Iraida.

**Comment by SamJoness** [comment] 2021-01-13 16:27
Hello Iraida,
Have you found a solution to this problem yet? I am having the exact same issue and I have tried everything I can think of to solve it. The only time I have this issue is when I have a binomial as the response variable, the package works perfectly otherwise. 
I would love to find out if you have found a solution to this!

**Comment by rvlenth** [comment] 2021-01-13 16:33
Could one of you post here a simple example that I can reproduce and test? I just need the model and data, hopefully small.

**Comment by papavientos** [comment] 2021-01-13 16:34
@SamJoness Hi Sam! 

I am sorry to hear that you have this issue too! I am planning to send some script and data  to see where is the problem (I am very busy at this time!)

The only thing I can recommend you is giving a try (I will do it as soon as I can) at uninstalling all your packages from RStudio (if possible) and install and load only those you need for building the psem object and call the summary. I don't know if this would work but I am recommending you this because I sent my script and dataset to 2 colleagues and all ran perfectly. 

So, I don't know if it has to do with problems between versions of packages, masked functions or anything like that. Hope it works!

**Comment by SamJoness** [comment] 2021-01-13 19:12
I exported my df as a .csv so that you could replicate the error using my data. I open a new script to run the problem code with the .cvs to ensure you would get the same error. The code worked fine.
 
I went back to my original code (fairly extensive) and I still got the same error only when the response variable is a binomial. I imported the .cvs file (the one I just exported - so it is the exact same data) into my original script and it worked. 

Here is a picture of the code with the error, exporting the df to a .csv, importing the .csv, and then the code working. Not sure what the glitch is, but it is working!  Thanks for the quick response!

![pSEM](https://user-images.githubusercontent.com/77403183/104497456-5f7fa680-55a8-11eb-9eb2-4d409942d3e9.JPG)

**Comment by rvlenth** [comment] 2021-01-13 20:09
I set a breakpoint for the beginning of `emmeans()` and this is what I see:
```r
Browse[1]> n
debug at C:/Users/rlenth/Documents/rvlhome/progs/R/devel/EMMEANS/emmeans/R/emmeans.R#296: if (!is(object, "emmGrid")) {
    args = .zap.args(object = object, ..., omit = "submodel")
    object = do.call(ref_grid, args)
}
Browse[2]> object

Call:  glm(formula = status ~ nestling_condition + adult_condition + 
    feather_length + total_pecking + screaming + run_day_eclosion + 
    p14, family = "binomial", data = data)

Coefficients:
       (Intercept)  nestling_condition     adult_condition      feather_length  
         -1.657183            0.339676            0.313976            0.045855  
     total_pecking           screaming    run_day_eclosion                 p14  
         -0.029497            0.221585            0.006156            0.103621  

Degrees of Freedom: 265 Total (i.e. Null);  258 Residual
Null Deviance:	    355.1 
Residual Deviance: 340.1 	AIC: 356.1

Browse[2]> class(object)
[1] "glm" "lm" 

Browse[2]> specs
[1] "status"

Browse[2]> ref_grid(object)
'emmGrid' object with variables:
    nestling_condition = 7.5188e-12
    adult_condition = 2.6316e-11
    feather_length = 35.363
    total_pecking = 4.6015
    screaming = 0.2594
    run_day_eclosion = 30.598
    p14 = 3.9624
Transformation: “logit” 
```
So what is happening is that your `specs` argument in `emmeans()` is asking for EMMs for the *response* variable, `status`. The specs should only include *predictors*, of which there are several.

I am only speculating, but I'm guessing that this is an `emmeans()` call that you should have skipped, inasmuch as you'll only want to call it when the response is among the predictors in another model. Am I correct? 

Is there a logic error in how these `emmeans()` calls are determined, e.g., that factors are included regardless? I speculate this because it seems from the discussion that this problem occurs only when the response is a factor. 

FWIW, I know that an easy way to strip off the response variable is via `delete.response()` (for a `terms` object).

Hope this helps

**Comment by rvlenth** [comment] 2021-01-13 20:25
FWIW, I do get reasonable-looking answers if I re-read the data and do:
```r
> data$status = 0 + (data$status == "R")
> q1 <- psem(
+     glm(status ~ nestling_condition + adult_condition + feather_length + total_pecking + screaming + run_day_eclosion + p14 , family = "binomial", data = data),
+     lm(adult_condition ~ nestling_condition + run_day_eclosion + p14 + feather_length + total_pecking + screaming , data = data),
+     lm(nestling_condition ~ run_day_eclosion + p14, data = data), total_pecking%~~%screaming, data=data)
> summary(q1)
  |=============================================================================================================| 100%

Structural Equation Model of q1 

Call:
  status ~ nestling_condition + adult_condition + feather_length + total_pecking + screaming + run_day_eclosion + p14
  adult_condition ~ nestling_condition + run_day_eclosion + p14 + feather_length + total_pecking + screaming
  nestling_condition ~ run_day_eclosion + p14
  total_pecking ~~ screaming

    AIC      BIC
 42.884   114.554

---
Tests of directed separation:

                             Independ.Claim Test.Type  DF Crit.Value P.Value 
  nestling_condition ~ feather_length + ...      coef 262     0.2182  0.8274 
   nestling_condition ~ total_pecking + ...      coef 262     0.4850  0.6281 
       nestling_condition ~ screaming + ...      coef 262    -0.7481  0.4551 

Global goodness-of-fit:

  Fisher's C = 2.884 with P-value = 0.823 and on 6 degrees of freedom

---
Coefficients:

            Response          Predictor Estimate Std.Error  DF Crit.Value P.Value Std.Estimate    
              status nestling_condition   0.3397    0.1688 258     2.0121  0.0442       0.1550   *
              status    adult_condition   0.3140    0.1553 258     2.0219  0.0432       0.1536   *
              status     feather_length   0.0459    0.0438 258     1.0463  0.2954       0.0742    
              status      total_pecking  -0.0295    0.0377 258    -0.7829  0.4337      -0.0552    
              status          screaming   0.2216    0.2477 258     0.8947  0.3709       0.0642    
              status   run_day_eclosion   0.0062    0.0082 258     0.7550  0.4502       0.0562    
              status                p14   0.1036     0.139 258     0.7455  0.4560       0.0523    
     adult_condition nestling_condition   0.3353     0.065 259     5.1574  0.0000       0.3129 ***
     adult_condition   run_day_eclosion  -0.0036    0.0033 259    -1.0935  0.2752      -0.0680    
     adult_condition                p14  -0.0078    0.0576 259    -0.1351  0.8926      -0.0080    
     adult_condition     feather_length   0.0411    0.0175 259     2.3468  0.0197       0.1360   *
     adult_condition      total_pecking  -0.0001    0.0154 259    -0.0092  0.9927      -0.0005    
     adult_condition          screaming  -0.0137    0.0987 259    -0.1385  0.8900      -0.0081    
  nestling_condition   run_day_eclosion  -0.0153     0.003 263    -5.1052  0.0000      -0.3055 ***
  nestling_condition                p14  -0.0456    0.0541 263    -0.8433  0.3998      -0.0505    
     ~~total_pecking        ~~screaming   0.1244         - 264     2.0370  0.0426       0.1244   *

  Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05

---
Individual R-squared:

            Response     method R.squared
              status nagelkerke      0.07
     adult_condition       none      0.14
  nestling_condition       none      0.09
```

BTW, I also note that your `summary` method calls `multcomp::cld(emmeans(...))`. The `cld()` part of this generates compact-letter-display groupings for pairwise comparisons, but I don't see evidence of these groupings in the output. If you don't need those groupings, there's a whole heck of a lot of computation you can skip. You can just use `as.data.frame(emmeans(...))` if you need it as a data frame.

**Comment by rvlenth** [comment] 2021-01-13 20:26
Moreover, I recommend against CLDs anyway because those groupings are NON-findings rather than findings.

**Comment by papavientos** [comment] 2021-01-14 11:41
@SamJoness Hey!!!! I tried the same thing and IT WORKED! 

I am starting to think that one of my problems could be that before performing the path analysis I've already run other models with status and my variables and for some reason I don't know, it may cause summary() to not recognize my *actually* psem model.

@rvlenth Thank you too for all the effort!!! So much appreciated!!!


Yay, so happy!

**Comment by rvlenth** [comment] 2021-02-02 19:12
I think this issue is pretty much resolved, so closing

**Closed by rvlenth** 2021-02-02 19:12 UTC
