### ISSUE TITLE
Factors coded as "factor" vs "character" - using character seems to ignore any weights= argument

### ISSUE THREAD

**Issue by felixthoemmes** [rvlenth/emmeans#23] opened 2018-03-23 02:15 UTC
Hello,
The following issue was discovered by one of my undergrads working on a homework assignment. In unbalanced factorial designs (in which the weights= option should typically result in different estimates), the weights= argument in emmeans is ignored if one of the factors is a string (as opposed to a factor). The result is surprising because (obviously) both the lm statement (and also the emmeans statement) run this model without issues. In fact, as expected the lm statement using either a variable that is a factor or a character yield identical results. 

Here is a minimally reproducible example:

`t1 <- c(0,0,0,0,0,0,1,1,1,1,1,1)`
`t2 <- c("C","C","C","T","T","C","T","T","T","C","C","C")`
`y <- c(1,2,3,4,5,6,7,8,9,10,1,2)`
` `
`df <- data.frame(t1,t2,y)`
`df$t1 <- as.factor(df$t1)`
`df$t2_chr <- as.character(df$t2)`
`str(df)`
` `
`lm1 <- lm(y~t1*t2,data=df)`
`lm2 <- lm(y~t1*t2_chr,data=df)`
` `
`all.equal(as.numeric(lm1$coefficients),as.numeric(lm2$coefficients))`
` `
`library(emmeans)`
` `
`e1 <- emmeans(lm1,"t1",weights="proportional")`
`e2 <- emmeans(lm1,"t1",weights="equal")`
`all.equal(e1,e2)`
` `
` `
`b1 <- emmeans(lm2,"t1",weights="proportional")`
`b2 <- emmeans(lm2,"t1",weights="equal")`
`all.equal(b1,b2)`

**Comment by rvlenth** [comment] 2018-03-23 02:30
Thanks for the report. I'll look into it and I appreciate the reproducible example.

I'm not sure how big a can of worms this will open, but I'm hoping it's fairly easily fixed. I'll keep you informed.

**Comment by rvlenth** [comment] 2018-03-26 15:34
Looks like the worm-can was pretty small; just some code in `ref_grid` where the `.wgt.` column of the `@grid` slot is determined, and character predictors had been ignored.

**Comment by rvlenth** [comment] 2018-04-02 18:52
Closing as I think it is addressed in CRAN version 1.1.3. But let me know if there are more concerns.

**Closed by rvlenth** 2018-04-02 18:52 UTC
Labels: bug
